### ISSUE TITLE
TypeError: StockTradingEnv.reset() got an unexpected keyword argument 'seed'

### ISSUE THREAD

**Issue by LunbiWa** [AI4Finance-Foundation/FinRL#1022]
Run Stock_NeurIPS2018_2_Train.ipynb in FinRL/examples

Colab report error

![image](https://github.com/AI4Finance-Foundation/FinRL/assets/112242664/3f45e6a3-c9c3-49c9-81ea-98ae1519cb66)

thanks!

**Comment by thinkscriptfan** [comment]
i am running to the same error
TypeError: StockTradingEnv.reset() got an unexpected keyword argument 'seed'

**Comment by Dharmendra-G-1** [comment]
Hello, I am also getting same above error on Colab, when running the Stock_NeurIPS2018_2_Train.ipynb from FinRL-Tutorials/1-Introduction/Stock_NeurIPS2018/Stock_NeurIPS2018_2_Train.ipynb python at 

**Environment for training command**

```
env_train, _ = e_train_gym.get_sb_env()
print(type(env_train))
```

**Comment by MariamaB** [comment]
Hi, I have the same issue when running:

df_summary = ensemble_agent.run_ensemble_strategy(A2C_model_kwargs,
                                                 PPO_model_kwargs,
                                                 DDPG_model_kwargs,
                                                 timesteps_dict)

in: FinRL/examples/FinRL_Ensemble_StockTrading_ICAIF_2020.ipynb

**Comment by Abhilaksh1498** [comment]
With the latest version of stable-baselines3 (2.0.0a10), I also get the same error. 
![image](https://github.com/AI4Finance-Foundation/FinRL/assets/46315184/f92251c8-29b8-49c6-8680-d50315070763)





However when I downgrade it to say v1.5.0 I get the following error. 

![image](https://github.com/AI4Finance-Foundation/FinRL/assets/46315184/aa38fbb3-ed42-40ef-beba-45e22b754474)

Any help would be greatly appreciated!
Thanks in advance

**Comment by AkashKarnatak** [comment]
`StockTradingEnv.reset()`' doesn't take any arguments. You can fix this by changing line 358 of `finrl/meta/env_stock_trading/env_stocktrading.py` from

```
    def reset(self):
```
to
```
    def reset(self, seed=None):
```

**Comment by thinkscriptfan** [comment]
tired the proposed change to the file line 358 def reset(self, seed=None):  , got this:
TypeError:  StockTradingEnv.reset() , got an unexpected keyword argument 'seed'

**Comment by AkashKarnatak** [comment]
Which file did you exactly change? Was it directly inside site-packages folder?

**Comment by ZCKAO** [comment]
Hi! I'm running into the same error, when running the Stock_NeurIPS2018_SB3.ipynb on Colab from 
AI4Finance-Foundation/FinRL/examples/Stock_NeurIPS2018_SB3.ipynb
```TypeError: StockTradingEnv.reset() got an unexpected keyword argument 'seed'```

**Comment by thinkscriptfan** [comment]
the proposed change from
finrl/meta/env_stock_trading/env_stocktrading.py from

   def reset(self):
to
    def reset(self, seed=None):
does work . 
 I was not pulling the repository correctly.  thank you .

**Comment by thinkscriptfan** [comment]
there is now error symthom as bug #1010

ValueError: If using all scalar values, you must pass an index #1010

**Comment by kilmern** [comment]
Also getting the same error @thinkscriptfan pointed.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-f7216cfcab9f> in <module>
----> 1 df_summary = ensemble_agent.run_ensemble_strategy(A2C_model_kwargs,
      2                                                  PPO_model_kwargs,
      3                                                  DDPG_model_kwargs,
      4                                                  timesteps_dict)

~/.local/lib/python3.10/site-packages/finrl/agents/stablebaselines3/models.py in run_ensemble_strategy(self, A2C_model_kwargs, PPO_model_kwargs, DDPG_model_kwargs, timesteps_dict)
    666             )
    667             # print("Used Model: ", model_ensemble)
--> 668             last_state_ensemble = self.DRL_prediction(
    669                 model=model_ensemble,
    670                 name="ensemble",

~/.local/lib/python3.10/site-packages/finrl/agents/stablebaselines3/models.py in DRL_prediction(self, model, name, last_state, iter_num, turbulence_threshold, initial)
    319                 last_state = trade_env.render()
    320 
--> 321         df_last_state = pd.DataFrame({"last_state": last_state})
    322         df_last_state.to_csv(f"results/last_state_{name}_{i}.csv", index=False)
    323         return last_state

~/.local/lib/python3.10/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    707         elif isinstance(data, dict):
    708             # GH#38939 de facto copy defaults to False only in non-dict cases
--> 709             mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
    710         elif isinstance(data, ma.MaskedArray):
    711             from numpy.ma import mrecords

~/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py in dict_to_mgr(data, index, columns, dtype, typ, copy)
    479             arrays = [x.copy() if hasattr(x, "dtype") else x for x in arrays]
    480 
--> 481     return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
    482 
    483 

~/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py in arrays_to_mgr(arrays, columns, index, dtype, verify_integrity, typ, consolidate)
    113         # figure out the index, if necessary
    114         if index is None:
--> 115             index = _extract_index(arrays)
    116         else:
    117             index = ensure_index(index)

~/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py in _extract_index(data)
    643 
    644     if not indexes and not raw_lengths:
--> 645         raise ValueError("If using all scalar values, you must pass an index")
    646 
    647     if have_series:

ValueError: If using all scalar values, you must pass an index
```

**Comment by srikantamehta** [comment]
Fixed by modifying StockTradingEnv class: 

`class MyStockTradingEnv(StockTradingEnv):
    def reset(self, seed=None):
        # Call the parent class's reset method, which doesn't expect a seed
        return super().reset()`

**Comment by srikantamehta** [comment]
You can fix this by making modified class for StockTradingEnv: 
 
```
class MyStockTradingEnv(StockTradingEnv):
    def reset(self, seed=None):
        # Call the parent class's reset method, which doesn't expect a seed
        return super().reset()
```

**Comment by ZCKAO** [comment]
> 
Thanks your idea! Does anything should be change in other lines? I mean to call the new class MyStockTradingEnv.

**Comment by ZCKAO** [comment]
> You can fix this by making modified class for StockTradingEnv:
> 
> ```
> class MyStockTradingEnv(StockTradingEnv):
>     def reset(self, seed=None):
>         # Call the parent class's reset method, which doesn't expect a seed
>         return super().reset()
> ```


Thanks your idea! Does anything should be change in other lines? I mean to call the new class MyStockTradingEnv.

**Comment by thinkscriptfan** [comment]
I am new to Python , can you please clarify which area the above code was inserted ?  thanks in advance.

**Comment by srikantamehta** [comment]
Right before calling the StockTradingEnv class. Place this before and then change StockTradingEnv to MyStockTradingEnv

**Comment by thinkscriptfan** [comment]
Sorry , Still not clear . , where is StockTradingEnv class called ? which file , which line ?

**Comment by AkashKarnatak** [comment]
srikantamehta is suggesting an alternative way to my solution of fixing the above problem. For #1010, you can try this solution https://github.com/AI4Finance-Foundation/FinRL/issues/1010#issuecomment-1585580373

**Comment by sardpl** [comment]
The "StockTradingEnv.reset()" error should be related to modifications to the Release 2.0.0aXX (WIP) of Stable-Baselines3.
The Change log says:
"Because of new Gym API (0.26+), the random seed passed to vec_env.seed(seed=seed) will only be effective after then env.reset() call." 
The standard installation procedure for Windows of FinRL gets the latest version of stable baselines. I have manually downgraded to v. 2.0.0a5 and the error disappears, but I don't know if something is broken within Gym.
