### ISSUE TITLE
Installation process can skip cuda-pytorch

### ISSUE THREAD

**Issue by icsl-Jeon** [AI4Finance-Foundation/FinRL#1023]
**Describe the bug**

Thank you for wonderful OpenSource project!

The installation guide [here](https://github.com/AI4Finance-Foundation/FinRL/blob/master/docs/source/start/installation.rst), which uses `pip install .`, can install pytorch cpu version. If this is the case, users cannot use gpu when training. 

I think it would be better to instruct users that the below pytorch install might be required 
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117` 

**To Reproduce**
We can simply check the below after installing FinRL on a clean conda env. 
```py
import torch
torch.cuda.is_available()
```

**Comment by XiaoYangLiu-FinRL** [comment]
> **Describe the bug**
> 
> Thank you for wonderful OpenSource project!
> 
> The installation guide [here](https://github.com/AI4Finance-Foundation/FinRL/blob/master/docs/source/start/installation.rst), which uses `pip install .`, can install pytorch cpu version. If this is the case, users cannot use gpu when training.
> 
> I think it would be better to instruct users that the below pytorch install might be required `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117`
> 
> **To Reproduce** We can simply check the below after installing FinRL on a clean conda env.
> 
> ```python
> import torch
> torch.cuda.is_available()
> ```

Thanks very much for this feedback!

**Comment by zhumingpassional** [comment]
@icsl-Jeon 
thanks for your suggestions
w.r.t torch, it depends on users' demand, e.g., OS, gpu/cpu
the install docs focus on installing finrl
