### ISSUE TITLE
msi_pc\Python3.9.10\Lib\site-packages\finrl\applications\stock_trading.py To fix the issue of overlapping dates on the x-axis

### ISSUE THREAD

**Issue by omerfirat** [AI4Finance-Foundation/FinRL#1059]
overlapping dates on the x-axixs are not readble Can you help me how can i fix it?

![stock_trading](https://github.com/AI4Finance-Foundation/FinRL/assets/11609018/2abccb42-a857-4230-8bc5-d1455f412c51)

**Comment by nuoheizi** [comment]
At the moment, you can rotate the xticks by setting the parameter “xrotation=20” of the plot function (FinRL/finrl/plot/plot_result), although this may still not achieve the effect you want. Further improvements may require modifying the source code.

**Comment by zhumingpassional** [comment]
pls try functions of finrl.plot, or write your own functions as reference.
