### ISSUE TITLE
KeyError: '2009-05-18' --- Missing Data Causes error

### ISSUE THREAD

**Issue by Youbadawy** [AI4Finance-Foundation/FinRL#109]
When calling the 
```
e_train_gym = StockTradingEnvCashpenalty(df = train,initial_amount = 1e6,hmax = 5000, 
                                turbulence_threshold = None, 
                                currency='$',
                                buy_cost_pct=3e-3,
                                sell_cost_pct=3e-3,
                                cash_penalty_proportion=0.2,
                                cache_indicator_data=True,
                                daily_information_cols = information_cols, 
                                print_verbosity = 500, 
                                random_start = False)
```
Causes the below error, only deviation between mine and spencer's notebook was  a few rows of missing data, I extracted the indicated date, and provided me a dataframe with the below data. (below is a snippet)

![image](https://user-images.githubusercontent.com/44686731/106648187-90bf1700-6555-11eb-985b-1b7eebeae4c7.png)

```
caching data

---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2897             try:
-> 2898                 return self._engine.get_loc(casted_key)
   2899             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: '2009-05-18'


The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)

10 frames

/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2898                 return self._engine.get_loc(casted_key)
   2899             except KeyError as err:
-> 2900                 raise KeyError(key) from err
   2901 
   2902         if tolerance is not None:

KeyError: '2009-05-18'
```

@spencerR1992 @BruceYanghy

**Comment by spencerR1992** [comment]
Hi @Youbadawy , you might unfortunately have missing data in your dataframe. Can you please make sure that the unique stock indicators are all present in this index? It seems that you might have a missing data point for a single stock. 

Does the behavior persist if you set `cache_indicator_data` to `False`?

**Comment by Youbadawy** [comment]
Hello @spencerR1992 thanks for answering! I have used the config ticker list provided with the project. but I do see a slight deviation between my notebook and yours, your Dataframe.Shape is (90630,8), while mine is (90570,8) even thou I used the same time frame...

When I set `cache_indicator_data` to `False `it does not persist no

**Comment by acertainKnight** [comment]
I found this issue as well. If a ticker was not available for the full range of data this issue arises. For example, if Ali Baba (BABA), which did not exist before 2015, is included in the data set then there will be an issue when caching the data. The function that caches the data requires that all of the tickers have complete data for the full timeframe. I made adjustments to fill in missing dates with zeros but this leads to errors when computing/updating states in the environment. This is definitely an issue that should get looked at and additional functionality be added.

**Comment by Waterkin** [comment]
Now that filling missing data didn't work, except for setting cache_indicator_data to False, are there any solutions to the problem?

**Comment by zhumingpassional** [comment]
If we set cache_indicator_data to true, we have to fill the missing data, which requires more work. Please set cache_indicator_data to False, and fill missing data, which is the best solution now.

**Comment by zhumingpassional** [comment]
We will develop the filling missing data function if cache_indicator_data = true in the future. 

@acertainKnight You can fill the missing data by open=close=high=low price, not zero. You can try.
