### ISSUE TITLE
How to use other parameters as reward for the RL models to train?

### ISSUE THREAD

**Issue by Mr-Nobody-dey** [AI4Finance-Foundation/FinRL#1109]
In the examples mentioned in the repository, the models use portfolio value as reward. 
### **What if i want to use other parameter as reward?**

1. Do I need to redefine/build a new RL model for that task?
2. Or their is some other easy way?

**Describe the solution you'd like**
Please provide a solution in the tutorial repository.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by mmmarchetti** [comment]
Hello @Mr-Nobody-dey!
If you need to modify the reward calculation parameter, you can create a customized environment by cloning the project and making changes to the finrl/meta folder. Actually, the default environment does not offer this option.

**Comment by Mr-Nobody-dey** [comment]
Ok. Thank you for your comment.
