### ISSUE TITLE
Issue in FinRL_single_stock_trading.ipynb

### ISSUE THREAD

**Issue by Mostafasaeed29** [AI4Finance-Foundation/FinRL#114]
agent = DRLAgent(env = env_train)
TD3_PARAMS = {"batch_size": 128, 
              "buffer_size": 1000000, 
              "learning_rate": 0.0001}

model_td3 = agent.get_model("td3",model_kwargs = TD3_PARAMS)
trained_td3 = agent.train_model(model=model_td3, 
                             tb_log_name='td3',
                             total_timesteps=30000)
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-25-1a9611504b31> in <module>
      7 trained_td3 = agent.train_model(model=model_td3, 
      8                              tb_log_name='td3',
----> 9                              total_timesteps=30000)

~\Anaconda3\lib\site-packages\finrl\model\models.py in train_model(self, model, tb_log_name, total_timesteps)
    115 
    116     def train_model(self, model, tb_log_name, total_timesteps=5000):
--> 117         model = model.learn(total_timesteps=total_timesteps, tb_log_name=tb_log_name)
    118         return model

~\Anaconda3\lib\site-packages\stable_baselines3\td3\td3.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    203             tb_log_name=tb_log_name,
    204             eval_log_path=eval_log_path,
--> 205             reset_num_timesteps=reset_num_timesteps,
    206         )
    207 

~\Anaconda3\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    257                 learning_starts=self.learning_starts,
    258                 replay_buffer=self.replay_buffer,
--> 259                 log_interval=log_interval,
    260             )
    261 

~\Anaconda3\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py in collect_rollouts(self, env, callback, n_episodes, n_steps, action_noise, learning_starts, replay_buffer, log_interval)
    407 
    408                 # Rescale and perform action
--> 409                 new_obs, reward, done, infos = env.step(action)
    410 
    411                 self.num_timesteps += 1

~\Anaconda3\lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py in step(self, actions)
    148         """
    149         self.step_async(actions)
--> 150         return self.step_wait()
    151 
    152     def get_images(self) -> Sequence[np.ndarray]:

~\Anaconda3\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py in step_wait(self)
     42         for env_idx in range(self.num_envs):
     43             obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] = self.envs[env_idx].step(
---> 44                 self.actions[env_idx]
     45             )
     46             if self.buf_dones[env_idx]:

~\Anaconda3\lib\site-packages\finrl\env\env_stocktrading.py in step(self, actions)
    138             df_total_value['daily_return']=df_total_value.pct_change(1)
    139             sharpe = (252**0.5)*df_total_value['daily_return'].mean()/ \
--> 140                 df_total_value['daily_return'].std()
    141             df_rewards = pd.DataFrame(self.rewards_memory)
    142             if self.episode%self.print_verbosity ==0:

ZeroDivisionError: float division by zero

**Comment by XiaoYangLiu-FinRL** [comment]
Please check out the updated file. We have made substantial changes.

**Comment by b-tank1** [comment]
This notebook still doesn't seem to work.

trade = data_split(data_df, start = '2019-01-01', end = '2021-01-01')

e_trade_gym = StockTradingEnv(df = trade, **env_kwargs)
env_trade, obs_trade = e_trade_gym.get_sb_env()

df_account_value, df_actions = DRLAgent.DRL_prediction(model=trained_sac,
                                           trade_data  = trade,
                                           test_env = env_trade,
                                           test_obs = obs_trade)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-52459e78ba62> in <module>
      5 env_trade, obs_trade = e_trade_gym.get_sb_env()
      6 
----> 7 df_account_value, df_actions = DRLAgent.DRL_prediction(model=trained_sac,
      8                                            trade_data  = trade,
      9                                            test_env = env_trade,

TypeError: DRL_prediction() got an unexpected keyword argument 'trade_data'

**Comment by b-tank1** [comment]
I think the fix for #211 should work here.
