### ISSUE TITLE
Unable to add technical indicators for BSE500 (Indian) tickers

### ISSUE THREAD

**Issue by avipul751** [AI4Finance-Foundation/FinRL#1177]
**Describe the bug**
I have been trying to test the notebook [https://github.com/AI4Finance-Foundation/FinRL-Tutorials/blob/master/1-Introduction/Stock_NeurIPS2018_SB3.ipynb](https://github.com/AI4Finance-Foundation/FinRL-Tutorials/blob/master/1-Introduction/Stock_NeurIPS2018_SB3.ipynb) for Indian Market data with initially only a limited number of stocks but I am stuck at the part where technical indicators are added to the daily price data.

I'm getting the error as:
KeyError: "None of [Index(['tic', 'date', 'macd'], dtype='object')] are in the [columns]"

I noticed a couple of more issues here from other users saying the same thing, but those were not helpful either.

**Expected behavior**
Technical indicators should have been added just like it happened for dow30 tickers

**Screenshots**
![Screenshot 2024-02-29 054711](https://github.com/AI4Finance-Foundation/FinRL/assets/125493990/f06cea19-3f30-4aa5-b5d0-cae0af153509)

**Comment by zhumingpassional** [comment]
have you connected Indian stocks correctly?

**Comment by avipul751** [comment]
> I guess Indian Stock market is not supported. I have gone through architecture and studying from few weeks if you can provide some pointers for changes required. Yahoo provides data for NSE indian stock exchange for example TCS.NS. While processing below comand existing
> 
> df_summary = ensemble_agent.run_ensemble_strategy(A2C_model_kwargs, PPO_model_kwargs, DDPG_model_kwargs, timesteps_dict)

I have not yet ran the ensemble strategy, I'll do it in a day or 2 and will let you know if it works for me.

**Comment by avipul751** [comment]
> I guess Indian Stock market is not supported. I have gone through architecture and studying from few weeks if you can provide some pointers for changes required. Yahoo provides data for NSE indian stock exchange for example TCS.NS. While processing below comand existing
> 
> df_summary = ensemble_agent.run_ensemble_strategy(A2C_model_kwargs, PPO_model_kwargs, DDPG_model_kwargs, timesteps_dict)

I was able to run the ensemble strategy notebook without any issues, just that the agent took around 3.5 hrs to train. If you could share the errors you're getting then maybe I could help.

**Comment by xprabhudayal** [comment]
indian stocks can be trained but you cant be able to trade ig with paper trading on alpaca platform
