### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by qwzhuanghkclr** [AI4Finance-Foundation/FinRL#1183]
**Describe the bug**

**To Reproduce**
1. Go to '...': FinRL_PaperTrading_Demo.ipynb
2. Click on '....': Import related modules
4. See error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 from finrl.config_tickers import DOW_30_TICKER
      2 from finrl.config import INDICATORS
      3 from finrl.meta.env_stock_trading.env_stocktrading_np import StockTradingEnv

File E:\qw_e\FinRL\finrl\__init__.py:4
      1 from __future__ import annotations
      3 from finrl.test import test
----> 4 from finrl.trade import trade
      5 from finrl.train import train

File E:\qw_e\FinRL\finrl\trade.py:3
      1 from __future__ import annotations
----> 3 from finrl.meta.env_stock_trading.env_stock_papertrading import AlpacaPaperTrading
      4 from finrl.test import test
      7 def trade(
      8     start_date,
      9     end_date,
   (...)
     22     **kwargs,
     23 ):

File E:\qw_e\FinRL\finrl\meta\env_stock_trading\env_stock_papertrading.py:13
     10 import pandas as pd
     11 import torch
---> 13 from finrl.meta.data_processors.processor_alpaca import AlpacaProcessor
     16 class AlpacaPaperTrading:
     17     def __init__(
     18         self,
     19         ticker_list,
   (...)
     34     ):
     35         # load agent

File E:\qw_e\FinRL\finrl\meta\data_processors\processor_alpaca.py:11
      9 import pandas as pd
     10 import pytz
---> 11 from stockstats import StockDataFrame as Sdf
     14 class AlpacaProcessor:
     15     def __init__(self, API_KEY=None, API_SECRET=None, API_BASE_URL=None, api=None):

File ~\AppData\Local\anaconda3\envs\fin\lib\site-packages\stockstats.py:94
     43     pass
     46 _dft_windows = {
     47     # sort alphabetically
     48     'ao': (5, 34),
   (...)
     90     'vwma': 14,
     91 }
---> 94 def set_dft_window(name: str, windows: Union[int, tuple[int, ...]]):
     95     ret = _dft_windows.get(name)
     96     _dft_windows[name] = windows

TypeError: 'type' object is not subscriptable

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] :win11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by STerOTto** [comment]
try pip install stockstats==0.4.0
