### ISSUE TITLE
YahooDownloader

### ISSUE THREAD

**Issue by Veronicacs95** [AI4Finance-Foundation/FinRL#1286]
**Describe the bug**
YahooDownloader function used to work perfectly to download a list, however today it is not working anymore.

**To Reproduce**
dax = [
    'SIE.DE',
    'BAYN.DE',
    'RWE.DE',
    'ZAL.DE',
    'HNR1.DE',
    'ALV.DE',
    'IFX.DE',
    'FRE.DE',
    'DBK.DE',
    'EOAN.DE',
    'DTE.DE',
    'CON.DE',
    'AIR.DE',
    'BEI.DE',
    'VNA.DE',
    'BAS.DE',
    'SHL.DE',
    'HEI.DE',
    'DB1.DE',
    'BMW.DE',
    'DTG.DE',
    '1COV.DE',
    'VOW3.DE',
    'MTX.DE',
    'ADS.DE',
    'SY1.DE',
    'P911.DE',
    'DHL.DE',
    'MRK.DE',
    'ENR.DE'
]

# Select start day data scraping ( future 5 years back)
TRAIN_START_DATE = '2019-03-08'
TRAIN_END_DATE = '2023-09-08'
TRADE_START_DATE = '2023-09-08'
TRADE_END_DATE = '2024-03-08'

df_raw = YahooDownloader(start_date = TRAIN_START_DATE,
                     end_date = TRADE_END_DATE,
                     ticker_list = dax).fetch_data()

**Expected behavior**
a dataframe with stock list- dax OHLCV
![image](https://github.com/user-attachments/assets/8cd15b57-5c55-41bb-ac1f-7da24fe24b7a)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOs 15.0 (24A335)
 - Browser safari Version 18.0 (20619.1.26.31.6)

**Comment by kamathhrishi** [comment]
Same issue. Its broken for the tutorials too. 

Temporary hack:

```
TOP_BRL =["NVDA", "INTC", "AMD", "GOOGL", "MSFT", "AAPL", "AMZN", "BRK-B", "TSLA"]

# Initialize an empty list to store DataFrames
df_list = []

for ticker in TOP_BRL:
    # Fetch data for each ticker
    portfolio_raw_df = YahooDownloader(start_date='2011-01-01',
                                       end_date='2022-12-31',
                                       ticker_list=[ticker]).fetch_data()
    # Append the fetched DataFrame to the list
    df_list.append(portfolio_raw_df)

# Concatenate all DataFrames row-wise
portfolio_raw_df = pd.concat(df_list, axis=0, ignore_index=True)

# Display the concatenated DataFrame
print(portfolio_raw_df)
```

Maintainers, can I take a stab at fixing this issue?

**Comment by kleemc** [comment]
I just added a line below to the fetch_data() function in yahoodownloader.py and it works.  See screenshot below.  After adding that line, you'd have to re-import the package.

temp_df.columns = ['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']

![image](https://github.com/user-attachments/assets/dfa4b6de-8b28-41ce-b2d1-7b7dbe3b6bf5)

**Comment by kano5266** [comment]
Hi there! I noticed that the issue comes from the downloaded dataframe having multi-level column names, while it’s expecting just a single level. 

**Adding `temp_df.columns = temp_df.columns.droplevel(1)` between lines 53 and 54 of  `yahoodownloader.py` should fix it.** 

Hope this helps!

<img width="691" alt="Screenshot 2024-11-01 at 14 18 12" src="https://github.com/user-attachments/assets/14fd7c55-e361-4ba5-af99-354d36b0e733">

https://github.com/AI4Finance-Foundation/FinRL/blob/083b9dccba415a555e7de13c70a90e1e921f944c/finrl/meta/preprocessor/yahoodownloader.py#L53-L54

**Comment by zhumingpassional** [comment]
@kano5266 
Does it work now? 
if it works, could you pls submit a PR for it?
