### ISSUE TITLE
Library not compatible with Python 3.9

### ISSUE THREAD

**Issue by merlos** [AI4Finance-Foundation/FinRL#133]
I was trying to install the library  following the instructions of the section _Bare-metal installation (More difficult)_,  but when I ran `pip install -r requirements`. I got the following error
```
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

I have python 3.9.1 in my system and it turns out that  [Tensorflow currently supports 3.6 -> 3.8 ](https://www.tensorflow.org/install)

**Comment by rickpm** [comment]
For now change your python version to 3.8 or 3.6.
As soon TensorFlow will be compatible I will be a new challenge

**Comment by merlos** [comment]
I think it would be nice to have it documented on the readme.

**Comment by XiaoYangLiu-FinRL** [comment]
It is docmented in Readme and requirement file.
