### ISSUE TITLE
Prediction returning result for t-1 time step

### ISSUE THREAD

**Issue by Rajmehta123** [AI4Finance-Foundation/FinRL#143]
Hello. This is an amazing project. I followed the tutorial for Single Stock Trading and have few questions.

The length of `trade` is 537.
```
e_trade_gym = StockTradingEnv(df = trade, **env_kwargs)
df_account_value, df_actions = DRLAgent.DRL_prediction(model=trained_a2c, environment  = e_trade_gym)
```

1. The `df_account_value returns 537` value but `df_actions just returns 536` values. What about the last time step value?
2. How should I use to predict the action/step based on the current input? For eg: I have a data range from 1 week to the current date. How to print the action to be taken at the current time step?

**Comment by spencerR1992** [comment]
@BruceYanghy are you able to verify that the single stock env should have this behavior?
