### ISSUE TITLE
What is the StockPortfolioEnv in the initialization of the env?

### ISSUE THREAD

**Issue by Mostafasaeed29** [AI4Finance-Foundation/FinRL#144]
# Initialize env:
env_setup = EnvSetup(stock_dim = stock_dimension,
                        state_space = state_space,
                        initial_amount = 1000000,
                        tech_indicator_list = config.TECHNICAL_INDICATORS_LIST)
                        
env_train = env_setup.create_env_training(data = train,
                                          env_class = StockPortfolioEnv)

**Comment by XiaoYangLiu-FinRL** [comment]
It is imported from the env file. Could you please check there. Basically it is for a portfolio management task.
