### ISSUE TITLE
env_stocktrading.py crash

### ISSUE THREAD

**Issue by venellinus1** [AI4Finance-Foundation/FinRL#152]
Hello, seems after pull #150 env_stocktrading is crashing , using FinRL_multiple_stock_trading notebook

df_account_value, df_actions = DRLAgent.DRL_prediction(
    model=model_sac, 
    environment = e_trade_gym)

Traceback (most recent call last)
<ipython-input-39-3dbe4275e00b> in <module>()
      5 df_account_value, df_actions = DRLAgent.DRL_prediction(
      6     model=model_sac,
----> 7     environment = e_trade_gym)

/usr/local/lib/python3.6/dist-packages/finrl/env/env_stocktrading.py in save_action_memory(self)
    357             date_list = self.date_memory[:-1]
    358             df_date = pd.DataFrame(date_list)
--> 359             df_date.columns = ['date']
    360 
    361             action_list = self.actions_memory

**Comment by XiaoYangLiu-FinRL** [comment]
@spencerR1992 this issue related with #150   may need a check. Thx.
