### ISSUE TITLE
en_cash_penalty

### ISSUE THREAD

**Issue by Mostafasaeed29** [AI4Finance-Foundation/FinRL#156]
Why does the df_account_value.shape is not equal to the df.shape !!
I can't get where is the problem.

**Comment by XiaoYangLiu-FinRL** [comment]
@spencerR1992 hi, pls have a quick look at this issue. Thx.

**Comment by Mostafasaeed29** [comment]
![image](https://user-images.githubusercontent.com/62180031/109359820-cb834900-788e-11eb-92fa-6dcc605bd095.png)

**Comment by Mostafasaeed29** [comment]
![image](https://user-images.githubusercontent.com/62180031/109359848-d3db8400-788e-11eb-88ce-1654c353f968.png)

This is the weird part , the notebook is copy paste from notebooks folder of github.
