### ISSUE TITLE
cannot import name 'BackTestStats' from 'finrl.trade.backtest'

### ISSUE THREAD

**Issue by xanstorm** [AI4Finance-Foundation/FinRL#177]
I get this error now. Any suggestions?
![Screen Shot 2021-03-13 at 2 06 20 PM](https://user-images.githubusercontent.com/7649650/111041231-4dce4a00-8405-11eb-9c5f-45fb096d6137.jpg)

**Comment by BruceYanghy** [comment]
we renamed the backtesting functions please change to from finrl.trade.backtest import backtest_stats, backtest_plot, get_daily_return, get_baseline.

**Comment by xanstorm** [comment]
First. I am amazed at how you all conceived of the idea of RL, implemented
it, and coded it. I looked at the program: WOW. You guys and gals are
brilliant!
Second. Thank you for your reply! I am really grateful, and nothing
expresses gratitude like money. Do you have a donation button on your
website? If so, I did not find it and would appreciate it if you would send
a link.
Third. Are you available for hire/consulting gigs?
My regards to you and contributors for the excellent work.
Stephen

Stephen Hobbs, M.Sc., MBA
Skype: stephenmhobbs
Cell: 404-441-2858

**Comment by xanstorm** [comment]
Is there a way I could have found the change on my own w/out bothering you
and your team, of discovering this without submitting a help request?
I don't like bothering ppl and if I can learn what to do and what not to
do, it makes our lives better, faster, easier.
Stephen

Stephen Hobbs, M.Sc., MBA
Skype: stephenmhobbs
Cell: 404-441-2858

**Comment by XiaoYangLiu-FinRL** [comment]
Thx for your compliment!

Sorry for delayed reply.  Hope you enjoyed the codes.  If you have more suggestions (besides codes), you can speak in the slack channel.
