### ISSUE TITLE
got multiple values for argument error

### ISSUE THREAD

**Issue by xanstorm** [AI4Finance-Foundation/FinRL#181]
I copied/pasted the code for the single stock DRL and got to the point of Feature Engineer, where I got the error, " __init__() got multiple values for argument 'use_technical_indicator'. 
Anyone want to help? Thank you.

**Comment by venellinus1** [comment]
Hi, do you mean you are trying to run FinRL_single_stock_trading.ipynb?
Could you paste your FeatureEngineer cell code here- hopefully this can shed some light whats happening on your side

**Comment by xanstorm** [comment]
`# Perform Feature Engineering:
df = FeatureEngineer(df.copy(),
                      use_technical_indicator=True,
                      tech_indicator_list = config.TECHNICAL_INDICATORS_LIST,
                      use_turbulence=True,
                      user_defined_feature = False).preprocess_data()`
![Screen Shot 2021-03-21 at 3 20 04 PM](https://user-images.githubusercontent.com/7649650/111917941-ee051e00-8a58-11eb-9239-d9fd33db719f.jpg)
