### ISSUE TITLE
docker installation failed

### ISSUE THREAD

**Issue by simin75simin** [AI4Finance-Foundation/FinRL#185]
`./docker/bin/build_container.sh`
`ERROR: Command errored out with exit status 128: git clone -q https://github.com/quantopian/pyfolio /tmp/pip-install-jw_b9oxf/pyfolio_7d0a4b62624b47d7a4dd5b0c69c8fe2a Check the logs for full command output.
The command '/bin/sh -c pip install -r /tmp/requirements.txt' returned a non-zero code: 1`
os: ubuntu18.04, newest docker

**Comment by XiaoYangLiu-FinRL** [comment]
If you like, matpool.com provides docker version.

**Comment by XiaoYangLiu-FinRL** [comment]
We now provide detailed installation here：https://ai4finance.medium.com/finrl-for-quantitative-finance-install-and-setup-tutorial-for-beginners-1db80ad39159
