### ISSUE TITLE
Is price data stationarized before feeding it to the models?

### ISSUE THREAD

**Issue by umbertov** [AI4Finance-Foundation/FinRL#188]
Often, in literature it is mentioned that price data is not a stationary time series, so using it to train models might lead to various problems, since values in the sequence are not centered around a mean, and moreover future price data might not be in the same price range as for training data.

One could stationarize a time series in various ways, such as computing `(data - data.shift(-1)) / data.shift(-1)`, or the logarithmic returns, or even the difference between previous and current value. This ensures that data has a mean close to 0.

I've found this library very recently and am looking at the preprocessing code. If there is code to stationarize the data, i don't see it; is it a deliberate choice?

**Comment by XiaoYangLiu-FinRL** [comment]
It is a valid statement, and would be interesting to test, and we previous did tried it several times, e.g,. price ratio.  It is up to the users's choices.
