### ISSUE TITLE
Colab - ValueError: The parameter loc has invalid values

### ISSUE THREAD

**Issue by Marcus020** [AI4Finance-Foundation/FinRL#192]
Hey Guys,

Nice Library! I get an error running the default FinRL_ensemble_stock_trading_ICAIF_2020.ipynb file in colab.

When running this code in Part 6, it results in this error: 

![error](https://user-images.githubusercontent.com/19209947/112308209-2c414e00-8ca2-11eb-925f-735c99a2e383.jpg)

It seems to be related to the timesteps_dict argument. 

Only thing I changed in the file was updating this line when importing packages: 
from finrl.trade.backtest import backtest_stats, backtest_plot, get_daily_return, get_baseline

Any thoughts, I can't find the cause?

Mark

**Comment by Marc-lu** [comment]
Have you solve this problem? I meet the same error and have no idea about this

**Comment by SamCurtis111** [comment]
I had the same error and I believe it is because of missing data in the training set after transformation. I havent looked into it too closely whether there is actually missing data in the underlying data or if there are problems with the preprocessing component but if you adjust the training start date to 2015 for e.g. it will resolve the issue

**Comment by Marcus020** [comment]
Hey Sam,

Good catch, this indeed is causing the error. Updating: 

train_start = '2015-01-01'

fixed it. If I find more info about the underlying missing data, I will update.

Thanks a lot!

**Comment by XiaoYangLiu-FinRL** [comment]
Please check whether there is missing values in the data.

**Comment by EveL1u** [comment]
I tried the start date of 2013-01-01, and it runs as well.  2012-01-01 does not work.

**Comment by arleigh418** [comment]
Check data. I have the same problem before, and I found -inf in my data set.

**Comment by NeDa-Y** [comment]
I got the same error in validation date from 2019 and also I checked and there is not any missed value
