### ISSUE TITLE
Enhancement - Add short positions with perhaps margin tunable parameters

### ISSUE THREAD

**Issue by TheWCKD** [AI4Finance-Foundation/FinRL#196]
Hello!

First of all thank you for this amazing project! I would like to know if there is a possibility to integrate **_short positions_** in your algorithms with some _**margin tunable parameters**_ as you did with the transaction costs. As far as I saw and read, the current project supports only _**long positions.**_

I think this could be a great addition to the entire FinRL project, addition that could also greatly improve the models and perhaps the returns.

**Comment by XiaoYangLiu-FinRL** [comment]
I believe it is possible, following an inverse logic of long positions.

**Comment by KaiOnGitHub** [comment]
@TheWCKD I am currently evaluating to implement this as a Bachelor Thesis. I would be happy if someone experienced with margin trading / shorting could help me to understand how it should be implemented. I have little experience with trading and I think with margin trading there are quite a few things to consider.
