### ISSUE TITLE
Notebook not working

### ISSUE THREAD

**Issue by qingyuanxingsi** [AI4Finance-Foundation/FinRL#197]
Thanks for your work!

I find this file [freq_model](https://github.com/AI4Finance-LLC/FinRL-Library/blob/master/notebooks/FinRL_freq_model.ipynb) can not work properly, will you be so kind to fix it?

It seems that some scripts or imports are missing!

**Comment by sunnyswag** [comment]
It's seems that you need to provide some detials
for example, which line can not work well.
