### ISSUE TITLE
State Technical Indicators

### ISSUE THREAD

**Issue by SamCurtis111** [AI4Finance-Foundation/FinRL#202]
It appears that the state uses the sum of technical indicators as a component. Is this correct and if so why does it sum them rather than treat them individually?

`state =  [self.state[0]] + \
                      self.data.close.values.tolist() + \
                      list(self.state[(self.stock_dim+1):(self.stock_dim*2+1)]) + \
                      sum([self.data[tech].values.tolist() for tech in self.tech_indicator_list ], [])`

**Comment by XiaoYangLiu-FinRL** [comment]
The sum here is not a sum. Please have a check of the grammar.....
