### ISSUE TITLE
Preprocess FeatureEngineer class error

### ISSUE THREAD

**Issue by abdulrahman93** [AI4Finance-Foundation/FinRL#203]
Hello,

Sorry if it's a naive question, I tried to search that but couldn't find a useful info. I've a dataframe for a historical data where I'm trying to generate indicators using the FeatureEngineer class, previously it was working fine now it emits this error:
`"Length of values (369926) does not match length of index (369850)"
`
Though dataframe dimension is 369850 x 8 columns, the same steps were working fine previously. Below is the code where I call the function.

```
tech_indicator_list=config.TECHNICAL_INDICATORS_LIST
tech_indicator_list=tech_indicator_list+['open_2_sma','close_10.0_le_5_c','wr_10','dma','trix']

fe = FeatureEngineer(
                    use_technical_indicator=True,
                    tech_indicator_list = tech_indicator_list,
                    use_turbulence=False,
                    user_defined_feature = False)

processed = fe.preprocess_data(df)
```

Preview of the dataframe
![screen](https://user-images.githubusercontent.com/11236813/113388289-3e9c4580-938e-11eb-9a3f-da02d714d7d7.PNG)

**Comment by XiaoYangLiu-FinRL** [comment]
I believe it is fixed in the updated codes.
