### ISSUE TITLE
Could not broadcast input array from shape

### ISSUE THREAD

**Issue by phamanhtu17295** [AI4Finance-Foundation/FinRL#204]
I am trying to run your code in Colab
https://colab.research.google.com/drive/11pErFMRAWFbWs-P5iArJheFxF2Mh-F1v#scrollTo=IhizvNwcrg1n

where I stumble in the problem: 

![Screenshot from 2021-04-02 14-33-19](https://user-images.githubusercontent.com/74130487/113393120-64424280-93c0-11eb-93e6-ac490461772d.png)

I only used 10 stocks for my model? Is that the one causing the problem?
ValueError: could not broadcast input array from shape (10,2) into shape (18,10)

The data I used:
[vietnamdata.txt](https://github.com/AI4Finance-LLC/FinRL-Library/files/6248291/vietnamdata.txt)

**Comment by george-adams1** [comment]
Did this issue end up being resolved? I am trying to use non YF data and I am having the same issue. 
`ValueError: could not broadcast input array from shape (6341,) into shape (32997,)`

**Comment by Ujjawal-K-Panchal** [comment]
+1 @george-adams1, @ckive. Trying to use `finrl.config_tickers.SP_500_TICKER`. Just the basic data. Getting same error. Any solutions yet??

**Comment by george-adams1** [comment]
Yes, wasn't the issue I originally thought. Make sure your index is set the saw FinRL likes it. That solved my problem

**Comment by Ujjawal-K-Panchal** [comment]
Interesting. I'm sorry I donot get it. Can you give an example perhaps to explain `make sure your index is set`?
