### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by zywang624** [AI4Finance-Foundation/FinRL#214]
![image](https://user-images.githubusercontent.com/41494634/114137714-2e143e00-993f-11eb-9491-be704bcc9b12.png)

**Comment by NeDa-Y** [comment]
Same error, any suggestion?

**Comment by zhumingpassional** [comment]
Please print relevant variables. Does inf or nan exists?

**Comment by zhumingpassional** [comment]
Please print the variables. Is any number too large?
