### ISSUE TITLE
Why would end_total_assets ends with negtive value?

### ISSUE THREAD

**Issue by tenggyut** [AI4Finance-Foundation/FinRL#217]
in [FinRL_ensemble_stock_trading_ICAIF_2020](https://github.com/AI4Finance-LLC/FinRL/blob/master/FinRL_ensemble_stock_trading_ICAIF_2020.ipynb), I have noticed that the end_total_assets may result in negtive value, but the stock price and stock holding are always positive.  so why the negtive value end_total_assets

**Comment by geek2008** [comment]
the results are the same as yours, the end_total_assets may be positive or negative with the K lines fluctuating.

**Comment by zhumingpassional** [comment]
Could you print relevant variables? If inf or nan exist, there may exist error in calculating end_total_assets.
