### ISSUE TITLE
error in FinRL_ensemble_stock_trading_ICAIF_2020.ipynb 

### ISSUE THREAD

**Issue by Xiaoshu-Zhao** [AI4Finance-Foundation/FinRL#225]
I have some issues running this file when I define df_summary.

df_summary = ensemble_agent.run_ensemble_strategy(A2C_model_kwargs,
                                                 PPO_model_kwargs,
                                                 DDPG_model_kwargs,
                                                 timesteps_dict)

 I did not change anything in the original ipynb file. My error is:

"The parameter loc has invalid values"

**Comment by goyalrajni** [comment]
I'm experiencing the same issue.
