### ISSUE TITLE
Consistency of saved model and original model

### ISSUE THREAD

**Issue by yanbosteve** [AI4Finance-Foundation/FinRL#230]
I've set the random seeds. Training the same length gave me the same test results.
But if I save the model and load it again. The result is different from the original model.

**Comment by SteamedGit** [comment]
I've had similar issues running a saved PPO model on the same data multiple times. Completely different results each time, what could account for this?

**Comment by SteamedGit** [comment]
@BruceYanghy @XiaoYangLiu-FinRL

**Comment by zhumingpassional** [comment]
>I've set the random seeds. Training the same length gave me the same test results.
But if I save the model and load it again. The result is different from the original model.

> I've had similar issues running a saved PPO model on the same data multiple times. Completely different results each time, what could account for this?

Because PPO used the stochastic policy in the 'test' stage.
