### ISSUE TITLE
FinRL_portfolio_allocation_NeurIPS_2020.ipynb onIndia Stocks

### ISSUE THREAD

**Issue by Captaingreenbeard** [AI4Finance-Foundation/FinRL#237]
the code corks perfectly till this point.
![image](https://user-images.githubusercontent.com/68405220/121852734-871c9b80-cd0d-11eb-9aab-04886dcb7b4c.png)
![image](https://user-images.githubusercontent.com/68405220/121852802-9ef41f80-cd0d-11eb-8c09-ea4b09e93ab4.png)

ValueError: could not broadcast input array from shape (37,29) into shape (38,30)

gave these files as the input rather than config.DOW_30_TICKER

[nifty_top30_ticker_list_try_with_tic.zip](https://github.com/AI4Finance-LLC/FinRL/files/6646250/nifty_top30_ticker_list_try_with_tic.zip)

**Comment by XiaoYangLiu-FinRL** [comment]
You may check the state size, e.g., 10 stocks with 10 prices, 10 shares, 1 balance,  here leading to 21 dimensions.
