### ISSUE TITLE
How to load the trained model

### ISSUE THREAD

**Issue by wuhao55158** [AI4Finance-Foundation/FinRL#245]
1、How to load the trained model？
agent=DRLAgent(env=env_train)
model_a2c=agent.get_model("a2c")
model_a2c.load(r"E:\7.1\7.1\trained_models\squicksave_A2C_dow.model")
Loading the model requires the previous conditions。Is there  a better way to load the model directly？

2、Cannot display pictures in pycharm environment
backtest_plot(df_account_value,
             baseline_ticker = '^DJI',
             baseline_start = '2019-01-01',
             baseline_end = '2021-01-01')
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>

Thank you very much！

**Comment by leeshen64** [comment]
I have the same question, can we train the model and saved, later on just reloaded?, or there already answer to this question?

**Comment by Waterkin** [comment]
I have the same question, can we train the model and saved, later on just reloaded?, or there already answer to this question?

**Comment by absolutelyharsh** [comment]
Hi, Does anyone here know how can we make a prediction on new data after loading the model ?

**Comment by george-adams1** [comment]
Has anyone been able reload the model after training for testing? I save the model 

> trained_ddpg.save('trained_ddpg')

 but are unable to reload the model. In keras it is usually quite simple just, 

> from tensorflow import keras
model = keras.models.load_model('path/to/location')

Could anyone help with this?
