### ISSUE TITLE
please add a short position, and possibly a stop loss

### ISSUE THREAD

**Issue by o-evgeny** [AI4Finance-Foundation/FinRL#249]

**Comment by o-evgeny** [comment]
for ensemble stock trading environment

**Comment by XiaoYangLiu-FinRL** [comment]
Short is more challenging, we did not have good demo yet. Anyone would like to help out a little boy?

**Comment by george-adams1** [comment]
@XiaoYangLiu-FinRL Was a stop loss ever added?

**Comment by XiaoYangLiu-FinRL** [comment]
@george-adams1 you may find a stop_loss environment somewhere, in a previous version.  Recent cleaning may have deleted it.
