### ISSUE TITLE
Trade envs interface should be same?

### ISSUE THREAD

**Issue by ruifeng96150** [AI4Finance-Foundation/FinRL#250]
FinRL is a good project, but the envs inside is not.

I have some ideas for design Envs:

1.  Create a single trade env objects. thus other project same to use.
2.  All envs parameter should be same if then mean for one things. thus when make is easy to replace a new one. Have a basic env class is a choose.
3.  Reward design is a importance thing for RL learning. It's possible to have a reward options for a env? Such as reward end assets rate or  float gain for every step, only reward when have sell action and so on.
4. better to extend markets such as futures ,options, if have a basic env class

Just as some ideas for your reading.

**Comment by XiaoYangLiu-FinRL** [comment]
Would you like to have a look at a set of environments at NeoFinRL: https://github.com/AI4Finance-LLC/NeoFinRL/tree/main/neo_finrl
Be happy to hear your coments.
