### ISSUE TITLE
Fixed buy/sell cost option for Environment

### ISSUE THREAD

**Issue by svenhakvoort** [AI4Finance-Foundation/FinRL#261]
First of all, the docs are great and super helpful! However I do miss an option for the StockTradingEnv to include a fixed fee, I commonly trade on a platform where there is a fixed fee of 50 cents + 1 cent per stock bought, I get that that last part might complicated things but it would be hugely helpful if just a fixed value could be passed in!

Thank you in advance :)

**Comment by Athe-kunal** [comment]
Yes, you can. Follow this tutorial https://github.com/AI4Finance-LLC/FinRL/blob/master/tutorials/tutorial_multistock_variant_2.ipynb.
Here in the StocktradingEnv class, under the _sell_stock and _buy_stock method, we have sell and buy cost pct. Just change them according to your need, you will have a custom class from trading Environment
