### ISSUE TITLE
AI4Finance-LLC / FinRL on pycharm Run Test.py No module named 'finrl.config'

### ISSUE THREAD

**Issue by javaddduke** [AI4Finance-Foundation/FinRL#268]
ModuleNotFoundError: No module named 'finrl.config'

from finrl.config import config

Traceback (most recent call last):
  File "F:/Project/AI4FinRL/Lib/site-packages/finrl/neo_finrl/data_processors/processor_yahoofinance.py", line 7, in <module>
    from finrl.config import config
ModuleNotFoundError: No module named 'finrl.config'

**Comment by javaddduke** [comment]
Incorrect installation?

**Comment by Athe-kunal** [comment]
It is
from finrl.apps import config

**Comment by javaddduke** [comment]
> It is
> from finrl.apps import config

Can't import

from finrl.apps import config

pycharm Report an error

**Comment by javaddduke** [comment]
already added from finrl.apps import config

pycharm Report an error

**Comment by Athe-kunal** [comment]
The config file is in finrl.apps only, probably follow one of the tutorial and install properly

**Comment by XiaoYangLiu-FinRL** [comment]
Recently, we made changes in the file structure.  Per your request, we updated a new version to pypi.
Could you like to try again?

**Comment by hokhay** [comment]
Have you tried `Mark Directory as Sources Root` on the FinRL-Library?
