### ISSUE TITLE
how to ouput trading plan

### ISSUE THREAD

**Issue by a20180502** [AI4Finance-Foundation/FinRL#269]
I was wondering how I would have to define the environment to predict a future day. So lets say I would train with data up until today (18th  August  2021) and I want to see what the actions for the DOW_30 stocks should be for tomorrow. I can't seem to find any examples or a way to do this.
like this，
8.18 trading plan：
sell Xstock 200 shares at price 20.02-20.05
buy Ystock 100 shares at price 10.00-10.10

**Comment by Athe-kunal** [comment]
In the tutorials, you can save the trained models in config.TRAINED_MODELS folder. Probably you can retrieve the trained model and pass in the required state space to get the action for each asset.

**Comment by XiaoYangLiu-FinRL** [comment]
Since DRL algorithms perform an action after observing the environment (say prices), one possible way for your question would be: 1). using a prediction model to estimate tomorrow's prices, 2) then input it into the trained agent and get the actions for tomorrow.

**Comment by Anjanitnov** [comment]
Hi ! Interesting suggestions.  Has anyone developed the code for this ? Kindly let me know .Thanks

**Comment by chenliqiang1982** [comment]
@XiaoYangLiu-FinRL  Hello, I have the same question. I want to know whether actions is for today or tomorrow? If you already know the closing price, it's too late.

**Comment by XiaoYangLiu-FinRL** [comment]
@chenliqiang1982  We are providing demo codes here.  If you use the price that is one minute before "closing price", will that cause big trouble for you?  If yes, then please find some good way to address it.  Currently, I am relying the execution team to address possible "slipage".

**Comment by chenliqiang1982** [comment]
@XiaoYangLiu-FinRL  Thank you. I probably understand what you mean. I will test it.
