### ISSUE TITLE
It's my first time to use FinRL

### ISSUE THREAD

**Issue by 630362055** [AI4Finance-Foundation/FinRL#270]
Lots of content, how to get started, Is there an order to the tutorials?

**Comment by ggardiakos** [comment]
I've done everything up to training the data like the instructions say..what to do now and how is unclear. The instructions just stop. I feel so fortunate to have people share exciting projects like these but almost everyone on github needs to do a much better job with instructions. I've been in IT for 25 years and it's so frustrating. Please make instructions for dummies, and not engineers. A youtube video of the setup and use would probably be the best thing ever. Come on Engineers, it takes all kinds of people to make the world go around.

**Comment by 630362055** [comment]
> Don't make us feel like we are being lazy for asking for help, we do good things for the world too.

I finally went to see each tutorial of this project. Not only was there no order and description, but also the content was complicated and messy. Finally, I had to look at the source code. This project has done some work, but since it wants to be an excellent open source project, I think the documentation and instructions should be better. There are few gym env projects for trading, and most of them are difficult to read and use, and there is no explanation. I plan to write a better and easier-to-use environment by myself.

**Comment by ggardiakos** [comment]
If you have any good suggestions out there let me know. I'm enjoying gamestonkterminal but would love something that focuses on predictions.

**Comment by XiaoYangLiu-FinRL** [comment]
> I've done everything up to training the data like the instructions say..what to do now and how is unclear. The instructions just stop. I feel so fortunate to have people share exciting projects like these but almost everyone on github needs to do a much better job with instructions. I've been in IT for 25 years and it's so frustrating. Please make instructions for dummies, and not engineers. A youtube video of the setup and use would probably be the best thing ever. Come on Engineers in general, it takes all kinds of people to make the world go around. Don't make us feel like we are being lazy for asking for help, we do good things for the world too.

Noted. We are also trying out best to help out.  Could you please share more about where you found it not easy to follow? As you may have experienced, deep reinforcement learning is quite sophisticated and there is a steep learning curve.

**Comment by XiaoYangLiu-FinRL** [comment]
> > Don't make us feel like we are being lazy for asking for help, we do good things for the world too.
> 
> I finally went to see each tutorial of this project. Not only was there no order and description, but also the content was complicated and messy. Finally, I had to look at the source code. This project has done some work, but since it wants to be an excellent open source project, I think the documentation and instructions should be better. There are few gym env projects for trading, and most of them are difficult to read and use, and there is no explanation. I plan to write a better and easier-to-use environment by myself.

We are updating and polishing it on a weekly basis, now it is becoming better.  Would appreciate very much if you will share more detailed thoughts.  The community is growing, and it is very good that our members can contribute and make it easy to use for others.

**Comment by Athe-kunal** [comment]
Yeah, it may be overwhelming to get started in this library. You can go through this introductory blog https://athekunal.medium.com/a-hitchhikers-guide-to-finrl-a-deep-reinforcement-learning-framework-for-quantitative-finance-e624c508f763, where I cover different components in RL, directory structure, code along understanding and which tutorial to follow given your use case. Do suggest where I can make changes?
