### ISSUE TITLE
What does the day column in the portfolio allocation notebook stand for?

### ISSUE THREAD

**Issue by KhalilBelghouat** [AI4Finance-Foundation/FinRL#271]
I'm currently using your much needed library in order to use reinforcement learning for portfolio allocation of a dozen Moroccan stocks. So, I don't have the privilege of retrieving the data as easily using the `YahooDownloader` function. My question, or questions, now are: What does the day column stand for? and why is it 2 in all the rows? I tried retrieving the historical data of two U.S. stocks and I got unordered numbers between 0 and 4. How do I choose the values in the day column? Can anyone please answer my questions. I apologize for the long post and thanks in advance.

**Comment by XiaoYangLiu-FinRL** [comment]
I believe you may find useful codes snippet at the NeoFinRL repo, which aims to standardize the data processing procedure,  https://github.com/AI4Finance-LLC/NeoFinRL

**Comment by Athe-kunal** [comment]
There is something called a weekend effect in the stock market, https://www.investopedia.com/terms/w/weekendeffect.asp. So days can act as a categorical column for our state space. So it is standard 1 for Monday, 2 for Tue etc I guess.

**Comment by KhalilBelghouat** [comment]
Thank you @XiaoYangLiu-FinRL and @Athe-kunal for the help and engagement. Your answer @Athe-kunal is exactly what I needed. Thank you so much!
