### ISSUE TITLE
The logger not working with Cash penalty environment

### ISSUE THREAD

**Issue by Athe-kunal** [AI4Finance-Foundation/FinRL#272]
The logger for the Cash penalty is not working in the current version. The logger was supposed to log cash percentage, returns etc. but it is not working. Also, the error data from Stable baselines is not getting logged.
Probably the error is in env_stocktrading_cashpenalty where

from stable_baselines3.common import logger --> from stable_baselines3.common.logger import Logger as per stable baselines format.

Also, we would three sets of lines in the get_model function in the models.py folder for stable baselines 3.
`
tmp_path =  "tmp\{}_log".format(
            model_name)
        
logger = configure(tmp_path, ["csv","tensorboard"])
model.set_logger(logger)
`
Am I getting anything wrong, or is it fixed?

**Comment by AhmMontasser** [comment]
Hi, 
I think the logger is updated in stable_baselines3

from stable_baselines3.common import logger
to
from stable_baselines3.common import utils

then configure the logger using 
logger = utils.configure_logger(......)
and use the logger as normal

**Comment by Athe-kunal** [comment]
Yes, after updating stable_baseline3 it is working. A few more things to add
self.logger = utils.configure_logger('tensorboard_log','environment')
and convert all the logger to self.logger
