### ISSUE TITLE
pip install No module named 'finrl.neo_finrl.env_stock_trading'

### ISSUE THREAD

**Issue by jamestack** [AI4Finance-Foundation/FinRL#273]
step 1:
pip install git+https://github.com/AI4Finance-Foundation/FinRL.git

step 2:
$ cd /d/Anaconda3/envs/rl_stock/lib/site-packages/finrl/neo_finrl
$ ls -l
total 22K
-rw-r--r-- 1 admin None    2 Sep  3 16:40 __init__.py
drwxr-xr-x 1 admin None    0 Sep  3 16:40 __pycache__
-rw-r--r-- 1 admin None 8.1K Sep  3 16:40 config.py
-rw-r--r-- 1 admin None 2.7K Sep  3 16:40 data_processor.py
drwxr-xr-x 1 admin None    0 Sep  3 16:40 data_processors
-rw-r--r-- 1 admin None    2 Sep  3 16:40 env_builder.py
drwxr-xr-x 1 admin None    0 Sep  3 16:40 preprocessor

not found folder : env_stock_trading env_portfolio_allocation env_cryptocurrency_trading

**Comment by jamestack** [comment]
os win10
python 3.7.11

**Comment by arjunsinghyadav2** [comment]
Had the same issue, any ideas where did env_stock_trading got moved?

**Comment by Athe-kunal** [comment]
Yes, when I did pip install https://github.com/AI4Finance-LLC/FinRL-Library.git on Google colab, the package did not get registered in the dist-packages folder ('/usr/local/lib/python3.7/dist-packages'). I guess you can just do
 !git clone https://github.com/AI4Finance-LLC/FinRL-Library.git
And add it to your system path
import sys
sys.path.append("FinRL-Library")

**Comment by arjunsinghyadav2** [comment]
The above worked for me

**Comment by XiaoYangLiu-FinRL** [comment]
We did not update pip install yet, but the codes were updated.
