### ISSUE TITLE
Single stock prediction not working when using turbulence threshold 

### ISSUE THREAD

**Issue by arnishow** [AI4Finance-Foundation/FinRL#277]
Hi,

Stocks models, including ensemble method, don't work with single stock in StockTradingEnv.
It fails when running prediction **and using turbulence_threshold**:
`e_trade_gym = StockTradingEnv(df = trade, turbulence_threshold = 70, risk_indicator_col='vix', **env_kwargs)`
`df_account_value, df_actions = DRLAgent.DRL_prediction(
    model=trained_agent, 
    environment = e_trade_gym)`

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-51-593702fb0e98> in <module>()
      1 df_account_value, df_actions = DRLAgent.DRL_prediction(
      2     model=trained_agent,
----> 3     environment = e_trade_gym)

3 frames

/usr/local/lib/python3.7/dist-packages/finrl/neo_finrl/env_stock_trading/env_stocktrading.py in step(self, actions)
    250             self.data = self.df.loc[self.day,:]
    251             if self.turbulence_threshold is not None:
--> 252                 self.turbulence = self.data[self.risk_indicator_col].values[0]
    253             self.state =  self._update_state()
    254 

AttributeError: 'numpy.float64' object has no attribute 'values'

**Comment by Athe-kunal** [comment]
Yes, it is expecting a data frame and it is possible with more than one stock. Probably you can navigate to /usr/local/lib/python3.7/dist-packages/finrl/neo_finrl/env_stock_trading/env_stocktrading.py and substitute this
if self.turbulence_threshold is not None:  
                if len(self.df.tic.unique()) == 1:
                  self.turbulence = self.data[self.risk_indicator_col]
                elif len(self.df.tic.unique()) > 1:
                  self.turbulence = self.data[self.risk_indicator_col].values[0]
            self.state =  self._update_state()

**Comment by arnishow** [comment]
Thank you
