### ISSUE TITLE
File Not Found in Ensemble -account_value_trade_{}_{}.csv- 

### ISSUE THREAD

**Issue by NurbukeTeker** [AI4Finance-Foundation/FinRL#281]
In Ensemble Stock Traidng ICAIF2020 notebook, there is line that read data from csv:

---  temp = pd.read_csv('results/account_value_trade_{}_{}.csv'.format('ensemble',i))

 But there is no "results" folder or not created during the code. I looked the environment codes but there is no " write account value to csv" part.  So how can I reach to this results. Or where should I add "write csv " part in code?

**Comment by Athe-kunal** [comment]
Just make sure you have done this to create results directory
if not os.path.exists("./" + config.RESULTS_DIR):
    os.makedirs("./" + config.RESULTS_DIR)

And if nothing is getting written to the data frame, you can do write to csv here https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/neo_finrl/env_stock_trading/env_stocktrading.py#354... This is the account value dataframe
