### ISSUE TITLE
DDPG Crashes GPU Training

### ISSUE THREAD

**Issue by chuachengling** [AI4Finance-Foundation/FinRL#282]
Hello, when running the GPU training on the FinRL_portfolio_allocation_NeurIPS_2020.ipynb notebook, when using SPX500 index universe as the data from 1990-2021, there seems to be a crash from GPU training for DDPG. 

Here are the error logs:

tcmalloc: large alloc 5847400448 bytes == 0x5656154b0000 @ 0x7f44b1550001 0x7f44a89c454f 0x7f44a8a14b58 0x7f44a8a18b17 0x7f44a8ab7203 0x5653592300a4 0x56535922fda0 0x5653592a4868 0x56535929edcc 0x565359231fec 0x565359272bc9 0x56535926fac4 0x5653592321f1 0x5653592a1318 0x56535923165a 0x5653592a3f40 0x56535929edcc 0x56535923173a 0x56535929fd67 0x56535929edcc 0x565359231fec 0x565359272bc9 0x56535926fac4 0x5653592321f1 0x5653592a1318 0x56535929ec35 0x56535923173a 0x5653592a093b 0x56535929ec35 0x56535929e933 0x56535929cda0

Does anyone have any idea why it crashes? Thanks!

**Comment by rayrui312** [comment]
I guess it is because the memory of the GPU is not enough. You may try to use a smaller dataset.

**Comment by chuachengling** [comment]
@rayrui312 that sounds about right, I am also thinking of increasing the GPU memory and try running it again, will let you know what happens
