### ISSUE TITLE
About the MADDPG implement

### ISSUE THREAD

**Issue by zhengzetao** [AI4Finance-Foundation/FinRL#287]
Hi, the tutorial said that the implemented DRL algorithms including MADDPG, but in the file finrl/drl_agents/stablebaselines3/models.py, I can only find the five RL algorithms, they are A2C, DDPG, TD3, SAC, PPO. My question is how to test the performance (in FinRL_portfolio_allocation_NeurIPS_2020.ipynb)  using MADDPG.

**Comment by XiaoYangLiu-FinRL** [comment]
Thanks for your reminding. We will clean the codes and release it soon.
