### ISSUE TITLE
Cannot Run the SingleStock Tutorial !!!

### ISSUE THREAD

**Issue by absolutelyharsh** [AI4Finance-Foundation/FinRL#288]
Have been following the tutorial for single stock but this keeps giving errors over and over. Most of the functions are missing and hence error out. Also cannot find the google colab notebook for the single stock tutorial. And there does not exist a notebook for the same in the github repo.

**Comment by segatrade** [comment]
Same problem. There is commit:
Delete FinRL_single_stock_trading.ipynb
625045a7 Bruce Yang <hongyang.yang@columbia.edu> on 1/26/2021 at 6:47 PM

Seems article completely obsolete for current version

**Comment by XiaoYangLiu-FinRL** [comment]
Use other tutorials plz.
