### ISSUE TITLE
fundemental data

### ISSUE THREAD

**Issue by JOHNFFFEE** [AI4Finance-Foundation/FinRL#292]
Hi, 
I tried to validate the fundamental code on S&P 500 (^GSPC) only and not on all the 30 tickers
can you tell me where the # Import fundamental data came from? 
the csv is not relevant in this case
thanks

**Comment by XiaoYangLiu-FinRL** [comment]
Yes, it needs an account.  You can use free data. Check here: https://github.com/AI4Finance-Foundation/FinRL-Meta
