### ISSUE TITLE
Vix cuts last day

### ISSUE THREAD

**Issue by arnishow** [AI4Finance-Foundation/FinRL#293]
Hi,

For strange reason, yahoo finance does not return the last asked day for the VIX.
So preprocess_data returns with last day of data missing.
We probably should add one day to end_date :

`        df_vix = YahooDownloader(start_date = df.date.min(),
                                end_date = df.date.max(),
                                ticker_list = ["^VIX"]).fetch_data()`

**Comment by Athe-kunal** [comment]
It may be a weekend or an off day (the last day), I suppose
