### ISSUE TITLE
Intraday Cashpenalty/Stoploss training.

### ISSUE THREAD

**Issue by bongomanuk** [AI4Finance-Foundation/FinRL#294]
Hi guys,

I love this awesome project but I'm struggling to get it to work with intraday stock training sets. I am hitting the following error with caching and can't figure it out, I assume it's because I'm using datetime and not date so it's screwing the caching up. Any pointers are much appreciated. Thanks!

My single stock processed dataframe is of the form:

 | date | open | high | low | close | volume | average | barCount | tic | macd | rsi_30 | cci_30 | dx_30 | boll | boll_ub | boll_lb | turbulence | log_volume | change | daily_variance
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2021-01-01 00:00:00 | 704.99 | 705.00 | 704.58 | 704.71 | 134 | 704.889 | 74 | TSLA | 7.394569 | 62.146219 | 70.637092 | 8.675102 | 701.3865 | 716.933746 | 685.839254 | 0.006246 | 11.455626 | -0.000397 | 0.000596
2021-01-01 01:00:00 | 704.65 | 704.70 | 704.05 | 704.50 | 465 | 704.365 | 139 | TSLA | 6.881793 | 61.999634 | 65.323743 | 7.306197 | 701.8760 | 717.152270 | 686.599730 | 0.005461 | 12.699526 | -0.000213 | 0.000923
2021-01-04 10:00:00 | 709.00 | 726.75 | 709.00 | 726.75 | 815 | 721.375 | 423 | TSLA | 8.176549 | 69.805741 | 159.774757 | 40.588349 | 703.5560 | 721.878295 | 685.233705 | 11.471878 | 13.291771 | 0.024424 | 0.024424
2021-01-04 11:00:00 | 726.85 | 729.77 | 725.00 | 725.12 | 249 | 726.649 | 166 | TSLA | 8.967750 | 68.735677 | 181.446638 | 43.555530 | 705.0770 | 725.259924 | 684.894076 | 0.082599 | 12.103790 | -0.002386 | 0.006578
2021-01-04 12:00:00 | 725.60 | 728.00 | 725.00 | 726.14 | 156 | 726.208 | 90 | TSLA | 9.566808 | 69.042873 | 167.348900 | 43.555530 | 706.6430 | 728.282687 | 685.003313 | 0.009877 | 11.637599 | 0.000744 | 0.004131

`/home/finrl/neo_finrl/env_stock_trading/env_stocktrading_stoploss.py in __init__(self, df, buy_cost_pct, sell_cost_pct, date_col_name, hmax, discrete_actions, shares_increment, stoploss_penalty, profit_loss_ratio, turbulence_threshold, print_verbosity, initial_amount, daily_information_cols, cache_indicator_data, cash_penalty_proportion, random_start, patient, currency)
    112             print("caching data")
    113             self.cached_data = [
--> 114                 self.get_date_vector(i) for i, _ in enumerate(self.dates)
    115             ]
    116             print("data cached!")

/home/finrl/neo_finrl/env_stock_trading/env_stocktrading_stoploss.py in <listcomp>(.0)
    112             print("caching data")
    113             self.cached_data = [
--> 114                 self.get_date_vector(i) for i, _ in enumerate(self.dates)
    115             ]
    116             print("data cached!")

/home/finrl/neo_finrl/env_stock_trading/env_stocktrading_stoploss.py in get_date_vector(self, date, cols)
    165             for a in self.assets:
    166                 subset = trunc_df[trunc_df[self.stock_col] == a]
--> 167                 v += subset.loc[date, cols].tolist()
    168             assert len(v) == len(self.assets) * len(cols)
    169             return v

/opt/conda/lib/python3.6/site-packages/pandas/core/indexing.py in __getitem__(self, key)
    871                     # AttributeError for IntervalTree get_value
    872                     pass
--> 873             return self._getitem_tuple(key)
    874         else:
    875             # we by definition only have the 0th axis

/opt/conda/lib/python3.6/site-packages/pandas/core/indexing.py in _getitem_tuple(self, tup)
   1042     def _getitem_tuple(self, tup: Tuple):
   1043         try:
-> 1044             return self._getitem_lowerdim(tup)
   1045         except IndexingError:
   1046             pass

/opt/conda/lib/python3.6/site-packages/pandas/core/indexing.py in _getitem_lowerdim(self, tup)
    808                     return section
    809                 # This is an elided recursive call to iloc/loc
--> 810                 return getattr(section, self.name)[new_key]
    811 
    812         raise IndexingError("not applicable")

/opt/conda/lib/python3.6/site-packages/pandas/core/indexing.py in __getitem__(self, key)
    877 
    878             maybe_callable = com.apply_if_callable(key, self.obj)
--> 879             return self._getitem_axis(maybe_callable, axis=axis)
    880 
    881     def _is_scalar_access(self, key: Tuple):

/opt/conda/lib/python3.6/site-packages/pandas/core/indexing.py in _getitem_axis(self, key, axis)
   1097                     raise ValueError("Cannot index with multidimensional key")
   1098 
-> 1099                 return self._getitem_iterable(key, axis=axis)
   1100 
   1101             # nested tuple slicing

/opt/conda/lib/python3.6/site-packages/pandas/core/indexing.py in _getitem_iterable(self, key, axis)
   1035 
   1036         # A collection of keys
-> 1037         keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
   1038         return self.obj._reindex_with_indexers(
   1039             {axis: [keyarr, indexer]}, copy=True, allow_dups=True

/opt/conda/lib/python3.6/site-packages/pandas/core/indexing.py in _get_listlike_indexer(self, key, axis, raise_missing)
   1252             keyarr, indexer, new_indexer = ax._reindex_non_unique(keyarr)
   1253 
-> 1254         self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
   1255         return keyarr, indexer
   1256 

/opt/conda/lib/python3.6/site-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1314                 with option_context("display.max_seq_items", 10, "display.width", 80):
   1315                     raise KeyError(
-> 1316                         "Passing list-likes to .loc or [] with any missing labels "
   1317                         "is no longer supported. "
   1318                         f"The following labels were missing: {not_found}. "

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['day'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"`

**Comment by Athe-kunal** [comment]
Use the stock trading environment for cash penalty in this tutorial
https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/tutorial_this_works_1_18.ipynb. It works
