### ISSUE TITLE
Hyperparameters optimization

### ISSUE THREAD

**Issue by rrkotik** [AI4Finance-Foundation/FinRL#304]
Hi, guys! unfortunately couldn't reproduce hyperparameters optimization for "1_18_this_works.ipynb" tutorial. Can you please provide actual notebooks? thanks.

**Comment by Athe-kunal** [comment]
Does this tutorial https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/Hyperparamter_optimization_FinRL_in_Stable_baselines3.ipynb helps?

**Comment by Athe-kunal** [comment]
If possible please share your notebook on it, I did not test it on the particular tutorial that you are doing. But yeah the notebook will help me to debug.

**Comment by rrkotik** [comment]
Ok, there is two issues with it: 1) it is about ddpg and ppo is presented in "1_18_this_works.ipynb"; 2) there is no net arch parameters at all.

**Comment by Athe-kunal** [comment]
Jump over to this link https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/hyperparams_opt.py . Here you will find all the parameters that you can tune for RL algorithms, also for PPO. Here you will also find the net_arch hyperparameter also. Finally, return them to PPO_PARAMS

**Comment by rrkotik** [comment]
the thing is that i don't observe parameters that are presented in https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/tutorial_this_works_1_18.ipynb and what i wanted to see is reproduced architecture as in "tutorial_this_works_1_18.ipynb" and in the given link training parameters are also absent.

**Comment by Athe-kunal** [comment]
Sorry, I am unable to understand your concern. Can you please elucidate
