### ISSUE TITLE
Add multi-process in env_stocktrading 

### ISSUE THREAD

**Issue by hokhay** [AI4Finance-Foundation/FinRL#312]
Hi all, I am trying add multi-processing capability in `env_stocktrading`.  In the `env_stocktrading`, I add     
```
 def get_multiproc_env(self, n=10):
        def get_self():
            return deepcopy(self)

        e = SubprocVecEnv([get_self for _ in range(n)], start_method="fork")
        obs = e.reset()
        return e, obs
```
and I generate training enviroment in `train.py` with
`env_train, _ = e_train_gym.get_multiproc_env(n=2)`

The code can run smoothly but from the results, it looks like the processors are running the exact same dataset and act exactly the same, thus giving same reward. Please see results below:
```
Eval num_timesteps=1536, episode_reward=150.55 +/- 0.64
Episode length: 3166.00 +/- 0.00
---------------------------------
| eval/              |          |
|    mean_ep_length  | 3.17e+03 |
|    mean_reward     | 151      |
| time/              |          |
|    total timesteps | 1536     |
---------------------------------
New best mean reward!
Eval num_timesteps=3072, episode_reward=150.55 +/- 0.64
Episode length: 3166.00 +/- 0.00
---------------------------------
| eval/              |          |
|    mean_ep_length  | 3.17e+03 |
|    mean_reward     | 151      |
| time/              |          |
|    total timesteps | 3072     |
---------------------------------
```
I have tried the `env_stocktrading_cashpenalty `with the same configuration, the results are like two different processors doing two different actions. What is the reason for making this different and how it be solved?

Thanks a lot
Jason

**Comment by rayrui312** [comment]
I think it is probably because of the random seed setting. In `env_stocktrading`, we set a random seed when initializing the env. If you deep copy it, the random seeds of your sub environments are probably the same. You may try to set n different seeds for n sub environments and see if the problem is solved.

**Comment by hokhay** [comment]
Thanks for your reply, Ray.
