### ISSUE TITLE
FinRL_PaperTradingDemo - AttributeError: 'NoneType' object has no attribute 'item'

### ISSUE THREAD

**Issue by dhsusf** [AI4Finance-Foundation/FinRL#326]
Running the following:

train(start_date = '2021-01-04', 
      end_date = '2021-09-01',
      ticker_list = ticker_list, 
      data_source = 'alpaca',
      time_interval= '1D', 
      technical_indicator_list= TECHNICAL_INDICATORS_LIST,
      drl_lib='elegantrl', 
      env=env,
      model_name='ppo', 
      API_KEY = API_KEY, 
      API_SECRET = API_SECRET, 
      APCA_API_BASE_URL = APCA_API_BASE_URL,
      erl_params=ERL_PARAMS,
      cwd='./papertrading_erl',
      break_step=1e5)

and received: 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-39-767aeac5564b> in <module>
     13       erl_params=ERL_PARAMS,
     14       cwd='./papertrading_erl',
---> 15       break_step=1e5)

/Volumes/ExtremeSSD/FinRL/finrl/train.py in train(start_date, end_date, ticker_list, data_source, time_interval, technical_indicator_list, drl_lib, env, model_name, if_vix, **kwargs)
     52         model = agent.get_model(model_name, model_kwargs=erl_params)
     53         trained_model = agent.train_model(
---> 54             model=model, cwd=cwd, total_timesteps=break_step
     55         )
     56 

/Volumes/ExtremeSSD/FinRL/finrl/drl_agents/elegantrl/models.py in train_model(self, model, cwd, total_timesteps)
     72         model.cwd = cwd
     73         model.break_step = total_timesteps
---> 74         train_and_evaluate(model)
     75 
     76     @staticmethod

/Volumes/ExtremeSSD/opt/miniconda3/envs/finrl/lib/python3.6/site-packages/elegantrl/run.py in train_and_evaluate(***failed resolving arguments***)
    194             steps, r_exp = update_buffer(traj_list)
    195 
--> 196         logging_tuple = agent.update_net(buffer, batch_size, repeat_times, soft_update_tau)
    197         with torch.no_grad():
    198             temp = evaluator.evaluate_and_save(agent.act, steps, r_exp, logging_tuple)

/Volumes/ExtremeSSD/opt/miniconda3/envs/finrl/lib/python3.6/site-packages/elegantrl/agent.py in update_net(self, buffer, batch_size, repeat_times, soft_update_tau)
   1092 
   1093         a_std_log = getattr(self.act, 'a_std_log', torch.zeros(1)).mean()
-> 1094         return obj_critic.item(), obj_actor.item(), a_std_log.item()  # logging_tuple
   1095 
   1096     def get_reward_sum_raw(self, buf_len, buf_reward, buf_mask, buf_value) -> (torch.Tensor, torch.Tensor):

AttributeError: 'NoneType' object has no attribute 'item'

**Comment by dhsusf** [comment]
Yeah, I was trying to run it on just 1 ticker using daily data. Is there a better notebook file for that or a way to adjust this notebook?

**Comment by sriram7777** [comment]
I have the same problem even after increasing the target_step to like 50000 from 5000. Not sure whether thats the issue here.

**Comment by XelHaku** [comment]
How big is your period?

I've done 3 months with 30,000 target step
