### ISSUE TITLE
FinRL_PaperTradingDemo for Single Ticker

### ISSUE THREAD

**Issue by dhsusf** [AI4Finance-Foundation/FinRL#328]
Hi, does anyone know how to adjust the PaperTrading notebook so I can run it on a single ticker using daily data or if there is a better notebook file for that? I have less than 2 months of coding/python experience, so if anyone can explain at that level it would be appreciated.

**Comment by rayrui312** [comment]
You may set a ticker list for the single ticker case that only has one ticker, e.g., ["AAPL"]. For daily data, you may try to change the time interval.

**Comment by dhsusf** [comment]
I ran back again into the AttributeError: 'NoneType' object has no attribute 'item'

I'm a little lost on where I would change the args.target_step = and how to go about coming up with value.

**Comment by rayrui312** [comment]
We'll update the codes soon, setting target_step as one of the input parameters so that users can easily set it.

**Comment by rayrui312** [comment]
It's updated. You can set target_step by setting `ERL_PARAMS = {..., "target_step": x ,...}`

**Comment by dhsusf** [comment]
Thanks for the update, testing right now. Question, how does one see the episode step? Is that equivalent to the batch size or break_step?

**Comment by rayrui312** [comment]
In most of our envs, the episode step is roughly the number of rows (times) of the data. For your case, I think a target_step of 5000 or 10000 should work.

**Comment by dhsusf** [comment]
Ok got it. 

I'm not sure if I should make another thread for this, but it looks like that when I get to the Part 2: Train the agent and start the "train" it looks like it's actually redownloading the data from Alpaca rather than using the cleaned data done in the Step 3. Data Cleaning & Feature Engineering.

Also from the Data Cleaning, I see that it's actually trying to process 1m data; I set it to 1D. And it splits up tic, in this case AAPL, with one row tic=A, second row tic=L, 3rd row tic=A, 4th row tic=L, etc. So, it's also duplicating values for tic "A" and tic "L", as well as doing it on a 1m basis.

**Comment by rayrui312** [comment]
1. The training function now redownloads data for each run. We will add a save function and support loading saved data in the future. For now, if you don't want to redownload data each time, you may try to save and load the data by yourself. As long as the data can be successfully loaded into the environment, it should work. 

2. For the problem of data cleaning you mentioned, we will check it. For now, you may see the compare notebook for training, which uses daily data from Yahoo! Finance data.

**Comment by skhonsha** [comment]
Hi, I cant find this code:
https://colab.research.google.com/github/AI4Finance-LLC/FinRL-Library/blob/master/examples/old/DRL_single_stock_trading.ipynb

would please check it?
thanks.
