### ISSUE TITLE
New Commit breaks Notebook

### ISSUE THREAD

**Issue by timweissenfels** [AI4Finance-Foundation/FinRL#329]
The newest commit that introduces target_step and eval_gap breaks the NeoFinRL Notebook.
https://github.com/AI4Finance-Foundation/NeoFinRL/blob/main/NeoFinRL_Plug_and_Play_with_DRL_Libraries.ipynb

How am i supposed to change it ?

`ERL_PARAMS = {"learning_rate": 3e-5,"batch_size": 2048,"gamma":  0.985, "seed":312, "net_dimension":512, "target_step":24, "eval_gap":0.05 } `

Also results in an error ->     AttributeError: 'NoneType' object has no attribute 'item'

**Comment by rayrui312** [comment]
Use larger target_steps like 5000 or 10000. eval_gap is the time (measured in seconds) gap of each evaluation. 0.5 is too small. 30, 60 may be fine.

**Comment by rayrui312** [comment]
The notebook is updated.

**Comment by timweissenfels** [comment]
LGTM thx
