### ISSUE TITLE
Data cleaning error

### ISSUE THREAD

**Issue by Nekhaenko** [AI4Finance-Foundation/FinRL#331]
![Снимок экрана от 2021-11-06 12-06-47](https://user-images.githubusercontent.com/34835972/140604387-8a92491d-5f5f-422d-b539-2599d5e97bc1.png)

**Comment by rayrui312** [comment]
We'll look into it. Could you tell us which notebook you are using?

**Comment by Nekhaenko** [comment]
> We'll look into it. Could you tell us which notebook you are using?

https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_PaperTrading_Demo.ipynb

**Comment by rayrui312** [comment]
I tested the notebook and didn't reproduce this error. Could you offer the specific codes?
