### ISSUE TITLE
about yahoofinance

### ISSUE THREAD

**Issue by scitao** [AI4Finance-Foundation/FinRL#335]
"As of November 1st, 2021 Yahoo services will no longer be accessible from mainland China. Yahoo products and services remain unaffected in all other global locations. We thank you for your support and readership."

So all examples in this project cannot run at all in mainland China.

Then how will we do?

**Comment by Athe-kunal** [comment]
I guess you can use other services like WrdsProcessor mentioned here https://github.com/AI4Finance-Foundation/FinRL/tree/master/finrl/neo_finrl/data_processors

https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_Compare_ElegantRL_RLlib_Stablebaseline3.ipynb
In the above example, you can specify a data source other than yahoo finance to download data.

**Comment by scitao** [comment]
> I guess you can use other services like WrdsProcessor mentioned here https://github.com/AI4Finance-Foundation/FinRL/tree/master/finrl/neo_finrl/data_processors
> 
> https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_Compare_ElegantRL_RLlib_Stablebaseline3.ipynb In the above example, you can specify a data source other than yahoo finance to download data.

This database need password and can register by person in some universities

**Comment by rayrui312** [comment]
You can try to use data from Alpaca.  The account of Alpaca can be quickly registered, and the basic APIs are free to access.

**Comment by XiaoYangLiu-FinRL** [comment]
There are lots of choices here: https://github.com/AI4Finance-Foundation/FinRL-Meta/tree/main/finrl_meta/data_processors  and will be more.
