### ISSUE TITLE
Why does a higher hmax cause the error? Has this something to do with hardware requirements? @rayrui312

### ISSUE THREAD

**Issue by timweissenfels** [AI4Finance-Foundation/FinRL#336]
Why does a higher hmax cause the error? Has this something to do with hardware requirements? @rayrui312

_Originally posted by @timweissenfels in https://github.com/AI4Finance-Foundation/FinRL/issues/167#issuecomment-963383034_

**Comment by Athe-kunal** [comment]
Probably you are running out of cash with higher h_max. H_max specifies the maximum number of shares you can buy or sell. Probably there is a cash shortage

**Comment by timweissenfels** [comment]
![image](https://user-images.githubusercontent.com/32968964/140792363-a22cfb25-c117-42ff-a29c-0a7074de0611.png)
![image](https://user-images.githubusercontent.com/32968964/140792559-10fbcd48-89b8-4184-ad91-7aa8e0ae5f5f.png)
![image](https://user-images.githubusercontent.com/32968964/140792810-d409b392-4ff1-413e-9fb2-83be39f148a6.png)

The closer hmax gets to 1, the more dates it includes

**Comment by timweissenfels** [comment]
So you mean it just dies without enough cash?

**Comment by Athe-kunal** [comment]
Yeah I suppose
You have set patient flag to true, so it is waiting for more cash. I am not sure how to do it after that.

**Comment by timweissenfels** [comment]
I have no cash penalty, thats why i am kinda confused

**Comment by Athe-kunal** [comment]
StockEnvV2 has a default cash penalty

**Comment by timweissenfels** [comment]
![image](https://user-images.githubusercontent.com/32968964/140794736-27e5b12e-384f-4952-ab68-3d3db48913ce.png)
Yeah you are completly right, missed the if statement, soory

**Comment by timweissenfels** [comment]
Setting the out_of_cash_penalty to 0, didn't really do anything but setting higher cash amount solved it.
The problem is i manually have to find the right hmax and initial_cash ?
Shouldn't the model be able to see how much money i got left and stop buying?

**Comment by Athe-kunal** [comment]
Maybe turning off the patient flag can help

**Comment by timweissenfels** [comment]
And by "having the same cash shortage problem" i mean they need a lower hmax or higher initial_cash to work

**Comment by Athe-kunal** [comment]
If you have many stocks in your portfolio, then having a higher h_max can lead to cash shortage. So generally try to have a smaller one for multi-stock portfolio. Else, you can use other environments

**Comment by timweissenfels** [comment]
Okay i understand that thx, but why does it differ between ppo and a2c,ddpg?

**Comment by Athe-kunal** [comment]
These are stochastic processes actually. I guess you can't reason why the difference. I would suggest you to try other environments in neo finrl

**Comment by timweissenfels** [comment]
Okay thank you so much!
