### ISSUE TITLE
how can I see these tables in my outputs on multiple_stock_trading?

### ISSUE THREAD

**Issue by skhonsha** [AI4Finance-Foundation/FinRL#337]
![trades](https://user-images.githubusercontent.com/40491703/140802177-da22bed7-0aba-460b-80c5-32881b7b9870.png)

**Comment by rayrui312** [comment]
For now, you may need to add codes in the environment by yourself to save these data and output these tables. We will add automated logs/recordings in the future.

**Comment by skhonsha** [comment]
thanks so much
