### ISSUE TITLE
Unable to replicate FinRL_Explainable_DRL_for_Portfolio_Management_An_Empirical_Approach.ipynb

### ISSUE THREAD

**Issue by chuachengling** [AI4Finance-Foundation/FinRL#341]
I am referring to the note book ```FinRL_Explainable_DRL_for_Portfolio_Management_An_Empirical_Approach.ipynb```

In the part of the integrated gradient of the paper, it shows the error message:

```RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x957 and 1073x64)```

I am using a different train and trade period for the models, and DJI Universe
Train: 2010-01-01 - 2020-12-31
Trade: 2021-01-01 - 2021-08-31

Any help would be greatly appreciated, thanks!

**Comment by 16GMCN** [comment]
This issue is now solved by redefining the technical_indicator_list.

**Comment by chuachengling** [comment]
@16GMCN 

I see, any reason why the author chose to use the technical indicators ```['macd','rsi_30','cci_30','dx_30']``` instead of the usual values?

**Comment by 16GMCN** [comment]
There's no specific reason. Indicators could be different from macd, rsi, cci, dx.
