### ISSUE TITLE
actions on ElegantRL

### ISSUE THREAD

**Issue by wezzyzzs** [AI4Finance-Foundation/FinRL#346]
Hello, I'm a beginner of RL.
I wonder that if we can see the actions with the ElegantRL's DRL_prediction function ?
(Return actions in [-1,0 1], just like the sb3's DRL_prediction function).
It will be helpful if someone share their idea, thanks!

Besides, I wonder that is it suitable to trade index (like DJI) as single stock with the env in plug_and_play_DRL notebook ?

**Comment by rayrui312** [comment]
See [FinRL-Meta issue15](https://github.com/AI4Finance-Foundation/FinRL-Meta/issues/15).
