### ISSUE TITLE
ImportError: cannot import name 'AgentA2C' from 'elegantrl.agent' 

### ISSUE THREAD

**Issue by t-b-r** [AI4Finance-Foundation/FinRL#347]
I am referring to the notebook `FinRL_PaperTrading_Demo.ipynb`, running on Ubuntu installed on Windows 11.

When running the following:
```
from finrl.train import train
from finrl.test import test
from finrl.apps.config import DOW_30_TICKER
from finrl.apps.config import TECHNICAL_INDICATORS_LIST
from finrl.neo_finrl.env_stock_trading.env_stocktrading_np import StockTradingEnv
from finrl.neo_finrl.env_stock_trading.env_stock_papertrading import AlpacaPaperTrading
from finrl.neo_finrl.data_processor import DataProcessor
from finrl.plot import backtest_stats, backtest_plot, get_daily_return, get_baseline

import numpy as np
import pandas as pd
```

I get the following error:

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-44bcb75bf543> in <module>
----> 1 from finrl.train import train
      2 from finrl.test import test
      3 from finrl.apps.config import DOW_30_TICKER
      4 from finrl.apps.config import TECHNICAL_INDICATORS_LIST
      5 from finrl.neo_finrl.env_stock_trading.env_stocktrading_np import StockTradingEnv

~/code/finrl/finrl/train.py in <module>
      1 import ray
----> 2 from finrl.drl_agents.elegantrl.models import DRLAgent as DRLAgent_erl
      3 from finrl.drl_agents.rllib.models import DRLAgent as DRLAgent_rllib
      4 from finrl.drl_agents.stablebaselines3.models import DRLAgent as DRLAgent_sb3
      5 from finrl.neo_finrl.data_processor import DataProcessor

~/code/finrl/finrl/drl_agents/elegantrl/models.py in <module>
      1 # RL models from elegantrl
      2 import torch
----> 3 from elegantrl.agent import AgentDDPG, AgentPPO, AgentSAC, AgentTD3, AgentA2C
      4 from elegantrl.run import Arguments, train_and_evaluate
      5 

ImportError: cannot import name 'AgentA2C' from 'elegantrl.agent' (/root/programs/miniconda3/lib/python3.7/site-packages/elegantrl/agent.py)
```

Any help would be appreciated.

**Comment by rayrui312** [comment]
Have you installed the newest version of ElegantRL? I have tested `FinRL_PaperTrading_Demo.ipynb` on Colab and didn't reproduce the error. You may try to install the newest version of ElegantRL and see if this issue is fixed.

**Comment by motnellig** [comment]
I am also having a problem with 
from elegantrl.run import * not loading

How do I load the new version into colab?

**Comment by rayrui312** [comment]
> I am also having a problem with from elegantrl.run import * not loading
> 
> How do I load the new version into colab?

Which notebook are you using? We have updated the codes to be compatible with the newest version of ElegantRL in FinRL. But some notebooks may not be updated yet.

**Comment by motnellig** [comment]
FinRL_PaperTrading_Demo.ipynb 
from rayrui312 Update notebook Latest commit 2ce2794 15 days ago 
at https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_PaperTrading_Demo.ipynb

**Comment by motnellig** [comment]
FinRL_PaperTrading_Demo.ipynb
from rayrui312 Update notebook Latest commit 2ce2794
<https://github.com/AI4Finance-Foundation/FinRL/commit/2ce2794e48ffdd93ee3745789cb1a05f2e5f97fb>
15
days ago
at
https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_PaperTrading_Demo.ipynb

Tom


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
11/22/21,
09:56:36 AM
