### ISSUE TITLE
FinRL_Ensemble_StockTrading_ICAIF_2020.ipynb vs ICAIF 2020 paper

### ISSUE THREAD

**Issue by fintech-ml** [AI4Finance-Foundation/FinRL#349]
Hi,
thank you very much for sharing this great project. Veyr impressive work!

I have a question: It seems the portfolio results in the jupyter notebook 

https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_Ensemble_StockTrading_ICAIF_2020.ipynb

are quite a bit worse than the results shown on 

https://towardsdatascience.com/deep-reinforcement-learning-for-automated-stock-trading-f1dad0126a02

as well as in the ICAIF 2020 paper (https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3690996).

Why is that? Is that a different version and if so in which respect? 

Thank you very much!!

**Comment by Burntt** [comment]
The answer to your question can have numerous answers.

A few examples:
- Hyperparameter optimization method
- Which data was trained upon
- Which data was tested upon
- Which out-of-sample data was used
- Model settings
....
- Market conditions

The code given in the notebook is not the identical version of the code corresponding to the paper. The notebooks are just a part of a complete application.

**Comment by Anurag-Maverick** [comment]
This notebook seems to have been removed: 
https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_Ensemble_StockTrading_ICAIF_2020.ipynb
Is this available somewhere else?

**Comment by XiaoYangLiu-FinRL** [comment]
Please check this folder: https://github.com/AI4Finance-Foundation/FinRL/tree/master/tutorials
Thanks.

**Comment by MaximCamilleri** [comment]
It appears that this link has also been deprecated:
https://github.com/AI4Finance-Foundation/FinRL/tree/master/tutorials
Is there a new place i can find it?
