### ISSUE TITLE
Switching off turbulence/vix

### ISSUE THREAD

**Issue by Abaminog** [AI4Finance-Foundation/FinRL#350]
Hello. If I want to run the models ignoring VIX/turbulence, how do I do that? Just switching to False in a call to FeatureEngineer doesn't help as it causes errors. It would be helpful to have this flexibility for a more objective comparison of this RL algorithm with other trading models. Thanks.

**Comment by rayrui312** [comment]
Thanks for your suggestion. For now, we don't support ignoring VIX/turbulence. You may set a high threshold to make it invalid. We will support it in the future.

**Comment by GXY2017** [comment]
I just learned this library.  You can skip FeatureEngineer() and prepare your own indicators or other observation data without VIX/turbulence index.  This is simple enough to do it yourself.  Just remember to sort the date and time like this.
````
processed_full.sort_values(['date','tic'])
````

**Comment by Abaminog** [comment]
> I just learned this library. You can skip FeatureEngineer() and prepare your own indicators or other observation data without VIX/turbulence index. This is simple enough to do it yourself. Just remember to sort the date and time like this.
> 
> ```
> processed_full.sort_values(['date','tic'])
> ```

Thanks. You are right -- it is possible to skip FeatureEngineer and prepare your own indicators. But then the risk indicator column is used in the StockTradingEnv object. I am not sure if that column can be just set to zero or some other dummy number.
