### ISSUE TITLE
Error: when running FinRL_StockTrading_Fundamental.ipynb

### ISSUE THREAD

**Issue by edwardhamilton** [AI4Finance-Foundation/FinRL#351]
trained_a2c = agent.train_model(model=model_a2c, 
                             tb_log_name='a2c',
                             total_timesteps=100000)

Logging to tensorboard_log/a2c/a2c_3
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_37/2087801270.py in <module>
      1 trained_a2c = agent.train_model(model=model_a2c, 
      2                              tb_log_name='a2c',
----> 3                              total_timesteps=100000)

/opt/conda/lib/python3.7/site-packages/finrl/drl_agents/stablebaselines3/models.py in train_model(self, model, tb_log_name, total_timesteps)
    102             total_timesteps=total_timesteps,
    103             tb_log_name=tb_log_name,
--> 104             callback=TensorboardCallback(),
    105         )
    106         return model

/opt/conda/lib/python3.7/site-packages/stable_baselines3/a2c/a2c.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    199             tb_log_name=tb_log_name,
    200             eval_log_path=eval_log_path,
--> 201             reset_num_timesteps=reset_num_timesteps,
    202         )

/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    235         while self.num_timesteps < total_timesteps:
    236 
--> 237             continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
    238 
    239             if continue_training is False:

/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py in collect_rollouts(self, env, callback, rollout_buffer, n_rollout_steps)
    167                 # Convert to pytorch tensor or to TensorDict
    168                 obs_tensor = obs_as_tensor(self._last_obs, self.device)
--> 169                 actions, values, log_probs = self.policy.forward(obs_tensor)
    170             actions = actions.cpu().numpy()
    171 

/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/policies.py in forward(self, obs, deterministic)
    588         # Evaluate the values for the given observations
    589         values = self.value_net(latent_vf)
--> 590         distribution = self._get_action_dist_from_latent(latent_pi)
    591         actions = distribution.get_actions(deterministic=deterministic)
    592         log_prob = distribution.log_prob(actions)

/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/policies.py in _get_action_dist_from_latent(self, latent_pi)
    603 
    604         if isinstance(self.action_dist, DiagGaussianDistribution):
--> 605             return self.action_dist.proba_distribution(mean_actions, self.log_std)
    606         elif isinstance(self.action_dist, CategoricalDistribution):
    607             # Here mean_actions are the logits before the softmax

/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/distributions.py in proba_distribution(self, mean_actions, log_std)
    150         """
    151         action_std = th.ones_like(mean_actions) * log_std.exp()
--> 152         self.distribution = Normal(mean_actions, action_std)
    153         return self
    154 

/opt/conda/lib/python3.7/site-packages/torch/distributions/normal.py in __init__(self, loc, scale, validate_args)
     48         else:
     49             batch_shape = self.loc.size()
---> 50         super(Normal, self).__init__(batch_shape, validate_args=validate_args)
     51 
     52     def expand(self, batch_shape, _instance=None):

/opt/conda/lib/python3.7/site-packages/torch/distributions/distribution.py in __init__(self, batch_shape, event_shape, validate_args)
     51                     continue  # skip checking lazily-constructed args
     52                 if not constraint.check(getattr(self, param)).all():
---> 53                     raise ValueError("The parameter {} has invalid values".format(param))
     54         super(Distribution, self).__init__()
     55 

ValueError: The parameter loc has invalid values
add Codeadd Markdown

**Comment by rayrui312** [comment]
Thanks for reporting it. We have confirmed this error. We are debugging now.
