### ISSUE TITLE
No module named 'elegantrl.agent' when running FinRL/FinRL_PaperTrading_Demo.ipynb

### ISSUE THREAD

**Issue by tensorboy** [AI4Finance-Foundation/FinRL#352]
It is called 'elegantrl.agents' in the new repository: https://github.com/AI4Finance-Foundation/ElegantRL/tree/master/elegantrl/agents The code need to be updated in https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/drl_agents/elegantrl/models.py#L3

**Comment by rayrui312** [comment]
Thanks for reporting it. ElegantRL has reorganized its codes. We are updating our codes now.

**Comment by rasphoran** [comment]
I'm getting ModuleNotFoundError: No module named 'elegantrl.agents' now.

**Comment by richardhuo** [comment]
I am getting this erro too. No module named 'elegantrl.agents' now.

**Comment by rasphoran** [comment]
Fixed the issue. Just had to install the required repositories by hand. I was following an example Jupiter notebook and turns out the install links they give do not correctly install it.
