### ISSUE TITLE
How can we treat NAN values?

### ISSUE THREAD

**Issue by skhonsha** [AI4Finance-Foundation/FinRL#353]
Apart from deleting stocks with empty value, what can we do in the cleaning phase?

preprocessors.py
`merged_closes = merged_closes.dropna(axis=1)`

my df with 30 stocks after this line has 0 columns!!!

**Comment by rayrui312** [comment]
We also adopt an improved forward filling method for NaN values. For missing rows, we fill the open, high, low, close prices with the previous valid close price and fill the volume with 0. For specific codes, you may see `finrl/neo_finrl/data_processors/processor_alpaca.py`

**Comment by skhonsha** [comment]
@rayrui312 thanks, Do you have any link? In my dataset, some stocks were closed on certain dates due to non-initial public offering or closed sessions. Does it affect algorithms?

**Comment by zhumingpassional** [comment]
We are revising the code to avoid the case with NaN. It will be updated in the future.

**Comment by skhonsha** [comment]
@zhumingpassional thank you, my point of view is another boolean feature is required, the stock is close or open? is it correct solution?

**Comment by zhumingpassional** [comment]
Just as rayrui312 said. We fill values for the NaN values since RL requires the same length. This may not be the perfect method, however, the effect is limited.
