### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pyfolio (unavailable)

### ISSUE THREAD

**Issue by forrestneo** [AI4Finance-Foundation/FinRL#355]
When I wanted to reinstall, I found that I couldn't install it. My system is win10, and the error is as follows:
due to  pyfolio 

(base) C:\Users\Administrator>pip install git+git://github.com/AI4Finance-Foundation/FinRL.git
Collecting git+git://github.com/AI4Finance-Foundation/FinRL.git
  Cloning git://github.com/AI4Finance-Foundation/FinRL.git to c:\users\administrator\appdata\local\temp\pip-req-build-33q5l1px
  Running command git clone --filter=blob:none -q git://github.com/AI4Finance-Foundation/FinRL.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-33q5l1px'
  Resolved git://github.com/AI4Finance-Foundation/FinRL.git to commit cf7c24bc0635c311ae455c5bc81e1ddddb2d4dff
  Preparing metadata (setup.py) ... done
Collecting pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2
  Cloning https://github.com/quantopian/pyfolio.git to c:\users\administrator\appdata\local\temp\pip-install-7g2rz1ce\pyfolio_cd6d59733e8e4800bab389a94ac83746
  Running command git clone --filter=blob:none -q https://github.com/quantopian/pyfolio.git 'C:\Users\Administrator\AppData\Local\Temp\pip-install-7g2rz1ce\pyfolio_cd6d59733e8e4800bab389a94ac83746'
  fatal: unable to access 'https://github.com/quantopian/pyfolio.git/': Failed to connect to github.com port 443: Timed out
WARNING: Discarding git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2. Command errored out with exit status 128: git clone --filter=blob:none -q https://github.com/quantopian/pyfolio.git 'C:\Users\Administrator\AppData\Local\Temp\pip-install-7g2rz1ce\pyfolio_cd6d59733e8e4800bab389a94ac83746' Check the logs for full command output.
Collecting elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git#egg=elegantrl
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to c:\users\administrator\appdata\local\temp\pip-install-7g2rz1ce\elegantrl_5262a2e4bcfd417c94c3451d9569ab6d
  Running command git clone --filter=blob:none -q https://github.com/AI4Finance-Foundation/ElegantRL.git 'C:\Users\Administrator\AppData\Local\Temp\pip-install-7g2rz1ce\elegantrl_5262a2e4bcfd417c94c3451d9569ab6d'
  fatal: unable to access 'https://github.com/AI4Finance-Foundation/ElegantRL.git/': Failed to connect to github.com port 443: Timed out
WARNING: Discarding git+https://github.com/AI4Finance-Foundation/ElegantRL.git#egg=elegantrl. Command errored out with exit status 128: git clone --filter=blob:none -q https://github.com/AI4Finance-Foundation/ElegantRL.git 'C:\Users\Administrator\AppData\Local\Temp\pip-install-7g2rz1ce\elegantrl_5262a2e4bcfd417c94c3451d9569ab6d' Check the logs for full command output.
Requirement already satisfied: numpy>=1.17.3 in e:\anaconda\lib\site-packages (from finrl==0.3.3) (1.20.1)
Requirement already satisfied: pandas>=1.1.5 in e:\anaconda\lib\site-packages (from finrl==0.3.3) (1.2.4)
Collecting stockstats
  Using cached stockstats-0.3.2-py2.py3-none-any.whl (13 kB)
Collecting yfinance
  Using cached yfinance-0.1.67-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: elegantrl in e:\anaconda\lib\site-packages (from finrl==0.3.3) (0.3.2)
Requirement already satisfied: matplotlib in e:\anaconda\lib\site-packages (from finrl==0.3.3) (3.3.4)
Requirement already satisfied: scikit-learn>=0.21.0 in e:\anaconda\lib\site-packages (from finrl==0.3.3) (0.24.1)
Requirement already satisfied: gym>=0.17 in e:\anaconda\lib\site-packages (from finrl==0.3.3) (0.19.0)
Requirement already satisfied: stable-baselines3[extra] in e:\anaconda\lib\site-packages (from finrl==0.3.3) (1.3.0)
Requirement already satisfied: ray[default] in e:\anaconda\lib\site-packages (from finrl==0.3.3) (1.8.0)
Requirement already satisfied: lz4 in e:\anaconda\lib\site-packages (from finrl==0.3.3) (3.1.3)
Requirement already satisfied: tensorboardX in e:\anaconda\lib\site-packages (from finrl==0.3.3) (2.4.1)
Requirement already satisfied: gputil in e:\anaconda\lib\site-packages (from finrl==0.3.3) (1.4.0)
Requirement already satisfied: trading_calendars in e:\anaconda\lib\site-packages (from finrl==0.3.3) (2.1.1)
Requirement already satisfied: alpaca_trade_api in e:\anaconda\lib\site-packages (from finrl==0.3.3) (1.4.1)
Requirement already satisfied: ccxt in e:\anaconda\lib\site-packages (from finrl==0.3.3) (1.61.93)
Requirement already satisfied: jqdatasdk in e:\anaconda\lib\site-packages (from finrl==0.3.3) (1.8.10)
Requirement already satisfied: wrds in e:\anaconda\lib\site-packages (from finrl==0.3.3) (3.1.1)
Requirement already satisfied: pytest in e:\anaconda\lib\site-packages (from finrl==0.3.3) (6.2.3)
Requirement already satisfied: setuptools>=41.4.0 in e:\anaconda\lib\site-packages (from finrl==0.3.3) (52.0.0.post20210125)
Requirement already satisfied: wheel>=0.33.6 in e:\anaconda\lib\site-packages (from finrl==0.3.3) (0.36.2)
Requirement already satisfied: pre-commit in e:\anaconda\lib\site-packages (from finrl==0.3.3) (2.15.0)
ERROR: Could not find a version that satisfies the requirement pyfolio (unavailable) (from finrl) (from versions: 0.1b2, 0.1b3, 0.1b4, 0.1b5, 0.1b6, 0.1b7, 0.1, 0.2, 0.3, 0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2)
ERROR: No matching distribution found for pyfolio (unavailable)

**Comment by rayrui312** [comment]
I didn't reproduce this error when installing FinRL on my own win10 PC. Have you tried `pip install pyfolio`?

**Comment by forrestneo** [comment]
I just solved this problem。
 because I did not download the whole package. I just executed this statement. 
pip install git+git://github.com/AI4Finance-LLC/FinRL-Library.git
and got that error。

We need to download the entire file directory and run pip install -r  requirements.txt
