### ISSUE TITLE
ccxt install problem

### ISSUE THREAD

**Issue by forrestneo** [AI4Finance-Foundation/FinRL#356]
When I installed it, I found that a package was installed repeatedly, and each version was installed, which was very strange.

 Using cached ccxt-1.61.83-py2.py3-none-any.whl (2.1 MB)
  Using cached ccxt-1.61.82-py2.py3-none-any.whl (2.1 MB)
  Using cached ccxt-1.61.81-py2.py3-none-any.whl (2.1 MB)
  Using cached ccxt-1.61.80-py2.py3-none-any.whl (2.1 MB)
  Using cached ccxt-1.61.79-py2.py3-none-any.whl (2.1 MB)
  Using cached ccxt-1.61.78-py2.py3-none-any.whl (2.1 MB)
  Using cached ccxt-1.61.77-py2.py3-none-any.whl (2.1 MB)
  Using cached ccxt-1.61.76-py2.py3-none-any.whl (2.1 MB)
  Using cached ccxt-1.61.75-py2.py3-none-any.whl (2.1 MB)
  Downloading ccxt-1.61.74-py2.py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 656 kB/s
  Downloading ccxt-1.61.73-py2.py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 3.3 MB/s
  Downloading ccxt-1.61.72-py2.py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 544 kB/s
  Downloading ccxt-1.61.71-py2.py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 638 kB/s
  Downloading ccxt-1.61.70-py2.py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 344 kB/s
  Downloading ccxt-1.61.69-py2.py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 262 kB/s
  Downloading ccxt-1.61.68-py2.py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 437 kB/s
  Downloading ccxt-1.61.67-py2.py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 656 kB/s
  Downloading ccxt-1.61.66-py2.py3-none-any.whl (2.1 MB)
     |███████████████                 | 993 kB 467 kB/s eta 0:00:03

**Comment by rayrui312** [comment]
Which command are you using to install CCXT? I have tried `pip install ccxt` and didn't reproduce this problem.

**Comment by StevenL2017** [comment]
it seems like
pip install finrl

**Comment by rayrui312** [comment]
For now, you may try to use `pip install git+https://github.com/AI4Finance-LLC/FinRL-Library.git ` to install the latest version of FinRL. We will check `pip install finrl`.

**Comment by XiaoYangLiu-FinRL** [comment]
If there are more issues about ccxt installation, it would be good to fix or discuss at the delicated FinRL-Meta repo: https://github.com/AI4Finance-Foundation/FinRL-Meta

**Comment by gendrelom** [comment]
I'm also experiencing this problem with 
`pip install git+https://github.com/AI4Finance-LLC/FinRL-Library.git`
and 
`pip install git+https://github.com/AI4Finance-Foundation/FinRL.git`
Can't install FinRL at all

**Comment by ConstantinosM** [comment]
I have the same issue with the above command on MacOS. Is it possible during installation to ignore any of the APIs such as the CCXT that seems to create a problem?

**Comment by AFTERaB** [comment]
fix?
