### ISSUE TITLE
FinRL_PaperTrading_Demo.ipynb from

### ISSUE THREAD

**Issue by motnellig** [AI4Finance-Foundation/FinRL#357]
FinRL_PaperTrading_Demo.ipynb

I am  having a problem with
from elegantrl.run import * not loading

How do I load the new version (elegantrl 0.3.2)
into colab?

**Comment by rayrui312** [comment]
I am updating the notebook now. A new version will be released soon.

**Comment by motnellig** [comment]
Thank you

I am looking forward to it.

Tom


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
11/22/21,
09:56:54 AM

**Comment by rayrui312** [comment]
The notebook is updated now. You may have a test.

**Comment by motnellig** [comment]
WOW That was fast and it worked!

When I ran the app, a new error message occurred at Cell 36.

paper_trading_erl.run()

HTTPError                                 Traceback (most recent call last)

/usr/local/lib/python3.7/dist-packages/alpaca_trade_api/rest.py
<https://localhost:8080/#> in _one_request(self, method, url, opts,
retry)    207         try:
--> 208             resp.raise_for_status()    209         except
HTTPError as http_error:


------------------------------
6 frames
------------------------------

HTTPError: 401 Client Error: Unauthorized for url:
https://paper-api.alpaca.markets/v2/orders?status=open

During handling of the above exception, another exception occurred:


APIError                                  Traceback (most recent call last)

/usr/local/lib/python3.7/dist-packages/alpaca_trade_api/rest.py
<https://localhost:8080/#> in _one_request(self, method, url, opts,
retry)    214                 error = resp.json()    215
  if 'code' in error:
--> 216                     raise APIError(error, http_error)    217
          else:    218                 raise


APIError: request is not authorized



Tom



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
11/22/21,
12:13:14 PM

**Comment by rayrui312** [comment]
This error comes from Alpaca side. Perhaps you may not have initialized your paper trading account on alpaca. You may try to log in on the Alpaca website and reset your paper trading account.

**Comment by motnellig** [comment]
Will do.

Thank you

Tom


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
11/22/21,
09:04:28 PM

**Comment by motnellig** [comment]
FYI

This is the reply from Alpaca support:

Hello Tom,
At this point, I think you should be looking on the other side. I don't think it's an Alpaca issue.

Sorry, I'm unable to help. Should you have any additional questions, kindly let us know!
Sincerely,

The Alpaca Team
