### ISSUE TITLE
reward function in env_btc_cctx

### ISSUE THREAD

**Issue by trungtv** [AI4Finance-Foundation/FinRL#360]
Hello, 
Could you please explain why we need to accumulate the reward at the end of the episode? I thought it is implicitly done inside the reinforcement learning models (eg. PPO in Stable baseline 3). Am I wrong? 

```
if done:
            reward += self.gamma_return
            self.gamma_return = 0.0
            self.episode_return = next_total_asset / self.initial_account
return state, reward, done, None
```

**Comment by rayrui312** [comment]
I am not clear whether it is implicitly done in Stable baselines3. But it is not implicitly done in ElegantRL and RLlib. Could you please provide related docs of Stable baselines3 so that we can have a check? Thanks.
