### ISSUE TITLE
Can't reproduce the result in FinRL_Compare_ElegantRL_RLlib_Stablebaseline3.ipynb

### ISSUE THREAD

**Issue by nonetodo** [AI4Finance-Foundation/FinRL#365]
Hi, 

After commenting out the following two lines because of error, the notebook ran successfully. 
  from elegantrl.agent import *
  from elegantrl.run import *

However, the total return was lower than the benchmark (^DJI) while the result showed in the original notebook was way better than the benchmark.   Also tried to run it on Google CoLab and it's also lower than the benchmark. 
Please advice on how to reproduce the result.  Thanks! 

![image](https://user-images.githubusercontent.com/2695449/143497729-f1514a7e-bfce-4326-9ac3-e4be0c727405.png)

**Comment by Athe-kunal** [comment]
Check out this [issues](https://github.com/AI4Finance-Foundation/FinRL/issues/362) for deterministic actions in the test set and test again

**Comment by nonetodo** [comment]
Thanks for the StableBaseline3 parameter for deterministic=True !

Do I need to make similar deterministic code/parameter change for the ElegantRL and RLlib's model.py file? 

Here are the original code from the repo:

ElegantRL:
            a_tensor = act(s_tensor)  # action_tanh = act.forward()

RLlib:
            action = trainer.compute_single_action(state)

**Comment by nonetodo** [comment]
The deterministic=True seems for the prediction only with the same trained model. 
However, the problem was for re-training model, the performance of the each re-trained model from beginning seemed very inconsistent.   And most of the re-trained model performed worse than the benchmark.

**Comment by joseerasmosilva** [comment]
> The deterministic=True seems for the prediction only with the same trained model. However, the problem was for re-training model, the performance of the each re-trained model seemed very inconsistent. Most of the re-trained model performed worse or similar to the benchmark. The result in the original notebook seems much better than the benchmark with ElegantRL and StableBaseline3.

@nonetodo, did you find a solution?
@Athe-kunal, could you help us?

**Comment by Athe-kunal** [comment]
I guess for reproducible training, you need to pass the seed value. Like here https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/drl_agents/stablebaselines3/models.py#L75 for SB3 models.
For more deterministic results, I would suggest you can add this
seed = 777
`
def seed_torch(seed):
    torch.manual_seed(seed)
    if torch.backends.cudnn.enabled:
        torch.backends.cudnn.benchmark = False
        torch.backends.cudnn.deterministic = True

np.random.seed(seed)
seed_torch(seed)
env.seed(seed)
`
It is taken from (here)[https://github.com/Curt-Park/rainbow-is-all-you-need/blob/master/01.dqn.ipynb]

**Comment by joseerasmosilva** [comment]
Perfect, it works. Thanks.

**Comment by Athe-kunal** [comment]
Yeah do verify if you are getting consistent training results with the seed values. Looking forward to your observations.
