### ISSUE TITLE
Turbulence index vs VIX

### ISSUE THREAD

**Issue by Abaminog** [AI4Finance-Foundation/FinRL#366]
The stock trading algorithm uses 2 turbulence indices: VIX (downloaded from Yahoo) and a 'turbulence index' that is calculated. Apparently, the trading is suspended and all the stocks are sold when the calculated turbulence index exceeds a certain threshold, say its historical maximum. What is the purpose then of the VIX index? If I set the turbulence threshold to a very high level, so that the algorithm essentially ignores it, how does VIX then effect the algorithm's logic? Can I set the VIX column in the input data to some dummy value (say, 0 or very high positive/negative) to force the model essentially ignore it? Thanks.

**Comment by rayrui312** [comment]
It takes time to calculate the turbulence index, which makes it hard to deploy in paper trading. However, VIX can be accessed immediately. It serves as a substitute for turbulence index. If you don't want to use VIX, you can change the environment and delete VIX from states and step settings. 

Hope this helps.

**Comment by Abaminog** [comment]
Thank you. This is helpful. So basically, if I force the environment to use the VIX column as risk_indicator_col, set the entire VIX column to zero, and set the turbulence threshold to a high number, then the algorithm should react as if there is no turbulence index, because every step it checks that the current turbulence (which is VIX=0) is lower than the turbulence threshold (very high) and does all trades as normal.

**Comment by rayrui312** [comment]
If you don't want to use the forced sale settings when VIX is high, it's OK to do so. However, if you're going to avoid VIX altogether, you may also remove it from the state. (In env_stocktrading_np.py, VIX is also included in the states, the agent will observe it and take action accordingly.)

**Comment by rohita77** [comment]
Is the the turbulence index being calculated by FinRL during training or is it being downloaded from somewhere?

**Comment by BruceYanghy** [comment]
>

**Comment by BruceYanghy** [comment]
> Is the the turbulence index being calculated by FinRL during training or is it being downloaded from somewhere?

FinRL uses this function [calculate_turbulence](https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/finrl_meta/data_processors/processor_yahoofinance.py) based on the paper: [Skulls, Financial Turbulence, and Risk Management](https://www.top1000funds.com/wp-content/uploads/2010/11/FAJskulls.pdf) to calculate turbulence index.
