### ISSUE TITLE
Issue with StockTradingEnvStopLoss

### ISSUE THREAD

**Issue by benwaldner** [AI4Finance-Foundation/FinRL#369]
If I replace at the papertrading.py the import: from finrl.neo_finrl.env_stock_trading.env_stocktrading_np import StockTradingEnv to the stopp loss env: from finrl.neo_finrl.env_stock_trading.env_stocktrading_stoploss import StockTradingEnvStopLoss and define env = StockTradingEnvStopLoss at the API section in the papertrading.py file.

I get at the train section train(start_date = '2021-10-11'...) the following error.

Dont understand what I did wrong

How to fix this error to make the stop loss env work?
(note: neo_finrl was renamed at the imports)

TypeError                                 Traceback (most recent call last)

<ipython-input-21-dd3b0697dc22> in <module>()
     13       erl_params=ERL_PARAMS,
     14       cwd='./papertrading_erl', #current_working_dir
---> 15       break_step=1e5)

/usr/local/lib/python3.7/dist-packages/finrl/train.py in train(start_date, end_date, ticker_list, data_source, time_interval, technical_indicator_list, drl_lib, env, model_name, if_vix, **kwargs)
     34         "if_train": True,
     35     }
---> 36     env_instance = env(config=env_config)
     37 
     38     # read parameters

TypeError: __init__() got an unexpected keyword argument 'config'

**Comment by Athe-kunal** [comment]
Refer [here](https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/finrl_meta/env_stock_trading/env_stocktrading_stoploss.py#L61). You can find the init config of Stop loss environment
