### ISSUE TITLE
neo_finrl missing in finrl folder

### ISSUE THREAD

**Issue by texasraj** [AI4Finance-Foundation/FinRL#372]
Most of the Jupyter Notebooks failing with the following imports:

from **finrl.neo_finrl.**preprocessor.yahoodownloader import YahooDownloader
from finrl.neo_finrl.preprocessor.preprocessors import FeatureEngineer, data_split
from finrl.neo_finrl.env_stock_trading.env_stocktrading import StockTradingEnv
from finrl.neo_finrl.env_stock_trading.env_stocktrading_np import StockTradingEnv as StockTradingEnv_numpy 

Is there a particular version of the code I have to download, to run the Jupyter Notebooks? Thanks!

**Comment by Athe-kunal** [comment]
Change neo_finrl to finrl_meta.

**Comment by texasraj** [comment]
Thanks Kunal bhai!!

**Comment by rayrui312** [comment]
Thanks for reporting it. We have renamed neo_finrl to finrl_meta. We are now updating our notebooks.
