### ISSUE TITLE
stable-baselines3 tensorboard_log directory

### ISSUE THREAD

**Issue by StevenL2017** [AI4Finance-Foundation/FinRL#375]
Hello,

For now, it seems that I cannot revise the log directory when using stable-baselines3 models, may be it is nice to revise the code similar with the code below?

    def get_model(
        self,
        model_name,
        policy="MlpPolicy",
        policy_kwargs=None,
        model_kwargs=None,
        verbose=1,
        seed=None,
        **tensorboard_log=None,**
    ):
        if model_name not in MODELS:
            raise NotImplementedError("NotImplementedError")

        if model_kwargs is None:
            model_kwargs = MODEL_KWARGS[model_name]

        if "action_noise" in model_kwargs:
            n_actions = self.env.action_space.shape[-1]
            model_kwargs["action_noise"] = NOISE[model_kwargs["action_noise"]](
                mean=np.zeros(n_actions), sigma=0.1 * np.ones(n_actions)
            )
        print(model_kwargs)
        model = MODELS[model_name](
            policy=policy,
            env=self.env,
            **tensorboard_log=tensorboard_log,**
            verbose=verbose,
            policy_kwargs=policy_kwargs,
            seed=seed,
            **model_kwargs,
        )
        return model

**Comment by rayrui312** [comment]
Thanks for reporting it. Could you please submit a pull request for it? We will review and test your codes.
