### ISSUE TITLE
What's the difference between the two versions of StockTradingEnv?

### ISSUE THREAD

**Issue by aksevenli** [AI4Finance-Foundation/FinRL#377]
I have spent several days exploring this framework and I have a question regarding the StockTradingEnvironment. 

I went through the tutorials and found different implementations of the StockTradingEnvironment. 

In the tutorial tutorial_multistock_docker.ipynb, you implemented the StockTradingEnvV2, which contains the log_step() function. 

But in the tutorial FinRL_Ensemble_StockTrading_ICAIF_2020.ipynb, you just imported the StockTradingEnv from finrl_meta. 

I would like to know which of the two environments you recommend me to use? Are there any differences between the two implementations?

**Comment by Athe-kunal** [comment]
In the first tutorial, you have StockTradingEnvV2 and the main functionalities in my opinion are daily_information_cols and out_of_cash_penalty. Daily information cols will augment the state space beyond OHLCV data. In the second tutorial, we have ensemble trading, you can see [here](https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/drl_agents/stablebaselines3/models.py#L162) that the [StockTradingEnv ](https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/finrl_meta/env_stock_trading/env_stocktrading.py)is hardcoded in line 479.
