### ISSUE TITLE
env_multiple_crypto.py mistake in step function

### ISSUE THREAD

**Issue by DjoFE2021** [AI4Finance-Foundation/FinRL#378]
In the file env_multiple_crypto.py, inside of the step function. When the agent purchase unit of a crypto. One should replace on line 66 self.cash//price[index] by self.cash//(self.price[index]*1+self.buy_cost_pct). It otherwise results in negative cash situations since it purchases more shares than it actuall could.

**Comment by rayrui312** [comment]
Thanks for pointing it out. We have updated it in the newest version.
