### ISSUE TITLE
Why can't display date as x-axis when using the backtest_plot() function?

### ISSUE THREAD

**Issue by aksevenli** [AI4Finance-Foundation/FinRL#379]
Hi, 

I am not able to display the date as x-axis when using the "backtest_plot()" function. And I noticed that in all the tutorials, the x-axis is also empty. Is it an issue due to the matplotlib version?

**Comment by Athe-kunal** [comment]
Hi @aksevenli  
Here https://githubmemory.com/repo/quantopian/pyfolio/issues/636 they are downgrading matplotlib to display the x-axis. Do try it out
