### ISSUE TITLE
Market Liquidity

### ISSUE THREAD

**Issue by thy-hoang-nn** [AI4Finance-Foundation/FinRL#380]
I am a beginner in finance, so I do not understand why we assume the agent's action does not impact the market attributes in stock trading. That means the trading actions occur close to the market closure. Can anyone explain the problem in detail? Some assumptions (market liquidity)make me confused.

**Comment by Athe-kunal** [comment]
The agent is trading on a small volume that is around 100 shares at max( can go higher). But if you have a large order volume you may affect the prices, that is changing the history. The transactions are fulfilled based on a order book where people bid and ask for their prices. A higher order volume will likely fulfill many orders leading to changes in price. So we assume the actions by our agent does not change the prices else our train data would be invalid.

**Comment by thy-hoang-nn** [comment]
If the prices change in that way, the trading agent cannot detect the market trend by the listed indicators, right? Can we call the market change is sentiment?

**Comment by Athe-kunal** [comment]
I guess not. Actually you are training on historical data, so if your agent is able to change it somehow, then it may lead to invalid training. We just assume that whatever our agent does, it will not affect the prices. The changes will be unpredictable also

**Comment by XiaoYangLiu-FinRL** [comment]
@thy-hoang-nn would you like to do market simulation (say on limit order Book, or liquidation model)?  It is a challenging and interesting task.

**Comment by thy-hoang-nn** [comment]
@XiaoYangLiu-FinRL Yes, I am trying to understand the concept and simulate this type of market.

**Comment by XiaoYangLiu-FinRL** [comment]
If you have some progress, please refer to the FinRL-Meta repo: https://github.com/AI4Finance-Foundation/FinRL-Meta
