### ISSUE TITLE
Add type hints for FinRL

### ISSUE THREAD

**Issue by antolu** [AI4Finance-Foundation/FinRL#381]
Hey all, I was using the library a bit but found it hard to use because type hinting is missing, and documentation for the code is sparse. 

I suggest to add [PEP 484 type hints](https://www.python.org/dev/peps/pep-0484/) for the whole library, which will significantly improve readability and development for external people of the code.

I volunteer to do this, but want input from the authors.

**Comment by XiaoYangLiu-FinRL** [comment]
Can we start from sime simple ones, gradually updating it?

**Comment by antolu** [comment]
Certainly. I was going to start with the python modules and walk it through with PyCharm.

**Comment by XiaoYangLiu-FinRL** [comment]
I do agree that code refactoring (type hints, parameter explanations, etc.) is very useful to increase readability. 
It is very helpful to walk through the codes (testing and cleaning) with you. Thanks in advance.

**Comment by Athe-kunal** [comment]
Hey @antolu , I would like to volunteer to work with you on hinting. Let me know how we can collaborate
