### ISSUE TITLE
issue in FinRL_PaperTrading_Demo.ipynb

### ISSUE THREAD

**Issue by MerrickBZheng** [AI4Finance-Foundation/FinRL#385]
data = DP.clean_data(data)
data = DP.add_technical_indicator(data, TECHNICAL_INDICATORS_LIST)
**data = DP.add_vix(data)**

Data clean finished!
Succesfully add technical indicators
Data before 2021-12-01T15:59:00-05:00 is successfully fetched
Data before 2021-12-02T15:59:00-05:00 is successfully fetched
Data before 2021-12-03T15:59:00-05:00 is successfully fetched
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-68c2b2d21f37> in <module>()
      1 data = DP.clean_data(data)
      2 data = DP.add_technical_indicator(data, TECHNICAL_INDICATORS_LIST)
----> 3 data = DP.add_vix(data)

2 frames
/usr/local/lib/python3.7/dist-packages/finrl/finrl_meta/data_processor.py in add_vix(self, df)
     58 
     59     def add_vix(self, df) -> pd.DataFrame:
---> 60         df = self.processor.add_vix(df)
     61 
     62         return df

/usr/local/lib/python3.7/dist-packages/finrl/finrl_meta/data_processors/processor_alpaca.py in add_vix(self, data)
    142     def add_vix(self, data):
    143         vix_df = self.download_data(["VIXY"], self.start, self.end, self.time_interval)
--> 144         cleaned_vix = self.clean_data(vix_df)
    145         vix = cleaned_vix[["time", "close"]]
    146         vix = vix.rename(columns={"close": "VIXY"})

/usr/local/lib/python3.7/dist-packages/finrl/finrl_meta/data_processors/processor_alpaca.py in clean_data(self, df)
     81                     previous_close = tmp_df.iloc[i - 1]["close"]
     82                     if str(previous_close) == "nan":
---> 83                         raise ValueError
     84                     tmp_df.iloc[i] = [
     85                         previous_close,

ValueError:

**Comment by MerrickBZheng** [comment]
**It may be from Daylight saving time**

Data clean finished!
Succesfully add technical indicators
Data before 2021-11-01T15:59:00-04:00 is successfully fetched
Data before 2021-11-02T15:59:00-04:00 is successfully fetched
Data before 2021-11-03T15:59:00-04:00 is successfully fetched
Data clean finished!

**Comment by rayrui312** [comment]
Thanks for reporting it. We will look into it.

**Comment by rayrui312** [comment]
We have updated the alpaca data processor. You may try if it solves the problem.

**Comment by MerrickBZheng** [comment]
Thanks!  see another error

**data = DP.clean_data(data)**

data = DP.add_technical_indicator(data, TECHNICAL_INDICATORS_LIST)


The price of the first row is NaN. It will filled with the first valid price.
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-22-3aa220b30645> in <module>()
----> 1 data = DP.clean_data(data)
      2 data = DP.add_technical_indicator(data, TECHNICAL_INDICATORS_LIST)

1 frames
/usr/local/lib/python3.7/dist-packages/finrl/finrl_meta/data_processor.py in clean_data(self, df)
     42 
     43     def clean_data(self, df) -> pd.DataFrame:
---> 44         df = self.processor.clean_data(df)
     45 
     46         return df

/usr/local/lib/python3.7/dist-packages/finrl/finrl_meta/data_processors/processor_alpaca.py in clean_data(self, df)
     84                           first_valid_price = tmp_df.iloc[i]["close"]
     85                           break
---> 86                    tmp_df.iloc[0] = [first_valid_price,
     87                                      first_valid_price,
     88                                      first_valid_price,

UnboundLocalError: local variable 'first_valid_price' referenced before assignment

**Comment by rayrui312** [comment]
Thanks for reporting it.  We have updated the codes now. You may have a try. See issue 389 [here](https://github.com/AI4Finance-Foundation/FinRL/issues/389).
