### ISSUE TITLE
why for linux

### ISSUE THREAD

**Issue by eiuc** [AI4Finance-Foundation/FinRL#393]
why the FinRL  can not work on windows?

**Comment by XiaoYangLiu-FinRL** [comment]
https://ai4finance.medium.com/finrl-for-quantitative-finance-install-and-setup-tutorial-for-beginners-1db80ad39159

**Comment by rayrui312** [comment]
FinRL can work on windows. What errors are you meeting on windows? You may report it here, and we can figure it out.

**Comment by eiuc** [comment]
oh，I,m new here.According to the tutorialI,we should first install Ubuntu on Windows 10.How about use in on windows directly?

**Comment by eiuc** [comment]
Oh，I,m new here.According to the tutorialI,we should first install Ubuntu on Windows 10.Can we use it on windows directly?

**Comment by XiaoYangLiu-FinRL** [comment]
@eiuc would you like to try to set it up on Windows directly?  Would very appreciate a windows running setup.
