### ISSUE TITLE
Is a log for training visualization implemented?

### ISSUE THREAD

**Issue by rfsilva1** [AI4Finance-Foundation/FinRL#4]
First of all, thanks a lot for the great work!!!!
I'm using the EnvSingleStock to evaluate the models on a specific stock. I want to better visualize the model training to evaluate it (as I'll train multiple runs of each model with different hyperparameter configuration and want to compare them). Is there a log implemented that would allow me to check:
- the end_total_asset, total_reward, total_cost, total_trades, and Sharpe during model training (could be just a df of the values printed during training the model)
- the chart related to the rewards during the training period
- the trades that were made by the agent during the training period (when they were made and what were their characteristics (buy or sell and how much)
Is there a way to do it? (it doesn't need to be online, could be after the training is over). It would be easy to do
Thanks!!!

**Comment by BruceYanghy** [comment]
> First of all, thanks a lot for the great work!!!!
> I'm using the EnvSingleStock to evaluate the models on a specific stock. I want to better visualize the model training to evaluate it (as I'll train multiple runs of each model with different hyperparameter configuration and want to compare them). Is there a log implemented that would allow me to check:
> 
> * the end_total_asset, total_reward, total_cost, total_trades, and Sharpe during model training (could be just a df of the values printed during training the model)
> * the chart related to the rewards during the training period
> * the trades that were made by the agent during the training period (when they were made and what were their characteristics (buy or sell and how much)
>   Is there a way to do it? (it doesn't need to be online, could be after the training is over). It would be easy to do
>   Thanks!!!

Hello,

We will add logging and versioning in the next version. 

Currently you can use functions inside the environment file to save it to a csv file or simply just print it out.

The render function in the SingleStockEnv can help you get model outputs in each step.

**In models.py**
    def DRL_prediction(model, test_data, test_env, test_obs):
        """make a prediction"""
        start = time.time()
        account_memory = []
        for i in range(len(test_data.index.unique())):
            action, _states = model.predict(test_obs)
            test_obs, rewards, dones, info = test_env.step(action)
            if i == (len(test_data.index.unique()) - 2):
                account_memory = test_env.env_method(method_name = 'save_asset_memory')
                actions_memory = test_env.env_method(method_name = 'save_action_memory')
        end = time.time()
        return account_memory[0], actions_memory[0]

**In SingleStockEnv.py**
    def render(self, mode='human'):
        return self.state
    
    def save_asset_memory(self):
        date_list = self.date_memory
        asset_list = self.asset_memory
        #print(len(date_list))
        #print(len(asset_list))
        df_account_value = pd.DataFrame({'date':date_list,'account_value':asset_list})
        return df_account_value

    def save_action_memory(self):
        # date and close price length must match actions length
        date_list = self.date_memory[:-1]
        close_price_list = self.close_price_memory[:-1]

        action_list = self.actions_memory
        df_actions = pd.DataFrame({'date':date_list,'actions':action_list,'close_price':close_price_list})
        df_actions['daily_return']=df_actions.close_price.pct_change()
        return df_actions

**Comment by rfsilva1** [comment]
Hi there!
Thanks for the great and quick answer!!! Great, so it's already implemented, I just need to export as csv :)
Just some quick questions to clarify if I understood correctly (sorry if they seem obvious, it's just that I'm diving deep into the code and trying to understand it better):

**1.** a question related to the model itself: the agent can carry its stocks from one period to the next if it maximizes its rewards (in other words, there is no restriction that makes it close its position each day, selling all the stocks it has), correct?
**2.** is the `hmax` the maximum number of shares to trade in each timestep, (ex: if hmax = 100, the agent can only buy or sell 100 stocks in that day, for daily trading)?
**3.** is the `asset_list` (in bold, below) the reward I'm looking to represent: the net value of the account = (amount of stocks I have * the current price per stock) + money left on the account for buying for stocks?

```
def save_asset_memory(self):
        date_list = self.date_memory
        **asset_list = self.asset_memory**
        #print(len(date_list))
        #print(len(asset_list))
        df_account_value = pd.DataFrame({'date':date_list,'account_value':asset_list})
        return df_account_value

```
**4.** is the `action_list` (in bold, below) the total number of shares I own at the moment (ex: 1000 means I own 1000 at that day, 400 on the next day means I sold 600 of those shares, what means I now own 400 shares)?

```
def save_action_memory(self):
        # date and close price length must match actions length
        date_list = self.date_memory[:-1]
        close_price_list = self.close_price_memory[:-1]

        **action_list = self.actions_memory**
        df_actions = pd.DataFrame({'date':date_list,'actions':action_list,'close_price':close_price_list})
        df_actions['daily_return']=df_actions.close_price.pct_change()
        df_actions.to_csv('actions.csv')
        return df_actions

```
**5.** is the `self.rewards_memory` (in bold, below) the history of rewards per day on the train dataset (ex: -100 means that in that specific day, the agent's actions reduced the self.asset in 100 dollars)?

```
if self.terminal:
            #plt.plot(self.asset_memory,'r')
            #plt.savefig('results/account_value_train.png')
            #plt.close()
            end_total_asset = self.state[0]+ \
                sum(np.array(self.state[1:(self.stock_dim+1)])*np.array(self.state[(self.stock_dim+1):(self.stock_dim*2+1)]))

            print("begin_total_asset:{}".format(self.asset_memory[0]))           
            print("end_total_asset:{}".format(end_total_asset))
            df_total_value = pd.DataFrame(self.asset_memory)
            #df_total_value.to_csv('results/account_value_train.csv')
            print("total_reward:{}".format(self.state[0]+sum(np.array(self.state[1:(self.stock_dim+1)])*np.array(self.state[(self.stock_dim+1):(self.stock_dim*2+1)]))- self.initial_amount ))
            print("total_cost: ", self.cost)
            print("total_trades: ", self.trades)
            df_total_value.columns = ['account_value']
            df_total_value['daily_return']=df_total_value.pct_change(1)
            if df_total_value['daily_return'].std() !=0:
              sharpe = (252**0.5)*df_total_value['daily_return'].mean()/ \
                    df_total_value['daily_return'].std()
              print("Sharpe: ",sharpe)
              print("=================================")
            ****df_rewards = pd.DataFrame(self.rewards_memory)****
                     
            
            return self.state, self.reward, self.terminal,{}

```
**6.** if those questions are correct, how do I get the history of stocks traded per day?

Thanks a lot for your help and great work!!!!!

**Comment by BruceYanghy** [comment]
> Hi there!
> Thanks for the great and quick answer!!! Great, so it's already implemented, I just need to export as csv :)
> Just some quick questions to clarify if I understood correctly (sorry if they seem obvious, it's just that I'm diving deep into the code and trying to understand it better):
> 
> **1.** a question related to the model itself: the agent can carry its stocks from one period to the next if it maximizes its rewards (in other words, there is no restriction that makes it close its position each day, selling all the stocks it has), correct?
> **2.** is the `hmax` the maximum number of shares to trade in each timestep, (ex: if hmax = 100, the agent can only buy or sell 100 stocks in that day, for daily trading)?
> **3.** is the `asset_list` (in bold, below) the reward I'm looking to represent: the net value of the account = (amount of stocks I have * the current price per stock) + money left on the account for buying for stocks?
> 
> ```
> def save_asset_memory(self):
>         date_list = self.date_memory
>         **asset_list = self.asset_memory**
>         #print(len(date_list))
>         #print(len(asset_list))
>         df_account_value = pd.DataFrame({'date':date_list,'account_value':asset_list})
>         return df_account_value
> ```
> 
> **4.** is the `action_list` (in bold, below) the total number of shares I own at the moment (ex: 1000 means I own 1000 at that day, 400 on the next day means I sold 600 of those shares, what means I now own 400 shares)?
> 
> ```
> def save_action_memory(self):
>         # date and close price length must match actions length
>         date_list = self.date_memory[:-1]
>         close_price_list = self.close_price_memory[:-1]
> 
>         **action_list = self.actions_memory**
>         df_actions = pd.DataFrame({'date':date_list,'actions':action_list,'close_price':close_price_list})
>         df_actions['daily_return']=df_actions.close_price.pct_change()
>         df_actions.to_csv('actions.csv')
>         return df_actions
> ```
> 
> **5.** is the `self.rewards_memory` (in bold, below) the history of rewards per day on the train dataset (ex: -100 means that in that specific day, the agent's actions reduced the self.asset in 100 dollars)?
> 
> ```
> if self.terminal:
>             #plt.plot(self.asset_memory,'r')
>             #plt.savefig('results/account_value_train.png')
>             #plt.close()
>             end_total_asset = self.state[0]+ \
>                 sum(np.array(self.state[1:(self.stock_dim+1)])*np.array(self.state[(self.stock_dim+1):(self.stock_dim*2+1)]))
> 
>             print("begin_total_asset:{}".format(self.asset_memory[0]))           
>             print("end_total_asset:{}".format(end_total_asset))
>             df_total_value = pd.DataFrame(self.asset_memory)
>             #df_total_value.to_csv('results/account_value_train.csv')
>             print("total_reward:{}".format(self.state[0]+sum(np.array(self.state[1:(self.stock_dim+1)])*np.array(self.state[(self.stock_dim+1):(self.stock_dim*2+1)]))- self.initial_amount ))
>             print("total_cost: ", self.cost)
>             print("total_trades: ", self.trades)
>             df_total_value.columns = ['account_value']
>             df_total_value['daily_return']=df_total_value.pct_change(1)
>             if df_total_value['daily_return'].std() !=0:
>               sharpe = (252**0.5)*df_total_value['daily_return'].mean()/ \
>                     df_total_value['daily_return'].std()
>               print("Sharpe: ",sharpe)
>               print("=================================")
>             ****df_rewards = pd.DataFrame(self.rewards_memory)****
>                      
>             
>             return self.state, self.reward, self.terminal,{}
> ```
> 
> **6.** if those questions are correct, how do I get the history of stocks traded per day?
> 
> Thanks a lot for your help and great work!!!!!

1. you can set a restriction if you want, now for multiple stock trading, we use turbulence index as the risk aversion signal to control buy or sell.
2. Correct
3. Correct
4. action_list is actually your question 6, the history of stock shares traded per day
5. Correct
6. refer to 4
