### ISSUE TITLE
beginner stock trading notebook not accessable

### ISSUE THREAD

**Issue by brianhance** [AI4Finance-Foundation/FinRL#402]
hi, thanks for this excellent repository. I am a beginner, and the tutorial notebook in the article https://ai4finance.medium.com/finrl-for-quantitative-finance-install-and-setup-tutorial-for-beginners-1db80ad39159 seems to not be found. Is there another way I can access this notebook?
Thanks.

**Comment by rayrui312** [comment]
Sorry for the inconvenience caused. The new link is [here](https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_StockTrading_NeurIPS_2018.ipynb).

**Comment by rayrui312** [comment]
The link in the medium blog is also updated.
