### ISSUE TITLE
NameError: name 'config' is not defined: in Tutorial Installing FinRL via Colab 

### ISSUE THREAD

**Issue by marcipops** [AI4Finance-Foundation/FinRL#403]
I'm a beginner, so following: FinRL for Quantitative Finance: Install and Setup Tutorial for Beginners
https://ai4finance.medium.com/finrl-for-quantitative-finance-install-and-setup-tutorial-for-beginners-1db80ad39159
Selected Colab option: Section 4: Google Colab
Following instructions and failed at section: 4.3 Run FinRL
"Google Colab has a lot of default packages which is very convenient. Just follow the steps in the FinRL notebook, you should be able to install and run FinRL."

Running FinRL_StockTrading_NeurIPS_2018.ipynb, failed at
section "2.1. Install all the packages through FinRL library"

Import os
if not os.path.exists("./" + config.DATA_SAVE_DIR):
    os.makedirs("./" + config.DATA_SAVE_DIR)
if not os.path.exists("./" + config.TRAINED_MODEL_DIR):
    os.makedirs("./" + config.TRAINED_MODEL_DIR)
if not os.path.exists("./" + config.TENSORBOARD_LOG_DIR):
    os.makedirs("./" + config.TENSORBOARD_LOG_DIR)
if not os.path.exists("./" + config.RESULTS_DIR):
    os.makedirs("./" + config.RESULTS_DIR)

Error:

NameError: name 'config' is not defined

How do I resolve this please?

Thanks!

**Comment by rayrui312** [comment]
Thanks for reporting it. We have updated the notebook. You may have a try and check if it solves the problem.

**Comment by marcipops** [comment]
thanks rayrui312 for solving this so quickly!

Yes, adding "from finrl.apps import config" solved the problem.

Many thanks and Happy New Year!
