### ISSUE TITLE
FinRL_PortfolioAllocation_NeurIPS_2020.ipynb

### ISSUE THREAD

**Issue by joseerasmosilva** [AI4Finance-Foundation/FinRL#404]
Hello!
I'm testing this notebook and realized that: each round show much different results in df_actions, even that I use the same data and params. That it, each round I have a portfolio totally different. ​
This behavior occur with both A2C and PPO. 
No problem with DDPG, SAC, and TD3.
Could anyone explain why, please?
Thanks
Notebook: FinRL_PortfolioAllocation_NeurIPS_2020.ipynb

**Comment by Athe-kunal** [comment]
Please refer to this [issue](https://github.com/AI4Finance-Foundation/FinRL/issues/362)

**Comment by joseerasmosilva** [comment]
Thanks @Athe-kunal
