### ISSUE TITLE
Colab Notebook Link Broken For ElegantRL Demo: Stock Trading Using DDPG (Part II)

### ISSUE THREAD

**Issue by lgwaustralia** [AI4Finance-Foundation/FinRL#405]
I can't seem to find the Colab notebook for the following.  Look forward to running this.
https://github.com/AI4Finance-Foundation/ElegantRL/blob/master/eRL_demo_StockTrading.ipynb

**Comment by rayrui312** [comment]
Thanks for reporting it. We will update the link in ElegantRL. For now, you may see the notebook here: [FinRL_Compare_ElegantRL_RLlib_Stablebaseline3.ipynb](https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_Compare_ElegantRL_RLlib_Stablebaseline3.ipynb.). You may try to use ElegantRL and select the DDPG algorithm by setting the parameters.
