### ISSUE TITLE
Dates in tutorial: "A Data Scientist’s Approach for Algorithmic Trading using Deep Reinforcement Learning: An End-to-end Tutorial for Paper Trading"

### ISSUE THREAD

**Issue by marcipops** [AI4Finance-Foundation/FinRL#406]
Just wanted to check the dates please in tutorial: "A Data Scientist’s Approach for Algorithmic Trading using Deep Reinforcement Learning: An End-to-end Tutorial for Paper Trading" found at https://medium.datadriveninvestor.com/a-data-scientists-approach-for-algorithmic-trading-using-deep-reinforcement-learning-an-be8da40b2230

I have checked the code referenced: https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_PaperTrading_Demo.ipynb and is consistent with the dates in tutorial, as follows:

Section 2.3 Train our DRL agent
train(start_date = '2021-10-11',
      end_date = '2021-10-15', ...

Section 2.4 Test our DRL agent
 test(start_date = '2021-10-18',
      end_date = '2021-10-19', ...

Section 2.5 Use full data to train
train(start_date = '2021-10-11',
      end_date = '2021-10-19', ...

However, Section 2.2. Data Engineering, Step 2 (and the corresponding code) states:
data = DP.download_data(start_date = '2021-10-01',
                        end_date = '2021-10-05', ...

Should this last start_date be '2021-10-11' and the end_date be '2021-10-19', so as to cover the complete set of data for train and test periods?

Many thanks and Happy New Year!

**Comment by XelHaku** [comment]
Train method downloads the data by itself.

I personally commented out section 2.2

The author put it there as to shows how is data downloaded and cleaned up

And yes, the dates don't match but is ok because it will be downloaded when
using the train method

**Comment by marcipops** [comment]
Hi XelHaku thanks for your reply.  Understood.

However wasn't the point of step 3 to clean and featurize the data? Or is this done in the other sections within the train and test functions?

Many thanks

**Comment by marcipops** [comment]
I've just had a look at the finrl.train and finrl.test codes in https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/train.py and test.py, and they do incorporate these clean and featurize functions - so answered my own question!
Thanks anyway!

**Comment by XelHaku** [comment]
Great! I just woke up, sorry

As an advice, you can still download in section 2.2 a small period, 2 or 3
days, just to see the shape of your data before going in to full training.

Useful when adding more stocks and indicators

**Comment by marcipops** [comment]
Thanks XelHaku – will take your advice!
