### ISSUE TITLE
FinRL_PaperTrading_Demo.ipynb fails to run: ImportError: cannot import name 'get_date_from_diff' from 'int_date' (/usr/local/lib/python3.7/dist-packages/int_date.py).

### ISSUE THREAD

**Issue by marcipops** [AI4Finance-Foundation/FinRL#409]
From Colab, running FinRL_PaperTrading_Demo.ipynb notebook, has just started failing with this error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-c20a148b5b86> in <module>()
----> 1 from finrl.train import train
      2 from finrl.test import test
      3 from finrl.apps.config import DOW_30_TICKER
      4 from finrl.apps.config import TECHNICAL_INDICATORS_LIST
      5 from finrl.finrl_meta.env_stock_trading.env_stocktrading_np import StockTradingEnv

3 frames
/usr/local/lib/python3.7/dist-packages/stockstats.py in <module>()
     35 import numpy as np
     36 import pandas as pd
---> 37 from int_date import get_date_from_diff
     38 
     39 __author__ = 'Cedric Zhuang'

ImportError: cannot import name 'get_date_from_diff' from 'int_date' (/usr/local/lib/python3.7/dist-packages/int_date.py).

**Comment by benwaldner** [comment]
Add a new code block and set: !pip install int_date==0.1.8
This fixes the issue

Thanks to @Athe-kunal for fixing it

**Comment by marcipops** [comment]
Thanks benwaldner for your rapid help!

Could also someone please fix FinRL_PaperTrading_Demo.ipynb, so it can still run out of the box for newbies like me?

Much appreciated!

**Comment by asheone** [comment]
I will double the above, am going through some difficulties running it with python 3.6 and 3.7 due to multiple different errors. Thanks in advance!

**Comment by lcavalie** [comment]
I'm running everything under python 3.8.11 and that solved a lot of problems of that nature. Including running on Apple Silicon with a M1 processor.

**Comment by marcipops** [comment]
With the latest change released, this issue I report is now working with my environment so will close it.  If others still have an issue please open a ticket with details of their environment.  thanks!
