### ISSUE TITLE
Can't find token for Jupyter

### ISSUE THREAD

**Issue by gendrelom** [AI4Finance-Foundation/FinRL#410]
I'm trying to use FinRL via Docker on Windows 10. I built a container using this command:
`docker build -f docker/Dockerfile -t finrl .`
After that I started a notebook server using this command:
`docker run -it -p 8887:8888  finrl`
But `http://127.0.0.1:8888/` shows only this:
![image](https://user-images.githubusercontent.com/77203653/148272977-02f55431-4323-4112-99f5-c4ac209a0651.png)
But I can't find the token in the output:

> [W 2022-01-05 18:57:19.591 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2022-01-05 18:57:19.591 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [I 2022-01-05 18:57:19.593 ServerApp] jupyterlab | extension was successfully linked.
> [I 2022-01-05 18:57:19.598 ServerApp] Writing Jupyter server cookie secret to /root/.local/share/jupyter/runtime/jupyter_cookie_secret
> [I 2022-01-05 18:57:19.721 ServerApp] nbclassic | extension was successfully linked.
> [W 2022-01-05 18:57:19.729 ServerApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
> [I 2022-01-05 18:57:19.732 ServerApp] nbclassic | extension was successfully loaded.
> [I 2022-01-05 18:57:19.732 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
> [I 2022-01-05 18:57:19.732 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
> [I 2022-01-05 18:57:19.734 ServerApp] jupyterlab | extension was successfully loaded.
> [I 2022-01-05 18:57:19.735 ServerApp] Serving notebooks from local directory: /home
> [I 2022-01-05 18:57:19.735 ServerApp] Jupyter Server 1.13.1 is running at:
> [I 2022-01-05 18:57:19.735 ServerApp] http://62e0ae889ef2:8888/lab
> [I 2022-01-05 18:57:19.735 ServerApp]  or http://127.0.0.1:8888/lab
> [I 2022-01-05 18:57:19.735 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

What should I do?

**Comment by rayrui312** [comment]
I think it is your private token, which we do not set. Have you tried to follow the instructions? (Enter the command 'jupyter notebook list' to get the token).

**Comment by lcavalie** [comment]
This is not a FinRL bug. the token is generated when you start the jupyter notebook and it's specific to your system.
To retrieve it if you don't know what it is you just need to type in any terminal window
$ jupyter notebook list
You will see a list of currently running servers and the associated token
