### ISSUE TITLE
Requirement stockstats >=0.4.0

### ISSUE THREAD

**Issue by M-Colley** [AI4Finance-Foundation/FinRL#415]
Hey, 

please update the requirements of stockstats to

_stockstats>=0.4.0_

to avoid issues from using inconsistencies with the int_date package (in version 0.2 it misses the function **get_date_from_diff** --> became from_diff) causing breaks of the colab notebooks (see #409).

Kind regards and thanks!

**Comment by rayrui312** [comment]
Thanks for pointing it out. We have updated it.
