### ISSUE TITLE
Issue in the FinRL_StockTrading_Fundamental.ipynb file

### ISSUE THREAD

**Issue by skhonsha** [AI4Finance-Foundation/FinRL#417]
I think the merge on two dfs bellow must be "right" join, I test on df rows and the "right" join is correct
`# Merge stock price data and ratios into one dataframe

`processed_full = pd.DataFrame(combination,columns=["date","tic"]).merge(df,on=["date","tic"],how="left")`

and the row filling metho in this line must be "ffill", I test on EPS data in detail.
`# Backfill the ratio data to make them daily

`processed_full = processed_full.bfill(axis='rows')`

**Comment by Burntt** [comment]
You could make a pull request for this if you have the corrected code.
