### ISSUE TITLE
FinRL_PaperTrading_Demo.ipynb breaks on Ubuntu on Windows

### ISSUE THREAD

**Issue by marcipops** [AI4Finance-Foundation/FinRL#420]
Managed to install FinRL on Ubuntu on Windows as per installation instructions https://ai4finance.medium.com/finrl-for-quantitative-finance-install-and-setup-tutorial-for-beginners-1db80ad39159 - and after running two additional commands as identified in issue: Install and Setup Tutorial for Beginners breaks (Windows 10) #419 (https://github.com/AI4Finance-Foundation/FinRL/issues/419)

Ran FinRL_PaperTrading_Demo.ipynb and but failed in "Part 1: Install FinRL" within section "Import related modules"

from finrl.train import train
from finrl.test import test
from finrl.apps.config import DOW_30_TICKER
from finrl.apps.config import TECHNICAL_INDICATORS_LIST
from finrl.finrl_meta.env_stock_trading.env_stocktrading_np import StockTradingEnv
from finrl.finrl_meta.env_stock_trading.env_stock_papertrading import AlpacaPaperTrading
from finrl.finrl_meta.data_processor import DataProcessor
from finrl.plot import backtest_stats, backtest_plot, get_daily_return, get_baseline

import numpy as np
import pandas as pd
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_1061/160074372.py in <module>
----> 1 from finrl.train import train
      2 from finrl.test import test
      3 from finrl.apps.config import DOW_30_TICKER
      4 from finrl.apps.config import TECHNICAL_INDICATORS_LIST
      5 from finrl.finrl_meta.env_stock_trading.env_stocktrading_np import StockTradingEnv

~/FinRL/finrl/train.py in <module>
      1 import ray
      2 from finrl.drl_agents.elegantrl.models import DRLAgent as DRLAgent_erl
----> 3 from finrl.drl_agents.rllib.models import DRLAgent as DRLAgent_rllib
      4 from finrl.drl_agents.stablebaselines3.models import DRLAgent as DRLAgent_sb3
      5 from finrl.finrl_meta.data_processor import DataProcessor

~/FinRL/finrl/drl_agents/rllib/models.py in <module>
      1 # DRL models from RLlib
      2 import ray
----> 3 from ray.rllib.agents.a3c import a2c
      4 from ray.rllib.agents.ddpg import ddpg, td3
      5 from ray.rllib.agents.ppo import ppo

~/anaconda3/lib/python3.9/site-packages/ray/rllib/__init__.py in <module>
      3 # Note: do not introduce unnecessary library dependencies here, e.g. gym.
      4 # This file is imported from the tune module in order to register RLlib agents.
----> 5 from ray.rllib.env.base_env import BaseEnv
      6 from ray.rllib.env.external_env import ExternalEnv
      7 from ray.rllib.env.multi_agent_env import MultiAgentEnv

~/anaconda3/lib/python3.9/site-packages/ray/rllib/env/__init__.py in <module>
----> 1 from ray.rllib.env.base_env import BaseEnv
      2 from ray.rllib.env.env_context import EnvContext
      3 from ray.rllib.env.external_env import ExternalEnv
      4 from ray.rllib.env.external_multi_agent_env import ExternalMultiAgentEnv
      5 from ray.rllib.env.multi_agent_env import MultiAgentEnv

~/anaconda3/lib/python3.9/site-packages/ray/rllib/env/base_env.py in <module>
      2 
      3 import ray
----> 4 from ray.rllib.env.external_env import ExternalEnv
      5 from ray.rllib.env.external_multi_agent_env import ExternalMultiAgentEnv
      6 from ray.rllib.env.multi_agent_env import MultiAgentEnv

~/anaconda3/lib/python3.9/site-packages/ray/rllib/env/external_env.py in <module>
      5 from typing import Optional
      6 
----> 7 from ray.rllib.utils.annotations import PublicAPI
      8 from ray.rllib.utils.typing import EnvActionType, EnvObsType, EnvInfoDict
      9 

~/anaconda3/lib/python3.9/site-packages/ray/rllib/utils/__init__.py in <module>
      7 from ray.rllib.utils.filter_manager import FilterManager
      8 from ray.rllib.utils.filter import Filter
----> 9 from ray.rllib.utils.numpy import sigmoid, softmax, relu, one_hot, fc, lstm, \
     10     SMALL_NUMBER, LARGE_INTEGER, MIN_LOG_NN_OUTPUT, MAX_LOG_NN_OUTPUT
     11 from ray.rllib.utils.schedules import LinearSchedule, PiecewiseSchedule, \

~/anaconda3/lib/python3.9/site-packages/ray/rllib/utils/numpy.py in <module>
      1 import numpy as np
----> 2 import tree  # pip install dm_tree
      3 from typing import List, Optional
      4 
      5 from ray.rllib.utils.deprecation import DEPRECATED_VALUE, deprecation_warning

ModuleNotFoundError: No module named 'tree'

**Comment by don-mao** [comment]
----> 2 import tree # pip install dm_tree

so you should pip install dm_tree

**Comment by don-mao** [comment]
I am a few steps after and i get this error on training.
 

```
     ...\FinRL\finrl\train.py
     
     68         model, model_config = agent_rllib.get_model(model_name)
     69 
---> 70         model_config["lr"] = rllib_params["lr"]
     71         model_config["train_batch_size"] = rllib_params["train_batch_size"]
     72         model_config["gamma"] = rllib_params["gamma"]

TypeError: 'NoneType' object is not subscriptable
```

**Comment by don-mao** [comment]
and with elegantrl i get this error...

```
elegantrl\train\utils.py in update_buffer(traj_list)
     70             steps_r_exp_list = list()
     71             for ten_state, ten_other in traj_list:
---> 72                 buffer.extend_buffer(ten_state, ten_other)
     73 
     74                 steps_r_exp_list.append(get_step_r_exp(ten_reward=ten_other[:, 0]))

AttributeError: 'ReplayBufferMP' object has no attribute 'extend_buffer'
```

**Comment by boyblinky** [comment]
I had the same issue. In the Ubuntu command line window, I manually installed tree to get past this issue. On the first line of the notebook, I added 

!pip install dm-tree

as a step before 

## install finrl library
!pip install git+https://github.com/AI4Finance-LLC/FinRL-Library.git

**Comment by marcipops** [comment]
Thanks boyblinky.  Have done that and replaced drl_lib=elegantrl with drl_lib=stable_baselines3 on advice from Jingyang Rui, as they are working on fixing elegantrl right now.

Reran notebook and it breaks at:  Section: Get cumulative return
df_erl, cumu_erl = alpaca_history(key=API_KEY, 
                                  secret=API_SECRET, 
                                  url=APCA_API_BASE_URL, 
                                  start='2021-10-19', #must be within 1 month
                                  end='2021-10-22') #change the date if error occurs

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~/anaconda3/lib/python3.9/site-packages/alpaca_trade_api/rest.py in _one_request(self, method, url, opts, retry)
    159         try:
--> 160             resp.raise_for_status()
    161         except HTTPError as http_error:

~/anaconda3/lib/python3.9/site-packages/requests/models.py in raise_for_status(self)
    952         if http_error_msg:
--> 953             raise HTTPError(http_error_msg, response=self)
    954 

HTTPError: 422 Client Error: Unprocessable Entity for url: https://paper-api.alpaca.markets/v2/account/portfolio/history?date_start=2021-10-19&timeframe=5Min

During handling of the above exception, another exception occurred:

APIError                                  Traceback (most recent call last)
/tmp/ipykernel_347/245586766.py in <module>
----> 1 df_erl, cumu_erl = alpaca_history(key=API_KEY, 
      2                                   secret=API_SECRET,
      3                                   url=APCA_API_BASE_URL,
      4                                   start='2021-10-19', #must be within 1 month
      5                                   end='2021-10-22') #change the date if error occurs

/tmp/ipykernel_347/706800812.py in alpaca_history(key, secret, url, start, end)
     14     df = pd.DataFrame()
     15     for day in trading_days:
---> 16         df = df.append(api.get_portfolio_history(date_start = day,timeframe='5Min').df.iloc[:78])
     17     equities = df.equity.values
     18     cumu_returns = equities/equities[0]

~/anaconda3/lib/python3.9/site-packages/alpaca_trade_api/rest.py in get_portfolio_history(self, date_start, date_end, period, timeframe, extended_hours)
    843         if extended_hours is not None:
    844             params['extended_hours'] = extended_hours
--> 845         resp = self.get('/account/portfolio/history', data=params)
    846         return self.response_wrapper(resp, PortfolioHistory)
    847 

~/anaconda3/lib/python3.9/site-packages/alpaca_trade_api/rest.py in get(self, path, data)
    174 
    175     def get(self, path, data=None):
--> 176         return self._request('GET', path, data)
    177 
    178     def post(self, path, data=None):

~/anaconda3/lib/python3.9/site-packages/alpaca_trade_api/rest.py in _request(self, method, path, data, base_url, api_version)
    137         while retry >= 0:
    138             try:
--> 139                 return self._one_request(method, url, opts, retry)
    140             except RetryException:
    141                 retry_wait = self._retry_wait

~/anaconda3/lib/python3.9/site-packages/alpaca_trade_api/rest.py in _one_request(self, method, url, opts, retry)
    166                 error = resp.json()
    167                 if 'code' in error:
--> 168                     raise APIError(error, http_error)
    169             else:
    170                 raise

APIError: invalid timeframe provided: 5Min. Valid timeframe for days > 30 is 1D

**Comment by marcipops** [comment]
I will try changing dates, even though the stock notebook really needs to work out of the box for newcomers like me

**Comment by marcipops** [comment]
Related to advice on issue #423, I have completely reinstalled from with Python 3.8 but still fails to run Test section.

These are exactly the steps I took from when it failed above and after your advice to create an environment for python 3.8
Followed https://ai4finance.medium.com/finrl-for-quantitative-finance-install-and-setup-tutorial-for-beginners-1db80ad39159 and selected Windows/Ubuntu option.

After Anaconda installed then:
conda create -n FinRL python=3.8
conda activate FinRL
conda install -c conda-forge jupyterlab
sudo apt-get update && sudo apt-get install cmake libopenmpi-dev python3-dev zlib1g-dev libgl1-mesa-glx
pip install git+https://github.com/AI4Finance-
git clone https://github.com/AI4Finance-
sudo apt install swig gcc
sudo apt-get update
sudo apt-get install --reinstall build-essential
jupyter notebook
Ran FinRL_PaperTrading.pynb

Error is below ....
Test
In [20]:
account_value_erl=test(start_date = TEST_START_DATE,
end_date = TEST_END_DATE,
#account_value_erl=test(start_date = '2021-10-18', #MH updated

end_date = '2021-10-19', #MH updated
                  ticker_list = ticker_list, 
                  data_source = 'alpaca',
                  time_interval= '1Min', 
                  technical_indicator_list= TECHNICAL_INDICATORS_LIST,
                  drl_lib = DRL_LIB, #MH added
drl_lib='elegantrl',
                  env=env, 
                  model_name='ppo', 
                  API_KEY = API_KEY, 
                  API_SECRET = API_SECRET, 
                  APCA_API_BASE_URL = APCA_API_BASE_URL,
                  cwd='./papertrading_erl',
                  net_dimension = 512)
Alpaca successfully connected
Data before 2022-01-08T15:59:00-05:00 is successfully fetched
Data before 2022-01-09T15:59:00-05:00 is successfully fetched
Data clean finished!
KeyError Traceback (most recent call last)
in
----> 1 account_value_erl=test(start_date = TEST_START_DATE,
2 end_date = TEST_END_DATE,
3 #account_value_erl=test(start_date = '2021-10-18', #MH updated
4 # end_date = '2021-10-19', #MH updated
5 ticker_list = ticker_list,

~/anaconda3/envs/FinRL/lib/python3.8/site-packages/finrl/test.py in test(start_date, end_date, ticker_list, data_source, time_interval, technical_indicator_list, drl_lib, env, model_name, if_vix, **kwargs)
36 data = DP.download_data(ticker_list, start_date, end_date, time_interval)
37 data = DP.clean_data(data)
---> 38 data = DP.add_technical_indicator(data, technical_indicator_list)
39
40 if if_vix:

~/anaconda3/envs/FinRL/lib/python3.8/site-packages/finrl/finrl_meta/data_processor.py in add_technical_indicator(self, df, tech_indicator_list)
48 def add_technical_indicator(self, df, tech_indicator_list) -> pd.DataFrame:
49 self.tech_indicator_list = tech_indicator_list
---> 50 df = self.processor.add_technical_indicator(df, tech_indicator_list)
51
52 return df

~/anaconda3/envs/FinRL/lib/python3.8/site-packages/finrl/finrl_meta/data_processors/processor_alpaca.py in add_technical_indicator(self, df, tech_indicator_list)
135 df = df.rename(columns={"time": "date"})
136 df = df.copy()
--> 137 df = df.sort_values(by=["tic", "date"])
138 stock = Sdf.retype(df.copy())
139 unique_ticker = stock.tic.unique()

~/anaconda3/envs/FinRL/lib/python3.8/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
309 stacklevel=stacklevel,
310 )
--> 311 return func(*args, **kwargs)
312
313 return wrapper

~/anaconda3/envs/FinRL/lib/python3.8/site-packages/pandas/core/frame.py in sort_values(self, by, axis, ascending, inplace, kind, na_position, ignore_index, key)
6240 if len(by) > 1:
6241
-> 6242 keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
6243
6244 # need to rewrap columns in Series to apply key function

~/anaconda3/envs/FinRL/lib/python3.8/site-packages/pandas/core/frame.py in (.0)
6240 if len(by) > 1:
6241
-> 6242 keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
6243
6244 # need to rewrap columns in Series to apply key function

~/anaconda3/envs/FinRL/lib/python3.8/site-packages/pandas/core/generic.py in _get_label_or_level_values(self, key, axis)
1777 values = self.axes[axis].get_level_values(key)._values
1778 else:
-> 1779 raise KeyError(key)
1780
1781 # Check for duplicates

KeyError: 'tic'
