### ISSUE TITLE
Demo_MultiCrypto_Trading.ipynb breaks in Colab

### ISSUE THREAD

**Issue by marcipops** [AI4Finance-Foundation/FinRL#421]
'Demo_MultiCrypto_Trading.ipynb' in Colab stopped with this error:

Section 'Training'

train(start_date = TRAIN_START_DATE, 
      end_date = TRAIN_END_DATE,
      ticker_list = TICKER_LIST, 
      data_source = 'binance',
      time_interval= '5m', 
      technical_indicator_list= TECHNICAL_INDICATORS_LIST,
      drl_lib='elegantrl', 
      env=env, 
      model_name='ppo', 
      current_working_dir='./test_ppo',
      erl_params=ERL_PARAMS,
      break_step=5e4,
      if_vix=False
      )

Binance successfully connected
Succesfully add technical indicators
| Arguments Remove cwd: ./test_ppo
################################################################################
ID     Step    maxR |    avgR   stdR   avgS  stdS |    expR   objC   etc.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-29348b501caa> in <module>()
     11       erl_params=ERL_PARAMS,
     12       break_step=5e4,
---> 13       if_vix=False
     14       )
4 frames
/usr/local/lib/python3.7/dist-packages/elegantrl/agents/AgentPPO.py
 in get_reward_sum_raw(self, buf_len, buf_reward, buf_mask, buf_value)
    237         pre_r_sum = 0
    238         for i in range(buf_len - 1, -1, -1):
--> 239             buf_r_sum[i] = buf_reward[i] + buf_mask[i] * pre_r_sum
    240             pre_r_sum = buf_r_sum[i]
    241         buf_adv_v = buf_r_sum - buf_value[:, 0]
IndexError: index 8641 is out of bounds for dimension 0 with size 1

**Comment by rayrui312** [comment]
Thanks for reporting it. It is caused by ElegantRL. We are fixing it.

**Comment by rayrui312** [comment]
It is updated now. You may have a try.
