### ISSUE TITLE
High-level code to use GPU in notebook?

### ISSUE THREAD

**Issue by don-mao** [AI4Finance-Foundation/FinRL#424]
As I am trying to speed up training, I found that it is possible to chose GPU or CPU on many algorithms. 

I can't find a proper documentation or example and I cant find in the code where this device activation happens.

Any suggestion or documentation?

Cheers

**Comment by rayrui312** [comment]
I think the default setting is using GPU (if available). You may check it using Colab by switching the runtime type to GPU.

**Comment by don-mao** [comment]
Oh ok. I've been monitoring the gpu from terminal and other tools and it wasnt using it. Just realized some algo do use gpu some others not.

**Comment by XiaoYangLiu-FinRL** [comment]
We are actively supporting GPU using ElegantRL: https://github.com/AI4Finance-Foundation/ElegantRL
