### ISSUE TITLE
Wiki Leaderboard

### ISSUE THREAD

**Issue by zappavignandrea** [AI4Finance-Foundation/FinRL#428]
Good day everyone,
I was wondering if it could be of interest to open a wiki Leaderboard page in a similar fashion to https://github.com/openai/gym/wiki/Leaderboard, this is only a suggestion.

**Comment by XiaoYangLiu-FinRL** [comment]
It is very good, would like to help me with that?

**Comment by zappavignandrea** [comment]
Of course, I can help

**Comment by XiaoYangLiu-FinRL** [comment]
I set it. Can you edit now?

**Comment by zappavignandrea** [comment]
Published a first draft @ https://github.com/AI4Finance-Foundation/FinRL/wiki/Leaderboard
Feel free to modify where necessary. I was thinking to include a test notebook to simplify testing since there are so many settings for each environment, instead of the long bullet list.

**Comment by Athe-kunal** [comment]
In my opinion, it would be better if we had the leaderboard for stock market trading environments here and other environments in the [ElegantRL ](https://github.com/AI4Finance-Foundation/ElegantRL) repo.

**Comment by zappavignandrea** [comment]
@Athe-kunal absolutely I agree, only FinRL environments should be allowed in the leaderboards. Namely all stock trading variants, crypto trading and portfolio allocation will be recorded.

**Comment by XiaoYangLiu-FinRL** [comment]
Hi, is there any good way to encourage updates of good results?  I mean we are interested in providing a benchmark performance to our community members.

**Comment by zappavignandrea** [comment]
I'm very busy right now improving my own submission, hopefully I will be able to publish results in a couple of weeks. You could also add your own benchmarks like the [ensemble agent](https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_Ensemble_StockTrading_ICAIF_2020.ipynb)
