### ISSUE TITLE
QUANTCONNECT DRL deployment

### ISSUE THREAD

**Issue by matti410** [AI4Finance-Foundation/FinRL#429]
Hi, 
has anyone implemented a FinRL model in Quantconnect/Binance platform?
If already done, could someone share the framework please? 
Thanks

**Comment by XiaoYangLiu-FinRL** [comment]
For binance, pls check here: https://github.com/AI4Finance-Foundation/FinRL-Meta/tree/master/finrl_meta/data_processors
