### ISSUE TITLE
Collab link for "FinRL for Quantitative Finance: Tutorial for Multiple Stock Trading" is broken

### ISSUE THREAD

**Issue by rohita77** [AI4Finance-Foundation/FinRL#430]
Collab link for "FinRL for Quantitative Finance: Tutorial for Multiple Stock Trading" is broken
https://github.com/AI4Finance-LLC/FinRL-Library/blob/master/FinRL_multiple_stock_trading.ipynb

**Comment by BruceYanghy** [comment]
Thanks, it's fixed. We've been doing some code refactoring to keep the library clean.

**Comment by rohita77** [comment]
Can share the new link?

**Comment by BruceYanghy** [comment]
> Can share the new link?

https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_StockTrading_NeurIPS_2018.ipynb
