### ISSUE TITLE
FinRL_Ensemble_StockTrading_ICAIF_2020 Error with DAX Data

### ISSUE THREAD

**Issue by Kartolon** [AI4Finance-Foundation/FinRL#431]
Hello,

I just changed the DOW30 Data to DAX data in the FinRL_Ensemble_StockTrading_ICAIF_2020 file.

`df = YahooDownloader(start_date = '2009-01-01',
                     end_date = '2021-07-06',
                     ticker_list = config.DAX_30_TICKER).fetch_data()`

However, I then receive an error when running the code. When running the code cell

`df_summary = ensemble_agent.run_ensemble_strategy(A2C_model_kwargs,
                                                 PPO_model_kwargs,
                                                 DDPG_model_kwargs,
                                                 timesteps_dict)`

I receive the error

`ValueError: Expected parameter loc (Tensor of shape (1, 27)) of distribution Normal(loc: torch.Size([1, 27]), scale: torch.Size([1, 27])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan]])`

When using DOW30 data, the code runs properly.

Thank you in advance for any help.

**Comment by rayrui312** [comment]
This is usually caused by NaN or inf values in the datasets. You may try to replace the NaN values or inf values in the final datasets with 0 like this:
`processed_full = processed_full.fillna(0)`
`processed_full = processed_full.replace(np.inf,0)`

**Comment by Kartolon** [comment]
Thank you for your response! I already tried that, my preprocessing looks like that:

`fe = FeatureEngineer(
                    use_technical_indicator=True,
                    tech_indicator_list = tech_indicators,
                    use_turbulence=True,
                    user_defined_feature = True,
                    use_vix = True)

processed = fe.preprocess_data(df)
processed = processed.copy()
processed = processed.fillna(0)
processed = processed.replace(np.inf,0)`

However, the error stills occurs.

**Comment by XelHaku** [comment]
Probably one of the tickers is not giving you data. I recommend to download
the data and inspect it. Then remove or replace the faulty ticker.

It's a guess. I happend to me often when adding my own tickers

**Comment by Kartolon** [comment]
Thank you for your input. I had a closer look at the data, but I could not find any fauly entries or missing values. I also plotted all of them individually and it looked all fine to me.

**Comment by richardhuo** [comment]
It works. 之前我使用A股的000100就是有同样的错误，今天对full processed data进行操作后已经可以运行了。

**Comment by richardhuo** [comment]
need to do the same to value like -inf, so the complete fix shall be:
processed_full = processed_full.fillna(0)
processed_full = processed_full.replace(np.inf,0)
processed_full = processed_full.replace(-np.inf,0)
