### ISSUE TITLE
Why these results?

### ISSUE THREAD

**Issue by ghaffari903** [AI4Finance-Foundation/FinRL#434]
==============Get Backtest Results===========
Annual return          2.472023e+41
Cumulative returns     3.521431e+19
Annual volatility      4.801511e+16
Sharpe ratio           1.461367e+00
Calmar ratio           1.647381e+41
Stability                       NaN
Max drawdown          -1.500577e+00
Omega ratio            7.059300e+14
Sortino ratio          2.162858e+15
Skew                            NaN
Kurtosis                        NaN
Tail ratio             2.249360e+00
Daily value at risk   -5.770892e+15
dtype: float64

`account_value_erl.tail()`

	date	account_value
114	2021-12-25	3.071313e+25
115	2021-12-26	3.075764e+25
116	2021-12-27	3.473762e+25
117	2021-12-28	3.509064e+25
118	2021-12-29	3.521431e+25

please help me, what's wrong?

**Comment by Satvik-web** [comment]
hi @ghaffari903 could you pls mention if the code is for mysql or what command are you trying to run

**Comment by ghaffari903** [comment]
FinRL_Compare_ElegantRL_RLlib_Stablebaseline3.ipynb

**Comment by Athe-kunal** [comment]
@ghaffari903 Can you explain a bit more, what is wrong with the results?

**Comment by ghaffari903** [comment]
@Athe-kunal 
2.472023e+41 is very high for 1m$  in one year!

**Comment by XiaoYangLiu-FinRL** [comment]
Is there any information value in the data that make the calculation wring?
