### ISSUE TITLE
Easiest way to add user specific features in Ensemble FinRL_Ensemble_StockTrading_ICAIF_2020

### ISSUE THREAD

**Issue by Kartolon** [AI4Finance-Foundation/FinRL#435]
Hello,

I was wondering what is the easiest way to add user specific features in the Ensemble Stock Trading method. Lets say I add some of my own features to the data frame. For example, lets say use the FeatureEngineer, to additional add the VIX to the data. What would I have to change to use it for training and trading? 
The only easy way I can think of right now to use the VIX as additional feature would be to add it to the list of technical indicators. Then it would be part of the definition of the environment and would be considered when performing the trading. However, it would then be basically added 30 times (cause technical indicators are used for each stock), so it would not really make sense. Is there a clean and easy way to do that?
And as an additional question: if I wanted to use the VIX as risk measurement (instead of the turbolence index) how would I do that? I already tried to add risk_indicator_col="turbulence" as additional paramenter in my environment arguments meaning 

`env_kwargs = {
    "hmax": 100, 
    "initial_amount": 1000000, 
    "buy_cost_pct": 0.001, 
    "sell_cost_pct": 0.001, 
    "state_space": state_space, 
    "stock_dim": stock_dimension, 
    "tech_indicator_list": tech_indicators,
    "action_space": stock_dimension, 
    "reward_scaling": 1e-4,
    "print_verbosity":5,
    "risk_indicator_col":"vix"
}` , however that does not work because the class DRLEnsembleAgent does not have an argument "risk_indicator_col" in it.

Thank you in advance for any help.

**Comment by skhonsha** [comment]
@Kartolon  did you solved https://github.com/AI4Finance-Foundation/FinRL/issues/431 ERROR?
please help me on the same error
thanks

**Comment by Kartolon** [comment]
Unfortunately, I also have no solved issue #431 yet

**Comment by ghaffari903** [comment]
> Thanks for the input. In this resource they basically also add the additional feature for each stock to the technical indicator list. I am wondering how I can add a feature that is not specific to a stock. For example, how to add the VIX as one additional variable

add_VIX function is implemened
https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/finrl_meta/data_processors/processor_yahoofinance.py

def add_vix(self, data):
        """
        add vix from yahoo finance
        :param data: (df) pandas dataframe
        :return: (df) pandas dataframe
        """
        df = data.copy()
        df_vix = self.download_data(
            start_date=df.time.min(),
            end_date=df.time.max(),
            ticker_list=["^VIX"],
            time_interval=self.time_interval,
        )
        df_vix = self.clean_data(df_vix)
        vix = df_vix[["time", "adjcp"]]
        vix.columns = ["time", "vix"]

        df = df.merge(vix, on="time")
        df = df.sort_values(["time", "tic"]).reset_index(drop=True)
        return df

**Comment by Kartolon** [comment]
Thats true, but this function does only add the VIX to the dataframe. It is still not considered in training or testing later on. My question is: how do I use an additional feature (like for example VIX) in training and testing.

**Comment by ghaffari903** [comment]
> 

def get_train_env(start_date, end_date, ticker_list, data_source, time_interval,model_name,env,
          info_col, **if_vix=True**,
          **kwargs):

    DP = Custom_DataProcessor(data_source, **kwargs)
    DP.download_data(ticker_list, start_date, end_date, time_interval)
    DP.clean_data()
    DP.add_user_defined_features(user_df) #Adding Google trends data to our state space
    DP.add_technical_indicator(technical_indicator_list)
    if if_vix:
        DP.add_vix()
    # Passed info col instead of tech_indicator_list.
    price_array, tech_array, turbulence_array = DP.df_to_array(
        data,info_col, if_vix)
    env_config = {'price_array':price_array,
              'tech_array':tech_array,
              'turbulence_array':turbulence_array,
              'if_train':True}
    env_instance = env(config=env_config)
    

    return env_instance

**Comment by Kartolon** [comment]
Thanks for your response! You are refering to the code of the Demo_FinRL_Meta_Integrate_Trends_data_to_DOW_Jones.ipynb right? Is it possible to use the VIX as risk_indicator in the Ensemble Strategy aswell (FinRL_Ensemble_StockTrading_ICAIF_2020)? Because in the models.py there is not any code refering to the VIX, so I am not sure how I can use it there.

Thank you!

**Comment by ghaffari903** [comment]
I didn't check now, but I guess it is possible

**Comment by Kartolon** [comment]
Update: I now tried to add stock specific features to the ensemble method using the method I described above. I added 2 additional features to the dataframe and then added the column names to the technical_indicators list. Unfortunately, this didnt work. I got the following error:

`\FinRL\finrl\finrl_meta\env_stock_trading\env_stocktrading.py in <listcomp>(.0)
    368                     + sum(
    369                         [
--> 370                             self.data[tech].values.tolist()
    371                             for tech in self.tech_indicator_list
    372                         ],

~\anaconda3\envs\bda\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   3456             if self.columns.nlevels > 1:
   3457                 return self._getitem_multilevel(key)
-> 3458             indexer = self.columns.get_loc(key)
   3459             if is_integer(indexer):
   3460                 indexer = [indexer]

~\anaconda3\envs\bda\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 'trends'`

"trends" is the column name of one of my additional features. Thank you in advance for any help!
