### ISSUE TITLE
ImportError: cannot import name 'Arguments' from 'elegantrl.run' (/usr/local/lib/python3.7/dist-packages/elegantrl/run.py)

### ISSUE THREAD

**Issue by skhonsha** [AI4Finance-Foundation/FinRL#437]
from finrl.drl_agents.elegantrl.models import DRLAgent as DRLAgent_erl

**Comment by zhongguojie1998** [comment]
In models.py, line 8:
from elegantrl.run import train_and_evaluate, init_agent

should be modified to:

from elegantrl.run import train_and_evaluate, init_agent
from elegantrl.config import Arguments

**Comment by NicoleRichards1998** [comment]
I'm not sure if a missed something, but I'm getting this error as well when running the FinRL_PaperTrading_Demo in colab even with the change in model.py
![Screen Shot 2022-01-25 at 11 43 30 AM](https://user-images.githubusercontent.com/97527265/150952104-5b7d4cca-4feb-429a-8584-59827532b6de.png)
