### ISSUE TITLE
sharpe ratio

### ISSUE THREAD

**Issue by LeeNamYeong** [AI4Finance-Foundation/FinRL#438]
In the environment, the sharpe ratio is fixed by root 252
However, your test data of period is longer than root 252 and even in your papers.
Then, I think it have to be set by root 337.
Because your test data is 337 days.
My opinion can be wrong.
However, please check for me.

**Comment by Athe-kunal** [comment]
Sharpe ratio is generally calculated annually, so in a year there are 252 trading days hence it is divided by the root of 252. As it is an annual metric, I don't think you can divide it by the number of testing days. If you can please elucidate the reasoning also.
