### ISSUE TITLE
turbulence_threshold in models.py

### ISSUE THREAD

**Issue by Kartolon** [AI4Finance-Foundation/FinRL#443]
Hello,

in the comments in the models.py file it says in lines 396 to 400 that if the mean turbolence of the historical data (I assume its the mean of the validation period, right?) is higher than the 90% quantil of the in-sample turbolence then its assumed that the market is volatile. However, after that in line 409 the turbolence threshold is now set to the 99% quantil not the 90% quantil. Is it supposed to be like that or is that a bug?

Thanks in advance for any help

**Comment by XiaoYangLiu-FinRL** [comment]
It is a bug. Please play it during backtesting period before deployment.

**Comment by Kartolon** [comment]
Thank you for your response. I dont understand completely, what do you mean by "playing" it during backtesting?
Thanks!

**Comment by XiaoYangLiu-FinRL** [comment]
I mean you can choose different values, either 90% or 99%.  It is a hyperparameter, so up to your own choice, depending on your risk-aversion level.  YMYD, lol.
