### ISSUE TITLE
FinRL_PaperTrading_Demo HTTPError on colab notebook

### ISSUE THREAD

**Issue by NicoleRichards1998** [AI4Finance-Foundation/FinRL#448]
Hi, I'm running the FinRL_PaperTrading_Demo.ipynb on colab for the first time (thank you so much for making it btw), but I'm getting an error from Step 2 when trying to download the data from Alpaca.

Here is the error message I'm getting:

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-15-3a2ad2f50099> in <module>()
      2                         end_date = '2021-10-05',
      3                         ticker_list = ticker_list,
----> 4                         time_interval= '1Min')

6 frames
/usr/local/lib/python3.7/dist-packages/requests/models.py in raise_for_status(self)
    958 
    959         if http_error_msg:
--> 960             raise HTTPError(http_error_msg, response=self)
    961 
    962     def close(self):

HTTPError: 403 Client Error: Forbidden for url: https://data.alpaca.markets/v1/bars/1Min?symbols=AXP&limit=500&start=2021-10-01T09%3A30%3A00-04%3A00&end=2021-10-01T15%3A59%3A00-04%3A00

I'll add a screenshot as well for incase that might help:

![Screen Shot 2022-01-25 at 9 41 09 AM](https://user-images.githubusercontent.com/97527265/150932782-ea9bdcaf-48dd-4450-8703-a74dc442232f.png)

Am I missing something? I'm so sorry if its a dumb question, I'm new

**Comment by rayrui312** [comment]
This error is usually caused by the Alpaca side. Have you activated your alpaca paper trading account and replaced the API_KEY and API_SECRET with yours?

**Comment by NicoleRichards1998** [comment]
Ooh I understand now. Sorry it really was a dumb question. It works now, thank you for your time!
