### ISSUE TITLE
Using VIX instead of the turbulence index in the FinRL_Ensemble_StockTrading_ICAIF_2020 model as risk indicator

### ISSUE THREAD

**Issue by Kartolon** [AI4Finance-Foundation/FinRL#451]
Hello,

how can I use the VIX as risk indicator during training and trading in the ensemble strategy. I already added it to the dataframe, but I am not sure what exactly I have to change so it is taken into account as risk indicator during training and testing. Also, I am not sure how the respective treshhold is set or whether that is set automatically by a certain quantil of the past distribution.

Thank you in advance for any help!

**Comment by XiaoYangLiu-FinRL** [comment]
Vix is a good choice!

**Comment by Kartolon** [comment]
Yes, I think so too, but how exactly can I implement it so it is considered in training and trading? My only idea is too just keep replace the values in the "turbulence" column in the dataframe with the VIX values while keeping the column names the same

**Comment by XiaoYangLiu-FinRL** [comment]
I think using Vix to replace turbulence index is a good way. We also tested it.  You can do more survey to find the best way.
