### ISSUE TITLE
Having a look at trades of ensemble strategy and of trades of individual agents of the ensemble strategy

### ISSUE THREAD

**Issue by Kartolon** [AI4Finance-Foundation/FinRL#452]
Hello,

how exactly can I have a look at the trades that the ensemble strategy (FinRL_Ensemble_StockTrading_ICAIF_2020 model) performed respectively how many stocks the agent is holding at each time point? Also, is it possible to see the returns of the individuals agents (PPO, A2C, DDPG) for the ensemble strategy?

Thank you in advance for any help!

**Comment by Athe-kunal** [comment]
Hi @Kartolon 
Please refer [here](https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/drl_agents/stablebaselines3/models.py#L304). You can save the action in a list and return in the DRL_prediction function to collect the actions for the given algorithm
