### ISSUE TITLE
Question abont "FinRL_PortfolioAllocation_NeurIPS_2020"

### ISSUE THREAD

**Issue by Aurorazqq** [AI4Finance-Foundation/FinRL#455]
Hello. I am a new student of deep reinforcement learning, and I am studying your article(FinRL_PortfolioAllocation_NeurIPS_2020)for the needs of my course. But I have some problems, I really have no way, so I ask you for advice. First, I can't get stock data through Yahoo Finance. See chart for the problem.
![image](https://user-images.githubusercontent.com/98687210/151696635-f803e353-19cc-44cd-9a60-c7eb1c5233e4.png)
![image](https://user-images.githubusercontent.com/98687210/151696637-f1357ab8-f71e-4228-a33c-c89a4483a4a7.png)
Second, I can only get data from Tushare for a few years (set to get data from January 1, 2009 to October 31, 2021.31, but only get data from July 31, 2019.7-december 31, 2021.12.31). I have baidu search for both of these problems but have not found a good solution.
![image](https://user-images.githubusercontent.com/98687210/151696650-6cd759af-98a6-4341-b364-5b87c40f4895.png)
![image](https://user-images.githubusercontent.com/98687210/151696652-533e3b18-4ce0-454c-bad7-0df0598fbaf2.png)
The third and most fatal problem is that I only used the SSE_50_TICKER tushare obtained from July 31, 2019.7-december 31, 2021.12.31 for training, but there were no good results in several models, and the sharpe rate was even negative. I understand that different stocks and in different years may have different effects. I wonder if you have any suggestions to make the model better in domestic stock training results (at least not lose money investing).
![image](https://user-images.githubusercontent.com/98687210/151696662-331b16b4-23c9-4de1-8a3d-130ba452a376.png)
![image](https://user-images.githubusercontent.com/98687210/151696663-c9ef95ee-e5fe-4f5a-8f23-886db34610e8.png)
Because I am not professional enough, some of the statements may not be accurate, I hope you can forgive me. If you are free, I hope you can answer my questions, especially the second and third questions. Thank you very much!!!

**Comment by XiaoYangLiu-FinRL** [comment]
In China, how about trying this code: https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/Demo_China_A_share_market.ipynb

**Comment by Aurorazqq** [comment]
> In China, how about trying this code: https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/Demo_China_A_share_market.ipynb
Thank you very much for your advice. I'll have a try!!!
