### ISSUE TITLE
Question about interpretability of the DRL 

### ISSUE THREAD

**Issue by evril7490** [AI4Finance-Foundation/FinRL#456]
Hi,

It was really nice to see a framework for DRL in trading, I was wondering if it is possible to provide more interpretability for the model output? For example, if we have some technical indicators and some company balance sheet data as input to our model, and each day the model produce some trading decisions based on these features and current portfolio positions, is there a way to generate some reasoning behind the decision so that the trader could have a better understanding of the AI's decision? Something like, we want to buy XXX shares of APPL, b/c of these main reasons: 1. 1D return reversal, 2. currently we are long 3. Or similar stocks has a recent upward trend, and APPL is high correlated with them. Not sure if this is already doable or is something that is of interest of the team.

**Comment by XiaoYangLiu-FinRL** [comment]
Thanks very much for your suggestion and sharing.  Interpretability indeed is of great interest to the readers and users. It is also an active research topic.

Would like to read the recent ICAIF 2021 paper: Explainable Deep Reinforcement Learning for Portfolio Management: An Empirical Approach, which can be found at: https://arxiv.org/abs/2111.03995
