### ISSUE TITLE
Is the Sharp Ratio function optimizable for any data?

### ISSUE THREAD

**Issue by ghaffari903** [AI4Finance-Foundation/FinRL#458]
1- Is the Sharp Ratio function optimizable for any data?

2- By what parameter do we increase the number of training episodes (both stable-baselines3 an elegant)?

**Comment by Burntt** [comment]
1. Yes, you can optimize for Sharpe ratio. During hyperparameter tuning, you can have the target to be Sharpe ratio.

2. break_step. This is the variable that determines the total amount of 'steps' in any of the trading environments. For example: if you have a timeseries, hourly with 10.000 points, and you set break_step to 20.000, the full datasets is passed twice.
