### ISSUE TITLE
FinRL_PaperTrading_Demo.ipynb - Alpaca 403 Client Error

### ISSUE THREAD

**Issue by vrangayyan6** [AI4Finance-Foundation/FinRL#460]
in FinRL_PaperTrading_Demo.ipynb, on executing 
```
data = DP.download_data(start_date = '2021-10-01', 
                        end_date = '2021-10-05',
                        ticker_list = ticker_list, 
                        time_interval= '1Min')
```

getting error:
---------------------------------------------------------------------------

HTTPError                                 Traceback (most recent call last)

[<ipython-input-10-4c0e2a4e69e3>](https://localhost:8080/#) in <module>()
      2                         end_date = '2021-10-05',
      3                         ticker_list = ticker_list,
----> 4                         time_interval= '1Min')

6 frames

[/usr/local/lib/python3.7/dist-packages/finrl/finrl_meta/data_processor.py](https://localhost:8080/#) in download_data(self, ticker_list, start_date, end_date, time_interval)
     37             start_date=start_date,
     38             end_date=end_date,
---> 39             time_interval=time_interval,
     40         )
     41         return df

[/usr/local/lib/python3.7/dist-packages/finrl/finrl_meta/data_processors/processor_alpaca.py](https://localhost:8080/#) in download_data(self, ticker_list, start_date, end_date, time_interval)
     35             for tic in ticker_list:
     36                 barset = self.api.get_barset(
---> 37                     [tic], time_interval, start=start_time, end=end_time, limit=500
     38                 ).df[tic]
     39                 barset["tic"] = tic

[/usr/local/lib/python3.7/dist-packages/alpaca_trade_api/rest.py](https://localhost:8080/#) in get_barset(self, symbols, timeframe, limit, start, end, after, until)
    511         if until is not None:
    512             params['until'] = until
--> 513         resp = self.data_get('/bars/{}'.format(timeframe), params)
    514         return self.response_wrapper(resp, BarSet)
    515 

[/usr/local/lib/python3.7/dist-packages/alpaca_trade_api/rest.py](https://localhost:8080/#) in data_get(self, path, data, api_version)
    191         base_url: URL = get_data_url()
    192         return self._request(
--> 193             'GET', path, data, base_url=base_url, api_version=api_version,
    194         )
    195 

[/usr/local/lib/python3.7/dist-packages/alpaca_trade_api/rest.py](https://localhost:8080/#) in _request(self, method, path, data, base_url, api_version)
    137         while retry >= 0:
    138             try:
--> 139                 return self._one_request(method, url, opts, retry)
    140             except RetryException:
    141                 retry_wait = self._retry_wait

[/usr/local/lib/python3.7/dist-packages/alpaca_trade_api/rest.py](https://localhost:8080/#) in _one_request(self, method, url, opts, retry)
    158         resp = self._session.request(method, url, **opts)
    159         try:
--> 160             resp.raise_for_status()
    161         except HTTPError as http_error:
    162             # retry if we hit Rate Limit

[/usr/local/lib/python3.7/dist-packages/requests/models.py](https://localhost:8080/#) in raise_for_status(self)
    958 
    959         if http_error_msg:
--> 960             raise HTTPError(http_error_msg, response=self)
    961 
    962     def close(self):

HTTPError: 403 Client Error: Forbidden for url: https://data.alpaca.markets/v1/bars/1Min?symbols=AXP&limit=500&start=2021-10-01T09%3A30%3A00-04%3A00&end=2021-10-01T15%3A59%3A00-04%3A00

**Comment by Athe-kunal** [comment]
If you are running it now and getting errors, then markets are closed. Try again tomorrow.

**Comment by vrangayyan6** [comment]
I got this error earlier in the day when markets were open.  I had heard that Market Data API v1 endpoints will sunset on March 15, 2022 and will be removed from the Alpaca documentation. After March 15, 2022, systems using v1 endpoints will no longer work.

**Comment by lcavalie** [comment]
You should check what version of the processor_alpaca.py you are using, it may be outdated.
Look into /finrl/finrl_meta/data_processors/processor_alpaca.py
In particular at line 13, you should see that the version of the app used is ‘v2’
The latest alpaca_trade_api uses their v2 api that’s why it’s surprising that you have a call to the old v1 api.

L

**Comment by vrangayyan6** [comment]
Thanks!  I'll update my repo.
