### ISSUE TITLE
Adding Fund Indicator to FinRL_PortfolioAllocation_NeurIPS_2020

### ISSUE THREAD

**Issue by alvaromorales1965** [AI4Finance-Foundation/FinRL#461]
After adding  fundamental indicators and obtaining the train df, I have an issue in:

e_train_gym = StockPortfolioEnv(df = train, **env_kwargs)

ValueError                                Traceback (most recent call last)
[<ipython-input-103-5080f7b41ea0>](https://localhost:8080/#) in <module>()
     11 }
     12 
---> 13 e_train_gym = StockPortfolioEnv(df = train, **env_kwargs)
     14 
     15 

1 frames
<__array_function__ internals> in append(*args, **kwargs)

[/usr/local/lib/python3.7/dist-packages/numpy/lib/function_base.py](https://localhost:8080/#) in append(arr, values, axis)
   4669         values = ravel(values)
   4670         axis = arr.ndim-1
-> 4671     return concatenate((arr, values), axis=axis)
   4672 
   4673 

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: zero-dimensional arrays cannot be concatenated

**Comment by XiaoYangLiu-FinRL** [comment]
Would you like to compare with the following codes: https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_StockTrading_Fundamental.ipynb
