### ISSUE TITLE
One train ElegantRL model different test results

### ISSUE THREAD

**Issue by ghaffari903** [AI4Finance-Foundation/FinRL#467]
The below 20 test trials is done on one trained ElegantRL model!!!! How can we have the best result fixed?

buy 
2 221.0
 buy 
12 1.0
sell
2 221.0
buy 
3 128.0
buy 
7 1.0
buy 
12 1.0
Test Finished!
episode_return 1.8533326059032225
+++++++++++++++++++++++++++++++++++++
buy 
1 155.0
 buy 
12 1.0
buy 
14 1.0
Test Finished!
episode_return 0.5597903215495362
++++++++++++++++++++++++++++++++++++=
buy 
0 62.0
sell 
0 62.0
buy
2 169.0
sell
2 169.0
 buy
4 212.0
 buy 
7 3.0
buy
4 1.0
Test Finished!
episode_return 0.436127923008618
+++++++++++++++++++++++++++++++++++++
buy
0 62.0
Test Finished!
episode_return 0.5453451798521484
+++++++++++++++++++++++++++++++++++++
buy
0 62.0
Test Finished!
episode_return 0.5453451798521484
+++++++++++++++++++++++++++++++++++++
buy
1 155.0
 buy
7 1.0
 buy
12 1.0
Test Finished!
episode_return 0.5643746412783204
+++++++++++++++++++++++++++++++++++++
buy 
1 155.0
 buy
4 2.0
sell
4 2.0
buy
5 2.0
sell
1 155.0
buy 
3 68.0
buy
5 1.0
 buy 
5 1.0
Test Finished!
episode_return 0.9947367225473388
+++++++++++++++++++++++++++++++++++++
buy
1 155.0
sell 
1 155.0
 buy
4 232.0
 buy
9 1.0
Test Finished!
episode_return 0.4702154116675292
+++++++++++++++++++++++++++++++++++++
buy
0 62.0
Test Finished!
episode_return 0.5453451798521484
+++++++++++++++++++++++++++++++++++++
buy 
0 62.0
sell
0 62.0
buy
2 136.0
 buy 
7 1.0
buy
25 1.0
Test Finished!
episode_return 0.36232031050913077
+++++++++++++++++++++++++++++++++++++
buy 
1 155.0
sell
1 155.0
 buy 
2 171.0
Test Finished!
episode_return 0.45341265289399413
+++++++++++++++++++++++++++++++++++++
buy
0 62.0
Test Finished!
episode_return 0.5453451798521484
+++++++++++++++++++++++++++++++++++++
buy
0 62.0
Test Finished!
episode_return 0.5453451798521484
+++++++++++++++++++++++++++++++++++++
buy 
4 234.0
buy
12 1.0
buy 
14 1.0
sell
14 1.0
 buy 
4 1.0
 buy 
4 1.0
Test Finished!
episode_return 0.48104703348134764
+++++++++++++++++++++++++++++++++++++
buy
0 62.0
Test Finished!
episode_return 0.5453451798521484
+++++++++++++++++++++++++++++++++++++
buy
0 62.0
Test Finished!
episode_return 0.5453451798521484
+++++++++++++++++++++++++++++++++++++
buy 
0 62.0
Test Finished!
episode_return 0.5453451798521484
+++++++++++++++++++++++++++++++++++++
buy
0 62.0
Test Finished!
episode_return 0.5453451798521484
+++++++++++++++++++++++++++++++++++++
 buy
1 155.0
buy
4 1.0
Test Finished!
episode_return 0.5703235124550293
+++++++++++++++++++++++++++++++++++++
buy 
2 221.0
Test Finished!
episode_return 0.5883003217143554
+++++++++++++++++++++++++++++++++++++
max episode_return 1.8533326059032225

**Comment by Burntt** [comment]
I recommend for starters trying to apply Optuna hyperparameter tuner. You can copy the best model in the optimization loop from the folder ./test (where the train function saves the model in the standard code).

You could do that by only copying when your episode return is higher than any of the previous trials.

**Comment by ghaffari903** [comment]
Do you test more than once on best trained model? The results again varies

**Comment by zhumingpassional** [comment]
Which model do you used? Some DRL algorithms are stochastic policies, not deterministic, so that the results may be different.
