### ISSUE TITLE
Pyfolio Tear Sheet in PyCharm

### ISSUE THREAD

**Issue by orthosku** [AI4Finance-Foundation/FinRL#469]
Below code in PyCharm doesn't show the tear sheet. Is the only way to view it in Jupyter or Colab?

```
with pyfolio.plotting.plotting_context(font_scale=1.1):
    pyfolio.create_full_tear_sheet(returns = DRL_strat,
                                   benchmark_rets=dow_strat, set_context=False)
```

**Comment by Burntt** [comment]
If I remember correctly, I was having issues with displaying the tear sheet as well. I believe the output is written in HTML and there are methods to display the output in PyCharm, however they are ambiguous.

I would not recommend trying to solve this issue with a HTML display. Instead, find out which metrics are important for your problem and plot them yourself.
