### ISSUE TITLE
Confusion regarding which tutorial is up to date.

### ISSUE THREAD

**Issue by orthosku** [AI4Finance-Foundation/FinRL#470]
Multiple tutorials with some out of date information is making it difficult for a beginner (myself) to understand which is most up to date. Could you let me know where I should look/which one is most recent? I'm just trying to train RL models now; not start paper trading.

**Comment by Athe-kunal** [comment]
Well for just training, you can start with [this](https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_StockTrading_NeurIPS_2018.ipynb)

**Comment by lshnmoptim** [comment]
> Well for just training, you can start with [this](https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_StockTrading_NeurIPS_2018.ipynb)

I tried running the notebook and I couldn't seem to import PyTorch. Here's the screenshot:
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/97660157/154661101-fb4c8a4f-903c-43f4-bfb2-4878643379ad.png">
