### ISSUE TITLE
Unused parameter "time_interval" in YahooFinance Data Processor

### ISSUE THREAD

**Issue by chasepuskar** [AI4Finance-Foundation/FinRL#472]
In file "processor_yahoofinance.py", the call to "yf.download" in the function "download_data" does not make use of the parameter "time_interval". Currently, the code is implemented on line 51 as:

temp_df = yf.download(tic, start=start_date, end=end_date)

While there would need to be some preprocessing to utilize the parameter, I think that this feature should be considered.

I've linked to the yfinance docs.

https://pypi.org/project/yfinance/

**Comment by XiaoYangLiu-FinRL** [comment]
Thanks for pointing it out.  We need some discussion in the team.   Basically, there are tens of data sources, where interval is used (say daily or minute data).  This, this parameter appears here at finance.

**Comment by zhumingpassional** [comment]
Yahoofinance use the default interval 'one day'. In fact, we should assert time_interval to be one day, and the parameter "time_interval" should be removed in yf.download.

**Comment by zhumingpassional** [comment]
We can point out the time interval. The following is the descriptions from the API docs:
        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "1m",

Therefore,  "time_interval" should not be removed.
