### ISSUE TITLE
module 'stable_baselines3.common.logger' has no attribute 'record'

### ISSUE THREAD

**Issue by Tasneem01** [AI4Finance-Foundation/FinRL#473]
While running FinRL_Ensemble_StockTrading_ICAIF_2020.ipynb

I am running the entire code as it is, still getting the following error:

AttributeError: module 'stable_baselines3.common.logger' has no attribute 'record'

AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_1680\3594883500.py in <module>
      2                                                  PPO_model_kwargs,
      3                                                  DDPG_model_kwargs,
----> 4                                                  timesteps_dict)

D:\Mine\Bot\FinRL-Library\finrl\model\models.py in run_ensemble_strategy(self, A2C_model_kwargs, PPO_model_kwargs, DDPG_model_kwargs, timesteps_dict)
    337             print("======A2C Training========")
    338             model_a2c = self.get_model("a2c",self.train_env,policy="MlpPolicy",model_kwargs=A2C_model_kwargs)
--> 339             model_a2c = self.train_model(model_a2c, "a2c", tb_log_name="a2c_{}".format(i), iter_num = i, total_timesteps=timesteps_dict['a2c']) #100_000
    340 
    341             print("======A2C Validation from: ", validation_start_date, "to ",validation_end_date)

D:\Mine\Bot\FinRL-Library\finrl\model\models.py in train_model(model, model_name, tb_log_name, iter_num, total_timesteps)
    161     @staticmethod
    162     def train_model(model, model_name, tb_log_name, iter_num, total_timesteps=5000):
--> 163         model = model.learn(total_timesteps=total_timesteps, tb_log_name=tb_log_name)
    164         model.save(f"{config.TRAINED_MODEL_DIR}/{model_name.upper()}_{total_timesteps//1000}k_{iter_num}")
    165         return model

c:\users\tasne\appdata\local\programs\python\python37\lib\site-packages\stable_baselines3\a2c\a2c.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    198             tb_log_name=tb_log_name,
    199             eval_log_path=eval_log_path,
--> 200             reset_num_timesteps=reset_num_timesteps,
    201         )

c:\users\tasne\appdata\local\programs\python\python37\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    248         while self.num_timesteps < total_timesteps:
    249 
--> 250             continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
    251 
    252             if continue_training is False:

c:\users\tasne\appdata\local\programs\python\python37\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py in collect_rollouts(self, env, callback, rollout_buffer, n_rollout_steps)
    176                 clipped_actions = np.clip(actions, self.action_space.low, self.action_space.high)
    177 
--> 178             new_obs, rewards, dones, infos = env.step(clipped_actions)
    179 
    180             self.num_timesteps += env.num_envs

c:\users\tasne\appdata\local\programs\python\python37\lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py in step(self, actions)
    160         """
    161         self.step_async(actions)
--> 162         return self.step_wait()
    163 
    164     def get_images(self) -> Sequence[np.ndarray]:

c:\users\tasne\appdata\local\programs\python\python37\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py in step_wait(self)
     42         for env_idx in range(self.num_envs):
     43             obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] = self.envs[env_idx].step(
---> 44                 self.actions[env_idx]
     45             )
     46             if self.buf_dones[env_idx]:

D:\Mine\Bot\FinRL-Library\finrl\env\env_stocktrading.py in step(self, actions)
    207                 plt.plot(self.asset_memory,'r')
    208                 plt.savefig('results/account_value_{}_{}_{}.png'.format(self.mode,self.model_name, self.iteration),index=False)
--> 209                 plt.close()
    210 
    211             # Add outputs to logger interface

AttributeError: module 'stable_baselines3.common.logger' has no attribute 'record'

At line:
df_summary = ensemble_agent.run_ensemble_strategy(A2C_model_kwargs,PPO_model_kwargs,DDPG_model_kwargs,timesteps_dict)

I have uninstalled and installed the library with its latest update, even then the error still exists. Anyone knows how to solve this?
Any kind of help will be highly appreciated. 
Thanks

**Comment by Athe-kunal** [comment]
Those lines are commented on in the recent file. But if you want to use them still
It is from stable_baselines3.common.logger import Logger, KVWriter, CSVOutputFormat
I am raising a PR issue for the same fixing it, uncomment them and use it

**Comment by Tasneem01** [comment]
> Those lines are commented on in the recent file. But if you want to use them still It is from stable_baselines3.common.logger import Logger, KVWriter, CSVOutputFormat I am raising a PR issue for the same fixing it, uncomment them and use it. But those loggers are not necessary as all the necessary logging are already done in the results folder


Hello, I tried commenting and uncommenting those lines even then jupyter lab is throwing that attribute error, Also in my site packages-> stable_baseline3 -> base_class.py logger isnt imported as you have given here. And even in the same way the following error is also thrown.  
ImportError: cannot import name 'BackTestStats' from 'finrl.trade.backtest' (D:\Mine\Bot\FinRL-Library\finrl\trade\backtest.py)


Can you help me out? I want to get the code running.
Thanks, Your reply is highly appreciated.

**Comment by Athe-kunal** [comment]
I was able to get the notebook running as it is. Please update to the recent branch and see if it runs, else try it once on Google Colab too. Uninstall and install FinRL again.

**Comment by Tasneem01** [comment]
> I was able to get the notebook running as it is. Please update to the recent branch and see if it runs, else try it once on Google Colab too. Uninstall and install FinRL again.

Were you able to do it on windows ?
Cause I can still not.

Thanks for your help, 
Highly Appreciate it.
