### ISSUE TITLE
Git clone !pip install git+https://github.com/AI4Finance-LLC/FinRL-Library.git

### ISSUE THREAD

**Issue by Tasneem01** [AI4Finance-Foundation/FinRL#474]
Am trying to import this by that single line of code, and there are multiple parts where am getting error.

First Error:
Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-LLC/FinRL-Library.git 'C:\Users\tasne\AppData\Local\Temp\pip-req-build-x4as1jij'
  Running command git clone --filter=blob:none --quiet https://github.com/quantopian/pyfolio.git 'C:\Users\tasne\AppData\Local\Temp\pip-install-0r5tbm76\pyfolio_931bc624f5f24423840b50b71f31b98d'
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/ElegantRL.git 'C:\Users\tasne\AppData\Local\Temp\pip-install-0r5tbm76\elegantrl_15ecada38334474ebabfdceab6d86f02'
  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  Using setuptools (version 60.9.3).
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\Box2D
  copying library\Box2D\Box2D.py -> build\lib.win-amd64-3.7\Box2D
  copying library\Box2D\__init__.py -> build\lib.win-amd64-3.7\Box2D
  creating build\lib.win-amd64-3.7\Box2D\b2
  copying library\Box2D\b2\__init__.py -> build\lib.win-amd64-3.7\Box2D\b2
  running build_ext
  building 'Box2D._Box2D' extension
  swigging Box2D\Box2D.i to Box2D\Box2D_wrap.cpp
  swig.exe -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library\Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D\Box2D_wrap.cpp Box2D\Box2D.i
  error: command 'swig.exe' failed: None
  [end of output]

Second Error:
Failed to build box2d-py pybullet
Installing collected packages: pybullet, box2d-py, elegantrl, alpaca_trade_api, tensorboard, pyfolio, finrl
  Running setup.py install for pybullet: started
  Running setup.py install for pybullet: finished with status 'error'
  -- laikago/chassis_zup.obj
  -- laikago/chassis_zup_lores.obj
  -- laikago/data1.txt
  -- laikago/hip_motor.mtl
  -- laikago/hip_motor.obj
  -- laikago/hip_motor.stl
  -- laikago/hip_motor_lores.obj
  -- laikago/hip_motor_mirror.mtl
  -- laikago/hip_motor_mirror.obj
  -- laikago/hip_motor_mirror.stl
  -- laikago/hip_motor_mirror_lores.obj
  -- laikago/laikago.urdf
  -- laikago/laikago_tex.jpg
..
..
..
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ic:\users\tasne\appdata\local\programs\python\python37\lib\site-packages\numpy\core\include -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -IExtras/VHACD/inc -IExtras/VHACD/public -Ic:\users\tasne\appdata\local\programs\python\python37\include -Ic:\users\tasne\appdata\local\programs\python\python37\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include" /EHsc /TpExtras/InverseDynamics/CloneTreeCreator.cpp /Fobuild\temp.win-amd64-3.7\Release\Extras/InverseDynamics/CloneTreeCreator.obj -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DBT_ENABLE_VHACD -DPYBULLET_USE_NUMPY -DWIN32 -DGLEW_STATIC
  CloneTreeCreator.cpp
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\cstring(12): fatal error C1083: Cannot open include file: 'string.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

Encountered error while trying to install package.
pybullet
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

Is there anybody who can guide? Any sorta help will be highly appreciated.
Thanks.

**Comment by Athe-kunal** [comment]
If I am not wrong, you can't install FinRL on Windows. You either need WSL or Dual boot OS with Ubuntu and then install it. Or else you can use Google colab and install it
Follow this for installation guide https://ai4finance.medium.com/finrl-for-quantitative-finance-install-and-setup-tutorial-for-beginners-1db80ad39159

**Comment by benwaldner** [comment]
> Am trying to import this by that single line of code, and there are multiple parts where am getting error.
> 
> First Error: Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-LLC/FinRL-Library.git 'C:\Users\tasne\AppData\Local\Temp\pip-req-build-x4as1jij' Running command git clone --filter=blob:none --quiet https://github.com/quantopian/pyfolio.git 'C:\Users\tasne\AppData\Local\Temp\pip-install-0r5tbm76\pyfolio_931bc624f5f24423840b50b71f31b98d' Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/ElegantRL.git 'C:\Users\tasne\AppData\Local\Temp\pip-install-0r5tbm76\elegantrl_15ecada38334474ebabfdceab6d86f02' error: subprocess-exited-with-error
> 
> python setup.py bdist_wheel did not run successfully. exit code: 1 Using setuptools (version 60.9.3). running bdist_wheel running build running build_py creating build creating build\lib.win-amd64-3.7 creating build\lib.win-amd64-3.7\Box2D copying library\Box2D\Box2D.py -> build\lib.win-amd64-3.7\Box2D copying library\Box2D__init__.py -> build\lib.win-amd64-3.7\Box2D creating build\lib.win-amd64-3.7\Box2D\b2 copying library\Box2D\b2__init__.py -> build\lib.win-amd64-3.7\Box2D\b2 running build_ext building 'Box2D._Box2D' extension swigging Box2D\Box2D.i to Box2D\Box2D_wrap.cpp swig.exe -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library\Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D\Box2D_wrap.cpp Box2D\Box2D.i error: command 'swig.exe' failed: None [end of output]
> 
> Second Error: Failed to build box2d-py pybullet Installing collected packages: pybullet, box2d-py, elegantrl, alpaca_trade_api, tensorboard, pyfolio, finrl Running setup.py install for pybullet: started Running setup.py install for pybullet: finished with status 'error' -- laikago/chassis_zup.obj -- laikago/chassis_zup_lores.obj -- laikago/data1.txt -- laikago/hip_motor.mtl -- laikago/hip_motor.obj -- laikago/hip_motor.stl -- laikago/hip_motor_lores.obj -- laikago/hip_motor_mirror.mtl -- laikago/hip_motor_mirror.obj -- laikago/hip_motor_mirror.stl -- laikago/hip_motor_mirror_lores.obj -- laikago/laikago.urdf -- laikago/laikago_tex.jpg .. .. .. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ic:\users\tasne\appdata\local\programs\python\python37\lib\site-packages\numpy\core\include -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -IExtras/VHACD/inc -IExtras/VHACD/public -Ic:\users\tasne\appdata\local\programs\python\python37\include -Ic:\users\tasne\appdata\local\programs\python\python37\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include" /EHsc /TpExtras/InverseDynamics/CloneTreeCreator.cpp /Fobuild\temp.win-amd64-3.7\Release\Extras/InverseDynamics/CloneTreeCreator.obj -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DBT_ENABLE_VHACD -DPYBULLET_USE_NUMPY -DWIN32 -DGLEW_STATIC CloneTreeCreator.cpp C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\cstring(12): fatal error C1083: Cannot open include file: 'string.h': No such file or directory error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX86\x64\cl.exe' failed with exit code 2 [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure
> 
> Encountered error while trying to install package. pybullet note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure.
> 
> Is there anybody who can guide? Any sorta help will be highly appreciated. Thanks.

I did installed it using the latest and and new, clean Ubuntu installation. I installed a conda version that worked with the ubuntu version (some didnt worked). Than I created a conda env and installed everything including cmake before. It could be very difficult if something doesnt work right.

Also make sure you install all packages like torch, nvidia drivers and everything upfront. So it can work after pip install finrl using the new conda env.
