### ISSUE TITLE
Some function may extent the flexibility of FinRL

### ISSUE THREAD

**Issue by shenlei515** [AI4Finance-Foundation/FinRL#481]
I met with some problem when use FinRL in my project, including: 
1. not support different costs_pct with different stocks ( a simple way to solve this is turn buy_costs_pct, sell_costs_pct into list )
2. we can't pocess any gold or bitcoin when initial ( a simple way to solve this is turn initial into list )
3. we can't define time that trading is forbidden ( add technique_index to denote whether the stock is allowed to be bought or sold )
4. not consider conmmision when calculate the share can be bought, and bought the stock to cash<0( I think it's a bug )
5. can't get state of everyday when predict

**Comment by XiaoYangLiu-FinRL** [comment]
Would you like to help improve the codes?  May be submit several PRs?

**Comment by XiaoYangLiu-FinRL** [comment]
Thanks for submitting a PR.
