### ISSUE TITLE
The FinRL_single_stock_trading.ipynb can not be found

### ISSUE THREAD

**Issue by JorisDigital** [AI4Finance-Foundation/FinRL#482]
Hi there, I noticed that the notebook for single stock trading is missing, any chance you can make it available again? 

Error from Google Colab: 
"
Notebook not found
There was an error loading this notebook. Ensure that the file is accessible and try again.
https://github.com/AI4Finance-LLC/FinRL-Library/blob/master/FinRL_single_stock_trading.ipynb
"

**Comment by Athe-kunal** [comment]
Try this https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_StockTrading_NeurIPS_2018.ipynb

**Comment by RoguePower** [comment]
This is also broken
