### ISSUE TITLE
Inference results 

### ISSUE THREAD

**Issue by Timodhau** [AI4Finance-Foundation/FinRL#485]
Hello i get a really strange behavior on prediction using test.py from finrl package. After training a model my predictions are not the same without changing test set and with same model each time. Aren't weight supposed to be frozen and model not exploring during inference?

**Comment by Athe-kunal** [comment]
If you are using Stable Baselines3, then in the predict function pass deterministic=True, like [here](https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/drl_agents/stablebaselines3/models.py#L128)
