### ISSUE TITLE
All notebooks included stablebaseline3 imports has error!

### ISSUE THREAD

**Issue by ghaffari903** [AI4Finance-Foundation/FinRL#488]
![errorr](https://user-images.githubusercontent.com/97940416/155681536-826897c1-197c-4f8c-9308-32ee36b94b9c.png)

**Comment by XiaoYangLiu-FinRL** [comment]
Yes, we are doing refactoring again. LoL.

**Comment by ghaffari903** [comment]
![err](https://user-images.githubusercontent.com/97940416/155725460-201e794f-a816-43c4-9447-72d3fa3141f4.png)

It worked on my local torch with version 1.10.2
I tried to install it on colab notebook but failed!

**Comment by BruceYanghy** [comment]
Please try: !pip install setuptools==59.5.0

**Comment by ghaffari903** [comment]
@BruceYanghy  thank you, its worked.
