### ISSUE TITLE
Can't reproduce portfolio allocation code

### ISSUE THREAD

**Issue by k-desai** [AI4Finance-Foundation/FinRL#496]
Hi. I'm using 49 stocks to reproduce the Dow30 portfolio allocation problem with/without technical indicators. While executing the cell DRL_prediction, I'm getting an AttributeError: StockPortfolioEnv has no attribute called 'save_state_memory'. 

Could you please look into it? Thanks. 

![Image 02-03-22 at 11 18 PM](https://user-images.githubusercontent.com/24428865/156515701-bc73c7ee-3601-419a-a6e0-7b0d2f19be3c.jpg)

**Comment by Athe-kunal** [comment]
Hi @k-desai 
The StockPortfolioEnv only has save_action_memory and save_asset_memory attributes, it does not save_state_memory.
Someone has changed the code for stablebaselines3 models and it works only for one of the environments. I have commented out those lines now, you can review them now

For a quick fix, go to 
 /usr/local/lib/python3.7/dist-packages/finrl/drl_agents/stablebaselines3/models.py and comment out the lines 123. Like I did [here](https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/drl_agents/stablebaselines3/models.py#L123)
