### ISSUE TITLE
Loading models

### ISSUE THREAD

**Issue by alvaromorales1965** [AI4Finance-Foundation/FinRL#498]
When I save and load a model in the same runtime there are no issues executing predictions, but when I do it in different runtimes I have this error. I can load the model but I can't make predictions.

Could anyone help me, please?

trained_ppo.save('/content/drive/MyDrive/Datos Colab/trained_models/trained_ppo.zip')
trained_ppo=model_ppo.load('/content/drive/MyDrive/Datos Colab/trained_models/trained_ppo.zip')

df_daily_return, df_actions = DRLAgent.DRL_prediction(model=trained_ppo, environment = e_trade_gym)

ValueError: Error: Unexpected observation shape (1, 93, 27) for Box environment, please use (92, 27) or (n_env, 92, 27) for the observation shape.

**Comment by alvaromorales1965** [comment]
If it helps, this issue came form  FinRL_PortfolioAllocation_NeurIPS_2020.ipynb

**Comment by alvaromorales1965** [comment]
I sort it out. Thanks

**Comment by neerajchhimwal** [comment]
Hi @alvaromorales1965 , can you share the code for loading and predicting using a model saved in a zip format?
