### ISSUE TITLE
How to deal with dynamic stock pool over time

### ISSUE THREAD

**Issue by lshnmoptim** [AI4Finance-Foundation/FinRL#499]
How can we test over a set of dynamic stock pool? For example, I want to test an algorithm over SZ50 components from 2009 to 2020, but the components change over time, i.e., stocks may join or leave the pool at certain times. What is the general method to deal with this situation? Is there any simplified way we can achieve it in FinRL?

**Comment by XiaoYangLiu-FinRL** [comment]
How about retraining your model every week or month?

**Comment by lshnmoptim** [comment]
> How about retraining your model every week or month? The stock pool May change, but the data is available for retraining the model.

Is there any example that I can look up at present? Thanks.

**Comment by Athe-kunal** [comment]
You can just get the tickers list for the new portfolio in week or month intervals and then re-train the model
