### ISSUE TITLE
How to set multi-agent for DDPG?

### ISSUE THREAD

**Issue by DarkFaceMonster** [AI4Finance-Foundation/FinRL#500]
I'm noob, and wanna set multi-agent
but in the DRLAgent class, couldn't find where can set multi-agent neither multi-worker.
how can i set multi-agent and watch the result?

**Comment by XiaoYangLiu-FinRL** [comment]
Do you want to try this one: https://github.com/AI4Finance-Foundation/ElegantRL/blob/master/elegantrl/agents/AgentMADDPG.py

**Comment by ghaffari903** [comment]
> 

Please share your result, I am working on it any  discussion and comment appreciated.
