### ISSUE TITLE
Does anyone have a learning chart based on episodes?

### ISSUE THREAD

**Issue by skhonsha** [AI4Finance-Foundation/FinRL#507]
I want to know do agents learn? Any tips are appreciated

**Comment by Athe-kunal** [comment]
Hi @skhonsha, can you elaborate on the question?
The MLP model, which is responsible for predicting Value and Action functions, alters their weights according to the data to come up with actions. So there is learning here. What are you expecting to know from here?

**Comment by skhonsha** [comment]
![Plot-of-average-reward-per-episode-versus-epoch-number-for-the-game-of-Seaquest](https://user-images.githubusercontent.com/40491703/158047342-72551dee-cbcd-4368-bc08-373d67e15270.png)

Hi Dear @Athe-kunal , excuse  me I was late, it  seems the agents cant train, do you have same chart to see the rewards are increasing by episodes? so training is done.

**Comment by Athe-kunal** [comment]
You can see the tensorboard plots of the reward to validate whether the model is learning or not. Like in the train_model attribute of SB3 [here](https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/drl_agents/stablebaselines3/models.py#L102).

**Comment by ghaffari903** [comment]
Hi @Athe-kunal , thank you do you have any notebook example?
