### ISSUE TITLE
TypeError: 'module' object is not callable in Demo_MultiCrypto_Trading.ipynb

### ISSUE THREAD

**Issue by kangyining** [AI4Finance-Foundation/FinRL#514]
I guess this could be a result of underlying library updates. Any thoughts on this one?

Original code:

```
train(start_date=TRAIN_START_DATE, 
      end_date=TRAIN_END_DATE,
      ticker_list=TICKER_LIST, 
      data_source='binance',
      time_interval='5m', 
      technical_indicator_list=TECHNICAL_INDICATORS_LIST,
      drl_lib='elegantrl', 
      env=env, 
      model_name='ppo', 
      current_working_dir='./test_ppo',
      erl_params=ERL_PARAMS,
      break_step=5e4,
      if_vix=False
      )
```

Output before fail:

```
Not support for {self.data_source}
{self.data_source} successfully connected
Using cached file ./cache/BTCUSDT_ETHUSDT_ADAUSDT_BNBUSDT_XRPUSDT_SOLUSDT_DOTUSDT_DOGEUSDT_AVAXUSDT_UNIUSDT_binance_2021-09-01_2021-09-20_5m.pickle
tech_indicator_list:  ['macd', 'rsi', 'cci', 'dx']
indicator:  macd
indicator:  rsi
indicator:  cci
indicator:  dx
Succesfully add technical indicators
Successfully transformed into array
| Arguments Remove cwd: ./test_ppo
```

Errors:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-40-0e8fc459cfcb>](https://localhost:8080/#) in <module>()
     11       erl_params=ERL_PARAMS,
     12       break_step=5e4,
---> 13       if_vix=False
     14       )

3 frames
[<ipython-input-34-ea6d6205e665>](https://localhost:8080/#) in train(start_date, end_date, ticker_list, data_source, time_interval, technical_indicator_list, drl_lib, env, model_name, if_vix, **kwargs)
     34         trained_model = agent.train_model(model=model, 
     35                                           cwd=current_working_dir,
---> 36                                           total_timesteps=break_step)
     37 
     38     elif drl_lib == 'rllib':

[/FinRL-Meta/drl_agents/elegantrl_models.py](https://localhost:8080/#) in train_model(self, model, cwd, total_timesteps)
     80         model.cwd = cwd
     81         model.break_step = total_timesteps
---> 82         train_and_evaluate(args=model)
     83 
     84     @staticmethod

[/FinRL-Meta/ElegantRL/elegantrl/train/run.py](https://localhost:8080/#) in train_and_evaluate(args)
     20     env = build_env(args.env, args.env_func, args.env_args)
     21 
---> 22     agent = init_agent(args, gpu_id, env)
     23     buffer = init_buffer(args, gpu_id)
     24     evaluator = init_evaluator(args, gpu_id)

[/FinRL-Meta/ElegantRL/elegantrl/train/run.py](https://localhost:8080/#) in init_agent(args, gpu_id, env)
     62 
     63 def init_agent(args, gpu_id, env=None):
---> 64     agent = args.agent(args.net_dim, args.state_dim, args.action_dim, gpu_id=gpu_id, args=args)
     65     agent.save_or_load_agent(args.cwd, if_save=False)
     66 

TypeError: 'module' object is not callable
```

Thanks a lot!

**Comment by leMoritzXD** [comment]
Is there a workaround at the moment?

**Comment by XiaoYangLiu-FinRL** [comment]
How about now, after we made many updates.  Are you able to run locally?

**Comment by kangyining** [comment]
> How about now, after we made many updates. Are you able to run locally?

Let me try that.

**Comment by kangyining** [comment]
@XiaoYangLiu-FinRL Sorry, but it seems that the original problem still persists.

**Comment by zhumingpassional** [comment]
We have revised the data processor.  It may help you.

**Comment by kangyining** [comment]
> We have revised the data processor. It may help you.

Sorry but it still doesn't seem to work...

**Comment by zhumingpassional** [comment]
revised.

Fixed.

**Comment by kangyining** [comment]
Thanks for the fix! However, I still run into some issues on my side:
![image](https://user-images.githubusercontent.com/22406297/161771559-b04a54d2-333a-4e61-9a5f-9681bd52a878.png)

Any walkaround on that one?

**Comment by kangyining** [comment]
It seems to work now. Thanks a lot!

**Comment by kangyining** [comment]
One more question, when I change the TICKER_LIST to only one, for example: BTCUSDT, the code doesn't work(i.e. the ElegantRL doesn't provide any output). Is there any workaround to make this notebook work for single crypto?

**Comment by zhumingpassional** [comment]
which notebook did you run?

Have you revised any parameters?


Wish you all my best.
Sincerely,
Ming Zhu.


kangyining ***@***.***> 于2022年4月11日周一 01:30写道：

**Comment by kangyining** [comment]
This one:https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/3-Practical/FinRL_MultiCrypto_Trading.ipynb

I use only one parameter "BTCUSDT" for the TICKER_LIST, and different algorithms like ddpg, TD3, etc. DDPG doesn't seem to give a valid output: the ElegantRL gives a straight line.

**Comment by zhumingpassional** [comment]
what do you mean by " a valid output" and “a straight line”?

Can you describe more about it?



Wish you all my best.
Sincerely,
Ming Zhu.


kangyining ***@***.***> 于2022年4月11日周一 17:01写道：

**Comment by zhumingpassional** [comment]
With respect to the structure of tutorials (notebook and python), there are
several proposals
https://github.com/AI4Finance-Foundation/FinRL-Meta/issues/134. We welcome
everyone can give some suggestions.

Wish you all my best.
Sincerely,
Ming Zhu.


Ming Zhu ***@***.***> 于2022年4月12日周二 11:08写道：

**Comment by kangyining** [comment]
Sorry, I'm trying to reproduce it but can't seem to find one until now. But shouldn't the resulting curve always be a positive one here?

**Comment by zhumingpassional** [comment]
@kangyining If there is only one ticker in TICKER_LIST, the state_dim is too small. Please use more tickers, just like DOW_30.

**Comment by kangyining** [comment]
@zhumingpassional  Thanks a lot! May I ask how to get the exact action value during the training and testing? And if so, what does it represent?

**Comment by zhumingpassional** [comment]
@kangyining  You may print the actions in RL algorithm code, which depends the DRL library, eg., elegantRL, SB3, and RLlib.
