### ISSUE TITLE
可以帮我找回之前的issue吗？

### ISSUE THREAD

**Issue by A5230171** [AI4Finance-Foundation/FinRL#520]
管理员您好，我之前有发过一个简体中文的issue，然后也有回复我，对我蛮重要的，我现在找不到了，可以帮我恢复一下内容嘛，或者将当时的回复我的内容发生到我的email（A5230171@g.pccu.edu.tw）,谢谢！

**Comment by XiaoYangLiu-FinRL** [comment]
Is it the following one:
[xhttps://github.com/AI4Finance-Foundation/FinRL/issues/439](https://github.com/AI4Finance-Foundation/FinRL/issues/439)
