### ISSUE TITLE
Development setup with PyCharm

### ISSUE THREAD

**Issue by ihopethiswillfi** [AI4Finance-Foundation/FinRL#522]
I spent entire last evening to try and get FinRL, ElegantRL and FinRL-Meta up and running in an IDE on a local machine for easy debugging and development.  After this interesting adventure *cough cough*, I propose to add the following to the docs.  

Can anyone please test this to see if it all works properly?

I'm open to any suggestions and/or modifications.

For the future PR: to which file best to commit?

# Development setup with PyCharm

This setup makes it easy to work on all of AI4Finance-Foundation's repositories simultaneously, while allowing easy debugging, committing to the respective repo's and creating PR's.

## Intro
- Download and install Anaconda.
- Download and install PyCharm.  The Community edition (free) offers everything you need.
- [Github] Fork FinRL to your private repo.
- [Github] Fork ElegantRL to your private repo.
- [Github] Fork FinRL-Meta to your private repo.
- All next steps happen on your local machine

## Download files
mkdir ~/AI4Finance
cd ~/AI4Finance
git clone https://github.com/[your_github_username]/FinRL.git
git clone https://github.com/[your_github_username]/ElegantRL.git
git clone https://github.com/[your_github_username]/FinRL-Meta.git

## Create a Conda environment
cd ~/AI4Finance
conda create --name ai4finance python=3.8
conda activate ai4finance

cd FinRL
pip install -r requirements.txt
cd ..

cd ElegantRL
ElegantRL does not contain a requirements.txt, so open setup.py in a text editor and pip install anything you can find under 'install_requires'

## Configure PyCharm project
- Launch PyCharm
- File > Open > [AI4Finance project folder]
- At the bottom right of the status bar, change the interpreter to the ai4finance conda environment.
- At the left of the screen, in the project file tree:
	- Right-click on the FinRL folder > Mark Directory as > Sources Root
	- Right-click on the ElegantRL folder > Mark Directory as > Sources Root
	- Right-click on the FinRL-Meta folder > Mark Directory as > Sources Root

## Creating commits and PR's
- Create your commits as you usually do through PyCharm.
- Make sure each commit covers only 1 of the 3 repo's.  E.g. don't create a commit that spans both FinRL and ElegantRL.
- When you do a Git Push, PyCharm will ask you to which of the 3 repo's you want to push.

**Comment by XiaoYangLiu-FinRL** [comment]
Thanks very much, appreciate!

**Comment by zhumingpassional** [comment]
Thanks for your suggestions.

We will integrate it to docs.

**Comment by XiaoYangLiu-FinRL** [comment]
@ihopethiswillfi  would you like to help update your steps on the website https://finrl.readthedocs.io/en/latest/index.html

It can be done via the docs folder: https://github.com/AI4Finance-Foundation/FinRL/tree/master/docs

**Comment by ihopethiswillfi** [comment]
@XiaoYangLiu-FinRL, sounds good, I will submit a PR later to add a new page here:

https://github.com/AI4Finance-Foundation/FinRL/tree/master/docs/source/developer
