### ISSUE TITLE
How to update the indicators iteratively during a trade?

### ISSUE THREAD

**Issue by italodamato** [AI4Finance-Foundation/FinRL#523]
Hi everyone,

My strategy requires to recompute the value of some indicators during a trade and to reset their status to the baseline when I exit the trade. Is it possible to implement a similar behaviour here?

An example is not to allow EMA200 to decrease during an active trade.

Thanks in advance.

**Comment by XiaoYangLiu-FinRL** [comment]
A first question would be: would you need use indicators as states, or use them to control the trade execution?

In the later case, you can treat actions of an RL agent as trading signals, and consulting indicators before taking actual actions.

**Comment by italodamato** [comment]
I's use them as indicators so that the agent can make a decision.

I came up with the following way. Do you think it can work?

```py

class StockTradingEnv(gym.Env):
	def __init__(...):
		self.in_trade = {}

[...]

 def _sell_stock(self, index, action):
	[...]
	# before returning the result
	if sell_num_shares > 0:
            self.in_trade[index] = 0

        return sell_num_shares


 def _buy_stock(self, index, action):
	[...]
	# before returning the result
	if buy_num_shares > 0:
            self.in_trade[index] = 1

        return buy_num_shares

 def _update_indicators_in_trade(self, index):
 	# edit self.data.iloc[index]
	pass

 def _update_state(self):
    if len(self.df.tic.unique()) > 1:
        for in_trade_idx in [k for k, v in self.in_trade.items() if v == 1]:            
           self._update_indicators_in_trade(in_trade_idx)
```

**Comment by XiaoYangLiu-FinRL** [comment]
Changing the "input feature" of a trained algorithm (nueral networks)… also changing the state space during the training or testing stage…well I do not know whether it is allowed;  theoretically NO.

But you can play with codes first.  Would like to know if it works.

**Comment by italodamato** [comment]
I think the rules of the game change depending on if the agent is in a trade or not. The agent should be looking at the data in a different way. Wondering if even having an attribute that tells the agent whether they are in a trade would help them distinguish the two games.

**Comment by XiaoYangLiu-FinRL** [comment]
How an agent knows it is a new feature, not treating as the old one with new values.

**Comment by italodamato** [comment]
I'm not sure I follow. Theoretically, I'm not changing the data the agent used to make a decision. The only thing I'd change is the future data.

Let's make an example:
- candle 10: buy signal 
- candle 10: I update the EMA200 at candle 11 to be the `max(ema200_candle10, ema200_candle11)`
- candle 11: agent makes a decision based on the untouched values for candles 0-10, plus takes into account the modified ema200 for candle 11

**Comment by XiaoYangLiu-FinRL** [comment]
In many ML algorithm, the input is fixed as follows:
e.g., [10, 8, 5] means that feature1 = 10,  feature2 = 8, and feature3 = 5.
Now, if you replace feature3 by feature, and it becomes [feature1, feature2, feature4].

I do not know how to make an agent knows it.

**Comment by italodamato** [comment]
It's technically the same feature, but its value depends on the decisions of the agent. Also, the agent hasn't seen the value at that moment in time yet (the historical values before entering the trade will stay constant)

**Comment by XiaoYangLiu-FinRL** [comment]
"the historical values before entering the trade will stay constant":  how to teach the agent to learn?  what would be the thing /information that can be learned?  NOT sure.
