### ISSUE TITLE
Alpaca data source URL endpoints v1 has been deprecated as of March 17

### ISSUE THREAD

**Issue by ObaidaAlhaasan** [AI4Finance-Foundation/FinRL#531]
Hey Team, I hope all are good

I'm trying to implement automatic trader with Alpaca Data source, and it seems alpaca deprecated their v1 URL as of March 17

I'm getting this error  now, the same code was working fine last week before alpaca deprecated the v1

```
DP = DataProcessor(data_source = 'alpaca',
                   API_KEY = API_KEY,
                   API_SECRET = API_SECRET,
                   APCA_API_BASE_URL = APCA_API_BASE_URL)



data = DP.download_data(start_date = '2021-02-01',
                        end_date = '2021-10-05',
                        ticker_list = ticker_list,
                        time_interval= '1Min'
                        )
```

```
Alpaca successfully connected
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[<ipython-input-10-2b2f7268b733>](https://localhost:8080/#) in <module>()
      9                         end_date = '2021-10-05',
     10                         ticker_list = ticker_list,
---> 11                         time_interval= '1Min'
     12                         )

6 frames
[/usr/local/lib/python3.7/dist-packages/requests/models.py](https://localhost:8080/#) in raise_for_status(self)
    958 
    959         if http_error_msg:
--> 960             raise HTTPError(http_error_msg, response=self)
    961 
    962     def close(self):

HTTPError: 404 Client Error: Not Found for url: https://data.alpaca.markets/v1/bars/1Min?symbols=AAPL&limit=500&start=2021-02-01T09%3A30%3A00-05%3A00&end=2021-02-01T15%3A59%3A00-05%3A00
```

A possible solution from the Alpaca forum [Link](https://forum.alpaca.markets/t/new-errors-with-no-changes/8812/4)

1. change from V1 to V2.

2. add ‘stocks’ before the /bars

3. the results are also different. Mainly the ‘time’ format has changed from UTC to a readable format so needed to be parsed differently.

**Comment by NicoleRichards1998** [comment]
I managed to fix it in my colab workbook by changing a few small things in the download_data and clean_data functions of AlpacaProcessor (the changes are in bold):

```
def download_data(
        API_KEY, API_SECRET, ticker_list, start_date, end_date, time_interval
    ) -> pd.DataFrame:


        start = start_date
        end = end_date
        time_interval = time_interval
```
**API_DATA_URL = 'https://data.alpaca.markets/v2/stocks'**
```
        api = tradeapi.REST(API_KEY, API_SECRET, API_DATA_URL)

        NY = "America/New_York"
        start_date = pd.Timestamp(start_date, tz=NY)
        end_date = pd.Timestamp(end_date, tz=NY) + pd.Timedelta(days=1)
        date = start_date
        data_df = pd.DataFrame()
        while date != end_date:
            start_time = (date + pd.Timedelta("09:30:00")).isoformat()
            end_time = (date + pd.Timedelta("15:59:00")).isoformat()
            for tic in ticker_list:
```

**barset = api.get_bars(
                    tic, TimeFrame.Minute, start=start_time, end=end_time, limit=500, adjustment='raw').df**
```
                barset['tic'] = tic
                barset = barset.reset_index()
                data_df = data_df.append(barset)
                
            print(("Data before ") + end_time + " is successfully fetched")
            date = date + pd.Timedelta(days=1)
            if date.isoformat()[-14:-6] == "01:00:00":
                date = date - pd.Timedelta("01:00:00")
            elif date.isoformat()[-14:-6] == "23:00:00":
                date = date + pd.Timedelta("01:00:00")
            if date.isoformat()[-14:-6] != "00:00:00":
                raise ValueError("Timezone Error")
        """times = data_df['time'].values
        for i in range(len(times)):
            times[i] = str(times[i])
        data_df['time'] = times"""

        return data_df

```
```
def clean_data(df, start, end):

        tic_list = np.unique(df.tic.values)

        trading_days = get_trading_days(start=start, end=end)
        #produce full time index
        times = []
        for day in trading_days:
            NY = "America/New_York"
            current_time = pd.Timestamp(day + " 09:30:00").tz_localize(NY)
            for i in range(390):
                times.append(current_time)
                current_time += pd.Timedelta(minutes=1)
        #create a new dataframe with full time series
        new_df = pd.DataFrame()
        for tic in tic_list:
            tmp_df = pd.DataFrame(
                columns=["open", "high", "low", "close", "volume"], index=times
            )
            tic_df = df[df.tic == tic]

            for i in range(tic_df.shape[0]):
```
**tmp_df.loc[tic_df.iloc[i]['timestamp']] = tic_df.iloc[i][
                ["open", "high", "low", "close", "volume"]
                ]**
            
 ```
           #if the close price of the first row is NaN
            if str(tmp_df.iloc[0]["close"]) == "nan":
               print('The price of the first row for ticker ', tic, ' is NaN. ', 
                     'It will filled with the first valid price.')
               for i in range(tmp_df.shape[0]):
                   if str(tmp_df.iloc[i]["close"]) != "nan":
                          first_valid_price = tmp_df.iloc[i]["close"]
                          tmp_df.iloc[0] = [first_valid_price,
                                     first_valid_price,
                                     first_valid_price,
                                     first_valid_price,
                                     0.0,]
                          break
            #if the close price of the first row is still NaN (All the prices are NaN in this case)
            if str(tmp_df.iloc[0]["close"]) == "nan":
                print('Missing data for ticker: ', tic, ' . The prices are all NaN. Fill with 0.')
                tmp_df.iloc[0] = [0.0, 0.0, 0.0, 0.0, 0.0,]
                      
            #forward filling row by row
            for i in range(tmp_df.shape[0]):
                if str(tmp_df.iloc[i]["close"]) == "nan":
                    previous_close = tmp_df.iloc[i - 1]["close"]
                    if str(previous_close) == "nan":
                        raise ValueError
                    tmp_df.iloc[i] = [
                        previous_close,
                        previous_close,
                        previous_close,
                        previous_close,
                        0.0,
                    ]
            tmp_df = tmp_df.astype(float)
            tmp_df["tic"] = tic
            new_df = new_df.append(tmp_df)

        new_df = new_df.reset_index()
        new_df = new_df.rename(columns={"index": "time"})

        print("Data clean finished!")

        return new_df
```

**Comment by ObaidaAlhaasan** [comment]
@NicoleRichards1998 
Thank you for your code.

I tried it in my google collab and it's throwing an error related to alpaca-trading-api, so I opened an issue in alpaca-trading-api.

Did you see the same error I'm getting ??

[Issue Link](https://github.com/alpacahq/alpaca-trade-api-python/issues/594)

**Comment by NicoleRichards1998** [comment]
@zhumingpassional I really wanted to push a pull request, I just have no idea how to do that from my colab notebook X_X
and @ObaidaAlhaasan I'm so sorry its still not working on your side. Here is a link to my notebook if you want to get the code directly from there: https://github.com/NicoleRichards1998/FinRL/blob/0234bc493c5e16edfe6ca91008698c92e16fb4c4/DayTrading_with_Tune_LSTM_FinRL.ipynb 
Its a bit different from the finrl alpaca example, because I changed how it interacts with the environment so its strictly making day trading activities (that's why the config arrays are being put into lists). But other than that its definitily working on my side

**Comment by yizhangliu** [comment]
def download_data(
            self, ticker_list, start_date, end_date, time_interval
        ) -> pd.DataFrame:

        self.start = start_date
        self.end = end_date
        self.time_interval = time_interval

        NY = "America/New_York"
        start_date = pd.Timestamp(start_date, tz=NY)
        end_date = pd.Timestamp(end_date, tz=NY) + pd.Timedelta(days=1)
        date = start_date
        data_df = pd.DataFrame()
        while date != end_date:
            start_time = (date + pd.Timedelta("09:30:00")).isoformat()
            end_time = (date + pd.Timedelta("15:59:00")).isoformat()
            for tic in ticker_list:
                # barset = self.api.get_barset(
                #    [tic], time_interval, start=start_time, end=end_time, limit=500
                # ).df[tic]
                barset = self.api.get_bars(
                    tic, time_interval, start=start_time, end=end_time, limit=500
                    ).df
                barset["tic"] = tic
                barset = barset.reset_index()
                data_df = data_df.append(barset)
            print(("Data before ") + end_time + " is successfully fetched")
            # print(data_df.head())
            date = date + pd.Timedelta(days=1)
            if date.isoformat()[-14:-6] == "01:00:00":
                date = date - pd.Timedelta("01:00:00")
            elif date.isoformat()[-14:-6] == "23:00:00":
                date = date + pd.Timedelta("01:00:00")
            if date.isoformat()[-14:-6] != "00:00:00":
                raise ValueError("Timezone Error")

        data_df['time'] = data_df['timestamp'].apply(lambda x: x.strftime('%Y-%m-%d %H:%M:%S'))

        return data_df
-------------------------------------------------------------------------------
1.  get_barset(   ---->  get_bars(    
2.  timestamp  ---->  time
3.  There are three 'get_barset( '  in file processor_alpaca.py.

**Comment by ObaidaAlhaasan** [comment]
Thank you so much @yizhangliu

**Comment by ObaidaAlhaasan** [comment]
Could you please create a PR with this fix?
 If you would like I could create the PR and credit you, I'm struggling to create a working sample with alpaca

**Comment by ObaidaAlhaasan** [comment]
Fixed!
