### ISSUE TITLE
Is there a notebook for this plot example?

### ISSUE THREAD

**Issue by ghaffari903** [AI4Finance-Foundation/FinRL#538]
https://github.com/AI4Finance-Foundation/FinRL/pull/113

what is exact input parameters? Has ticker list one ticker only?
https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/plot.py#L76

**Comment by zhumingpassional** [comment]
ticker list has one or multiple tickers, e.g., ["AAPL"], [    "AXP",    "AMGN",]
