### ISSUE TITLE
'float' object is not subscriptable

### ISSUE THREAD

**Issue by futureofworld** [AI4Finance-Foundation/FinRL#540]
I got this error while training a model, error look like this, please help to fix this issue
TypeError                                 Traceback (most recent call last)
[<ipython-input-30-979121541eab>](https://localhost:8080/#) in <module>()
      1 trained_sac = agent.train_model(model=model_sac, 
      2                              tb_log_name='sac',
----> 3                              total_timesteps=60000)

8 frames
[/usr/local/lib/python3.7/dist-packages/finrl/finrl_meta/env_stock_trading/env_stocktrading.py](https://localhost:8080/#) in _do_buy()
    156             # if self.state[index + 1] >0:
    157                 # Buy only if the price is > 0 (no missing data in this particular date)
--> 158                 available_amount = self.state[0] / (self.state[index + 1]*(1 + self.buy_cost_pct[index])) # when buying stocks, we should consider the cost of trading when calculating available_amount, or we may be have cash<0
    159                 # print('available_amount:{}'.format(available_amount))
    160 

TypeError: 'float' object is not subscriptable

**Comment by duwf2003** [comment]
My God! It haven't been resolved yet.

**Comment by XiaoYangLiu-FinRL** [comment]
Well, would you like to help out?   Be a God to this particular bug, :)    Thx!

**Comment by zhumingpassional** [comment]
Did you initialize "initial_amount" a float number?

Please see the issue: https://github.com/AI4Finance-Foundation/FinRL/issues/518. It can help you. Recently we revised the code. 

The following code may help you:

buy_cost_list = sell_cost_list = [0.001] * stock_dimension
num_stock_shares = [0] * stock_dimension

env_kwargs = { 
    "hmax": 100, 
    "initial_amount": 1000000, 
    "num_stock_shares": num_stock_shares,
    "buy_cost_pct": buy_cost_list, 
    "sell_cost_pct": sell_cost_list, 
    "state_space": state_space, 
    "stock_dim": stock_dimension, 
    "tech_indicator_list": config.INDICATORS, 
    "action_space": stock_dimension, 
    "reward_scaling": 1e-4 
}
e_train_gym = StockTradingEnv(df = train, **env_kwargs)

**Comment by zhumingpassional** [comment]
Fixed.
