### ISSUE TITLE
FinRL-Meta - package or github repo to be used in FinRL

### ISSUE THREAD

**Issue by Kilagi** [AI4Finance-Foundation/FinRL#542]
Hi all,

First of all, thanks a lot for this project. I've just started playing around with it and hope to be actively contributing soon as well.

I have noticed that the dataprocessors in the [FinRL-Meta](https://github.com/AI4Finance-Foundation/FinRL-Meta) repo are quite different than the ones available in the [package that comes with FinRL](https://github.com/AI4Finance-Foundation/FinRL/tree/master/finrl/finrl_meta). Since I'll be setting up a custom environment and dataprocessor for my project, I was wondering which baseline I should be following to ensure compatibility with future changes?

Thanks in advance!

**Comment by XiaoYangLiu-FinRL** [comment]
Thanks very much for this good question.  Actually, we are also working on "unifying" the two.  We would like to make the two repo to satisfy the "plug-and-play" principle.

**Comment by Kilagi** [comment]
Thanks for the rapid reply. If you give me a guideline, I'm definitely willing to contribute to this development if you'd need it. I'd just need to know if a certain baseline is already defined (such as the [data_processor.py](https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/finrl_meta/data_processor.py) in the FinRL-Meta repo). I can then adapt the different dataprocessors to follow the same approach.

**Comment by zhumingpassional** [comment]
We are now developing finrlmeta. In the future, we will integrate finrlmeta to finrl so that they are unified.
