### ISSUE TITLE
Are trained models provided?

### ISSUE THREAD

**Issue by zeyuanchen23** [AI4Finance-Foundation/FinRL#548]
Are there any trained models available?

**Comment by XiaoYangLiu-FinRL** [comment]
Thanks for your inquiry.  We are planning to provide trained models, and also demos to be held on a cloud server.

**Comment by ObaidaAlhaasan** [comment]
Hello @XiaoYangLiu-FinRL,

I would suggest a trained model that works with alpaca paper trading, a trained model with alpaca will be a good sample for the algo trading community and anyone who is looking for something similar in the Alpaca community and struggling to build something like this

Any trained model that is close to production will be a good addition to FinRl

**Comment by XiaoYangLiu-FinRL** [comment]
@ObaidaAlhaasan hi, I just saw your message.  Your proposal is very good!  How is the current status?

**Comment by ObaidaAlhaasan** [comment]
Hi @XiaoYangLiu-FinRL , sorry just saw your msg, unfortunately I couldn't make that demo with FinRL "keep facing issues" and the team decided to do more research and discover more options, If you would like we could chat about how we could collaborate on building that demo or to build a custom model based on FinRl, please send me your email or any way I can reach out to you and I'll include my manager to continue our chat.

Thank you in advance!

**Comment by XiaoYangLiu-FinRL** [comment]
My email is: XL2427 at Columbia dot edu

**Comment by ObaidaAlhaasan** [comment]
Sure, thank you @XiaoYangLiu-FinRL, talk to you soon
