### ISSUE TITLE
Importing agents throw Module not found error

### ISSUE THREAD

**Issue by ObaidaAlhaasan** [AI4Finance-Foundation/FinRL#549]
Hi team, I hope you all are well

I'm trying to build a bot that runs with Alpaca paper trading following this notebook [paper-trading](https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/3-Practical/FinRL_PaperTrading_Demo.ipynb)

When I reached the point that run the `train` method that imported as `from finrl.train import train` 

And ran it with the following params

```
train(start_date = start,
      end_date = end,
      ticker_list = ticker_list,
      data_source = 'alpaca',
      time_interval= time_interval,
      technical_indicator_list= TECHNICAL_INDICATORS_LIST,
      drl_lib='elegantrl',
      env=env,
      model_name='ppo',
      API_KEY = API_KEY,
      API_SECRET = API_SECRET,
      APCA_API_BASE_URL = APCA_API_BASE_URL,
      erl_params=ERL_PARAMS,
      cwd='./papertrading_erl',
      total_timesteps=1e5)
```

I got the following error

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-24-e6d14a5736eb> in <module>()
     18       erl_params=ERL_PARAMS,
     19       cwd='./papertrading_erl',
---> 20       total_timesteps=1e5)

1 frames
/usr/local/lib/python3.7/dist-packages/finrl/agents/elegantrl/models.py in <module>()
      1 # DRL models from ElegantRL: https://github.com/AI4Finance-Foundation/ElegantRL
      2 import torch
----> 3 from elegantrl.agents.agent import AgentDDPG
      4 from elegantrl.agents.agent import AgentPPO
      5 from elegantrl.agents.agent import AgentSAC

ModuleNotFoundError: No module named 'elegantrl.agents.agent'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
```

If you have a look at the source code you will notice that the imports are highlighted with a red error

![image](https://user-images.githubusercontent.com/35659426/161377205-42c0965f-48cd-4e3a-930b-c0aab7489603.png)

**Comment by ObaidaAlhaasan** [comment]
Probably the fix would just remove the `.agent` from import to be as the following, but please confirm to me to create a PR since I'm not an expert in this area, thank you in advance!


![image](https://user-images.githubusercontent.com/35659426/161377294-6826dd76-6b23-48b7-a25c-5fd2e7ac4d22.png)

**Comment by zhumingpassional** [comment]
@ObaidaAlhaasan Yes. ElegantRL updates frequently recently.

**Comment by zhumingpassional** [comment]
@ObaidaAlhaasan You can use GitHub desktop to submit a PR.

**Comment by zhumingpassional** [comment]
This has been revised. Please see https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/agents/elegantrl/models.py

**Comment by zhumingpassional** [comment]
fixed

**Comment by ObaidaAlhaasan** [comment]
Thank you sir @zhumingpassional , I was off yesterday and hadn't had the chance to push it, thanks for your effort!
