### ISSUE TITLE
Hi apparently I can't install FINRL

### ISSUE THREAD

**Issue by giannisperti** [AI4Finance-Foundation/FinRL#551]
Hi this is the issue i get when i launch pip install finrl: 

>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: legacy-install-failure
> 
> × Encountered error while trying to install package.
> ╰─> box2d-py
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for output from the failure.

sorry if this is trivial but i don't know what to do, thanks for the help

**Comment by giannisperti** [comment]
I resolved that one but I still get another error namely this one:

> ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

now what do i do? :D

**Comment by giannisperti** [comment]
Now I have a problem with this: 

`df = YahooDownloader(start_date = '2009-01-01',
                     end_date = '2021-01-01',
                     ticker_list = dow_tickers).fetch_data()`

where dow_tickers is just a list I wrote myself since config.DOW_30_TICKER wasnt working... 

but i get multiple errors like: 

> TypeError: import_optional_dependency() got an unexpected keyword argument 'errors'

i think the tutorial it's not working anymore guys any suggestion? maybe there is an updated version of the tutorial?

**Comment by zhumingpassional** [comment]
Do you use MAC OS or linux?

**Comment by NAmorim** [comment]
If on ubuntu you need to install the python version dev package. My case was "apt install python3.9-dev".

**Comment by zhumingpassional** [comment]
Please see https://finrl.readthedocs.io/en/latest/developer_guide/development_setup.html

**Comment by varunpan** [comment]
I have the same error on MAC OS (apple silicon) with Python 3.9
I follow the steps in the development setup link to fork and clone then install the requirements. (https://finrl.readthedocs.io/en/latest/developer_guide/development_setup.html)

I received the same error:
× Encountered error while trying to install package.
╰─> box2d-py

I was able to bypass  this error and install FinRL with python 3.9 with by doing following:
```
conda create --name [env name] python=3.9
conda activate [env name]
conda install swig
pip install git+https://github.com/AI4Finance-Foundation/FinRL.git
```
Reference: https://stackoverflow.com/a/70323937/9157627
