### ISSUE TITLE
use_technical_indicator= False has keyError for environment setup step

### ISSUE THREAD

**Issue by zzhan127** [AI4Finance-Foundation/FinRL#557]
When I do not want to use the technical indicator and set it to false, I cannot set up the correct environment because e_train_gym = StockTradingEnv(df = train, **env_kwargs) this will return KeyError: 'macd'

**Comment by zhumingpassional** [comment]
technical_indicator_list is imported from config.py.

If use_technical_indicator== False，technical_indicator_list should be an empty list.
