### ISSUE TITLE
Usage for intraday trading 2

### ISSUE THREAD

**Issue by Marneus** [AI4Finance-Foundation/FinRL#567]
Hello,

I wanted to test the intraday trading with finRL lib, and i found this [post](https://github.com/AI4Finance-Foundation/FinRL/issues/73)  which explain how to do... but I haven't been able to properly implement this code.
I took the following [code](https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/4-Optimization/FinRL_HyperparameterTuning_Optuna.ipynb) and I added a column 'hour_coef' in my data('processed_full') , which is always equal to 0, except for the last 30 minutes of the day where it is equal to 1.

I modifed the "step" function of "env_stocktrading.py" ([here](https://github.com/AI4Finance-Foundation/FinRL/tree/master/finrl/finrl_meta/env_stock_trading)) in which I did :
```
def step(self, actions):
	self.terminal = self.day >= len(self.df.index.unique()) - 1
	if self.terminal:		
		{...}
	else:
		{...}
		end_total_asset = self.state[0] + sum(
			np.array(self.state[1 : (self.stock_dim + 1)])
			* np.array(self.state[(self.stock_dim + 1) : (self.stock_dim * 2 + 1)])
		)
		self.asset_memory.append(end_total_asset)
		self.date_memory.append(self._get_date())
		self.reward = end_total_asset - begin_total_asset
		
		# START MODIFICATION
		first_position_hour_coef = 1 + 2*self.stock_dim  + len(self.tech_indicator_list) * self.stock_dim  #position of my column with hour_coef
		self.reward  = self.reward - (self.state[first_position_hour_coef]) * begin_total_asset) 
		# END MODIFICATION
		
		self.rewards_memory.append(self.reward)
		self.reward = self.reward * self.reward_scaling

	return self.state, self.reward, self.terminal, {}
```
	

Despite this, when I test my trained model, and I consult df_actions returned by DRLAgent.DRL_prediction(...), here is what i get :

```
                     AMD  EEM  EFA  EWZ  FXI  GDX  GLD  IVV  IWM  QQQ  ...  \
date                                                                   ...   
2022-03-28 09:30:00    0  137    0  137    0  137  137    0    0    0  ...   
2022-03-28 09:31:00    0  137    0  137    0  137  137    0    0    0  ...   
2022-03-28 09:32:00    0   81    0    0    0    0    0    0    0    0  ...   
2022-03-28 09:33:00    0    0    0    0    0    0    0    0    0    0  ...   
2022-03-28 09:34:00    0    0    0    0    0    0    0    0    0    0  ...   
...                  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
2022-03-28 15:55:00    0    0    0    0    0    0    0    0    0    0  ...   
2022-03-28 15:56:00    0    0    0    0    0    0    0    0    0    0  ...   
2022-03-28 15:57:00    0    0    0    0    0    0    0    0    0    0  ...   
2022-03-28 15:58:00    0    0    0    0    0    0    0    0    0    0  ...   
2022-03-28 15:59:00    0    0    0    0    0    0    0    0    0    0  ...  
```

It only performs actions during the first minutes of the day, then it does nothing: the rest of df_actions is at zero, and I have no sale at the end of the day.

I tried with different combinations of hyperparameters, increasing my timestep... but nothing happens after the first 5 minutes.
I also tested with other models (A2C...), but even if I have more trades than with the ddpg model, I still don't have a massive sale at the end of the day.

Did I make a mistake somewhere? Or there is something I dont' understand ?

**Comment by Athe-kunal** [comment]
If you want to extensively try out hyperparameters, then you can try out these set of [tutorials](https://github.com/AI4Finance-Foundation/FinRL/tree/master/tutorials/4-Optimization) and then check out the df_actions.

**Comment by Marneus** [comment]
Thank you for your advice.

I already try optuna and test the [first tutorial](https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/4-Optimization/FinRL_HyperparameterTuning_Optuna.ipynb) of this set (with ddpg) , whith these hyperparameters :

 - batch_size (between  2 and 1200)
 - buffer_size  (between  1e4 and 1e6)                 
 - learning_rate (between  1e-6 and 1e-2)
 - learning_starts (between 50 and 200)
 - tau (between 0.001 and 0.010)
 - gamma (between 0.950 and 1)
 - gradient_steps (between  -5 and -1)
   

I changed also:       
   
- timesteps (between 50 000 and 1 000 000)
- hmax  (between 50 and 150)
- reward_scaling (between 1e-5 and 1e-3)    
- the training days and the technical indicator.

But always with the same result...

I will test the other tutorials of the set next week, and will report my results.

**Comment by skhonsha** [comment]
@Marneus 
Hi, I have this problem. Why doesn`t the ddpg algorithm train and all the outputs are the same? Did you solve the problem?
