### ISSUE TITLE
Using the BitcoinEnv class from env_btc_ccxt.py

### ISSUE THREAD

**Issue by JorisDigital** [AI4Finance-Foundation/FinRL#569]
Hi there, I am interested in trading a single crypto against fiat. Therefore I would really like to try and use the BitcoinEnv class from env_btc_ccxt.py. Do you have any example calling this class?

**Comment by Athe-kunal** [comment]
Hi @JorisDigital 
You can do the following

```
from finrl.finrl_meta.data_processor import DataProcessor

def get_arrays(start_date, end_date, ticker_list, data_source, time_interval, 
          technical_indicator_list, if_vix = True,
          **kwargs):
    
    #fetch data
    DP = DataProcessor(data_source, **kwargs)
    data = DP.download_data(ticker_list, start_date, end_date, time_interval)
    data = DP.clean_data(data)
    data = DP.add_technical_indicator(data, technical_indicator_list)
    if if_vix:
        data = DP.add_vix(data)
    price_array, tech_array, turbulence_array = DP.df_to_array(data, if_vix)
    return price_array, tech_array, turbulence_array

price_array, tech_array, turbulence_array = get_arrays(**pass in your arguments)
#Do pass all the arguments that you need according to the environment class
crypto_env = BitcoinEnv(price_ary=price_array, tech_ary = tech_array)
```

**Comment by JorisDigital** [comment]
Great thanks for your reply, I will try this soon and let you know how things are going.

**Comment by dimoboy** [comment]
> Great thanks for your reply, I will try this soon and let you know how things are going.

how it went ? i want to try it now but im stuck ! should i use stable baselines models ? is there better envs for bitcoin ?

**Comment by dimoboy** [comment]
> Hi @JorisDigital You can do the following
> 
> ```
> from finrl.finrl_meta.data_processor import DataProcessor
> 
> def get_arrays(start_date, end_date, ticker_list, data_source, time_interval, 
>           technical_indicator_list, if_vix = True,
>           **kwargs):
>     
>     #fetch data
>     DP = DataProcessor(data_source, **kwargs)
>     data = DP.download_data(ticker_list, start_date, end_date, time_interval)
>     data = DP.clean_data(data)
>     data = DP.add_technical_indicator(data, technical_indicator_list)
>     if if_vix:
>         data = DP.add_vix(data)
>     price_array, tech_array, turbulence_array = DP.df_to_array(data, if_vix)
>     return price_array, tech_array, turbulence_array
> 
> price_array, tech_array, turbulence_array = get_arrays(**pass in your arguments)
> #Do pass all the arguments that you need according to the environment class
> crypto_env = BitcoinEnv(price_ary=price_array, tech_ary = tech_array)
> ```

 i want to try it now but im stuck ! should i use stable baselines models ? is there better envs for bitcoin ?
