### ISSUE TITLE
DRL Ensemble Strategy error: TypeError: __init__() missing 1 required positional argument: 'tech_indicator_list'

### ISSUE THREAD

**Issue by sean1111111111** [AI4Finance-Foundation/FinRL#575]
I run the code:df_summary = ensemble_agent.run_ensemble_strategy(A2C_model_kwargs,
                                                 PPO_model_kwargs,
                                                 DDPG_model_kwargs,
                                                 timesteps_dict)
But get the error:
    23 
     24     def __init__(self, env_fns: List[Callable[[], gym.Env]]):
---> 25         self.envs = [fn() for fn in env_fns]
     26         env = self.envs[0]
     27         VecEnv.__init__(self, len(env_fns), env.observation_space, env.action_space)

~/Downloads/FinRL-master/finrl/agents/stablebaselines3/models.py in <lambda>()
    425             self.train_env = DummyVecEnv(
    426                 [
--> 427                     lambda: StockTradingEnv(
    428                         train,
    429                         self.stock_dim,

TypeError: __init__() missing 1 required positional argument: 'tech_indicator_list'

**Comment by ExtEEd** [comment]
Yes, it is a bug. In master/finrl/finrl_meta/env_stock_trading/env_stocktrading.py - _num_stock_shares_ is required parameter. But in master/finrl/agents/stablebaselines3/models.py in function _run_ensemble_strategy_ this parameter is absent. 
You can repair this bug by changing _run_ensemble_strategy_ function like this:

`lambda: StockTradingEnv(
                        train,
                        self.stock_dim,
                        self.hmax,
                        self.initial_amount,
                        [],
                        self.buy_cost_pct,
                        self.sell_cost_pct,
                        self.reward_scaling,
                        self.state_space,
                        self.action_space,
                        self.tech_indicator_list,
                        print_verbosity=self.print_verbosity,
                    )`

**Comment by sean1111111111** [comment]
Thank you for your help! But after I change it, it gets another error...Could you help me revise it? Thanks!

ValueError                                Traceback (most recent call last)
<ipython-input-21-f7216cfcab9f> in <module>
----> 1 df_summary = ensemble_agent.run_ensemble_strategy(A2C_model_kwargs,
      2                                                  PPO_model_kwargs,
      3                                                  DDPG_model_kwargs,
      4                                                  timesteps_dict)

~/Downloads/FinRL-master/finrl/agents/stablebaselines3/models.py in run_ensemble_strategy(self, A2C_model_kwargs, PPO_model_kwargs, DDPG_model_kwargs, timesteps_dict)
    466                 "a2c", self.train_env, policy="MlpPolicy", model_kwargs=A2C_model_kwargs
    467             )
--> 468             model_a2c = self.train_model(
    469                 model_a2c,
    470                 "a2c",

~/Downloads/FinRL-master/finrl/agents/stablebaselines3/models.py in train_model(model, model_name, tb_log_name, iter_num, total_timesteps)
    198     @staticmethod
    199     def train_model(model, model_name, tb_log_name, iter_num, total_timesteps=5000):
--> 200         model = model.learn(
    201             total_timesteps=total_timesteps,
    202             tb_log_name=tb_log_name,

~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/a2c/a2c.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    189     ) -> "A2C":
    190 
--> 191         return super(A2C, self).learn(
    192             total_timesteps=total_timesteps,
    193             callback=callback,

~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    240         iteration = 0
    241 
--> 242         total_timesteps, callback = self._setup_learn(
    243             total_timesteps, eval_env, callback, eval_freq, n_eval_episodes, eval_log_path, reset_num_timesteps, tb_log_name
    244         )

~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/common/base_class.py in _setup_learn(self, total_timesteps, eval_env, callback, eval_freq, n_eval_episodes, log_path, reset_num_timesteps, tb_log_name)
    427         # Avoid resetting the environment when calling ``.learn()`` consecutive times
    428         if reset_num_timesteps or self._last_obs is None:
--> 429             self._last_obs = self.env.reset()  # pytype: disable=annotation-type-mismatch
    430             self._last_episode_starts = np.ones((self.env.num_envs,), dtype=bool)
    431             # Retrieve unnormalized observation for saving into the buffer

~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py in reset(self)
     60         for env_idx in range(self.num_envs):
     61             obs = self.envs[env_idx].reset()
---> 62             self._save_obs(env_idx, obs)
     63         return self._obs_from_buf()
     64 

~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py in _save_obs(self, env_idx, obs)
     90         for key in self.keys:
     91             if key is None:
---> 92                 self.buf_obs[key][env_idx] = obs
     93             else:
     94                 self.buf_obs[key][env_idx] = obs[key]

ValueError: could not broadcast input array from shape (147,) into shape (175,)

**Comment by David-sudo-spec** [comment]
Could you help me revise it? Thanks!
![image](https://user-images.githubusercontent.com/78137768/164369364-f9179e94-3fe0-4b42-88f6-359409668834.png)

**Comment by ExtEEd** [comment]
**sean1111111111**, you forget that _num_stock_shares_ is a list. You need to create a list with zeros of length equals the number of assets. If you try to work with 5 assets, _num_stock_shares_ must be like [0,0,0,0,0].

**Comment by ExtEEd** [comment]
**David-sudo-spec**, what is this? I think, it doesn't matter to the question of this issue...

**Comment by daeilcha** [comment]
I got this to work by using ExtEEd's fix above, except I used `[0] * self.stock_dim` instead of just `[0]` ... I repeated this process for any occurrence of StockTradingEnv() in models.py (I counted 5 total). 

After the fix, I encountered another error in the StockTradingEnv class within env_stocktrading.py ... I fixed this by replacing any occurrence of `self.buy_cost_pct[index]` with just `self.buy_cost_pct`, and `self.sell_cost_pct[index]` with just `self.sell_cost_pct` 

Hope that helps!

**Comment by David-sudo-spec** [comment]
Thank&nbsp;you&nbsp;very&nbsp;much&nbsp;for&nbsp;your&nbsp;help,&nbsp;I&nbsp;appreciate&nbsp;it.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AI4Finance-Foundation/FinRL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月23日(星期六) 凌晨3:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AI4Finance-Foundation/FinRL] DRL Ensemble Strategy error: TypeError: __init__() missing 1 required positional argument: 'tech_indicator_list' (Issue #575)





 
I got this to work by using ExtEEd's fix above, except I used [0] * self.stock_dim instead of just [0] ... I repeated this process for any occurrence of StockTradingEnv() in models.py (I counted 5 total).
 
After the fix, I encountered another error in the StockTradingEnv class within env_stocktrading.py ... I fixed this by replacing any occurrence of self.buy_cost_pct[index] with just self.buy_cost_pct, and self.sell_cost_pct[index] with just self.sell_cost_pct
 
Hope that helps!

**Comment by BinhKieu82** [comment]
> 

Hi,
I followed @daeilcha  guide but got the following error, could you give a hand please, thank you:

`TypeError                                 Traceback (most recent call last)
e:\temp\RL\P4_Finance\FinRL\tutorials\2-Advance\FinRL_Ensemble_StockTrading_ICAIF_2020.ipynb Cell 38' in <cell line: 1>()
----> 1 df_summary = ensemble_agent.run_ensemble_strategy(A2C_model_kwargs,
      2                                                  PPO_model_kwargs,
      3                                                  DDPG_model_kwargs,
      4                                                  timesteps_dict)

File e:\temp\RL\P4_Finance\FinRL\finrl\agents\stablebaselines3\models.py:469, in DRLEnsembleAgent.run_ensemble_strategy(self, A2C_model_kwargs, PPO_model_kwargs, DDPG_model_kwargs, timesteps_dict)
    465 print("======A2C Training========")
    466 model_a2c = self.get_model(
    467     "a2c", self.train_env, policy="MlpPolicy", model_kwargs=A2C_model_kwargs
    468 )
--> 469 model_a2c = self.train_model(
    470     model_a2c,
    471     "a2c",
    472     tb_log_name=f"a2c_{i}",
    473     iter_num=i,
    474     total_timesteps=timesteps_dict["a2c"],
    475 )  # 100_000
    477 print(
    478     "======A2C Validation from: ",
    479     validation_start_date,
    480     "to ",
    481     validation_end_date,
    482 )
    483 val_env_a2c = DummyVecEnv(
    484     [
    485         lambda: StockTradingEnv(
   (...)
    503     ]
    504 )

File e:\temp\RL\P4_Finance\FinRL\finrl\agents\stablebaselines3\models.py:200, in DRLEnsembleAgent.train_model(model, model_name, tb_log_name, iter_num, total_timesteps)
    198 @staticmethod
    199 def train_model(model, model_name, tb_log_name, iter_num, total_timesteps=5000):
--> 200     model = model.learn(
    201         total_timesteps=total_timesteps,
    202         tb_log_name=tb_log_name,
    203         callback=TensorboardCallback(),
    204     )
    205     model.save(
    206         f"{config.TRAINED_MODEL_DIR}/{model_name.upper()}_{total_timesteps // 1000}k_{iter_num}"
    207     )
    208     return model

File ~\AppData\Roaming\Python\Python38\site-packages\stable_baselines3\a2c\a2c.py:191, in A2C.learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    178 def learn(
    179     self,
    180     total_timesteps: int,
   (...)
    188     reset_num_timesteps: bool = True,
    189 ) -> "A2C":
--> 191     return super(A2C, self).learn(
    192         total_timesteps=total_timesteps,
    193         callback=callback,
    194         log_interval=log_interval,
    195         eval_env=eval_env,
    196         eval_freq=eval_freq,
    197         n_eval_episodes=n_eval_episodes,
    198         tb_log_name=tb_log_name,
    199         eval_log_path=eval_log_path,
    200         reset_num_timesteps=reset_num_timesteps,
    201     )

File ~\AppData\Roaming\Python\Python38\site-packages\stable_baselines3\common\on_policy_algorithm.py:250, in OnPolicyAlgorithm.learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    246 callback.on_training_start(locals(), globals())
    248 while self.num_timesteps < total_timesteps:
--> 250     continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
    252     if continue_training is False:
    253         break

File ~\AppData\Roaming\Python\Python38\site-packages\stable_baselines3\common\on_policy_algorithm.py:178, in OnPolicyAlgorithm.collect_rollouts(self, env, callback, rollout_buffer, n_rollout_steps)
    175 if isinstance(self.action_space, gym.spaces.Box):
    176     clipped_actions = np.clip(actions, self.action_space.low, self.action_space.high)
--> 178 new_obs, rewards, dones, infos = env.step(clipped_actions)
    180 self.num_timesteps += env.num_envs
    182 # Give access to local variables

File ~\AppData\Roaming\Python\Python38\site-packages\stable_baselines3\common\vec_env\base_vec_env.py:162, in VecEnv.step(self, actions)
    155 """
    156 Step the environments with the given action
    157 
    158 :param actions: the action
    159 :return: observation, reward, done, information
    160 """
    161 self.step_async(actions)
--> 162 return self.step_wait()

File ~\AppData\Roaming\Python\Python38\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py:43, in DummyVecEnv.step_wait(self)
     41 def step_wait(self) -> VecEnvStepReturn:
     42     for env_idx in range(self.num_envs):
---> 43         obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] = self.envs[env_idx].step(
     44             self.actions[env_idx]
     45         )
     46         if self.buf_dones[env_idx]:
     47             # save final observation where user can get it, then reset
     48             self.buf_infos[env_idx]["terminal_observation"] = obs

File e:\temp\RL\P4_Finance\FinRL\finrl\finrl_meta\env_stock_trading\env_stocktrading.py:304, in StockTradingEnv.step(self, actions)
    299     # print(f'take sell action after : {actions[index]}')
    300     # print(f"Num shares after: {self.state[index+self.stock_dim+1]}")
    302 for index in buy_index:
    303     # print('take buy action: {}'.format(actions[index]))
--> 304     actions[index] = self._buy_stock(index, actions[index])
    306 self.actions_memory.append(actions)
    308 # state: s -> s+1

File e:\temp\RL\P4_Finance\FinRL\finrl\finrl_meta\env_stock_trading\env_stocktrading.py:179, in StockTradingEnv._buy_stock(self, index, action)
    177 # perform buy action based on the sign of the action
    178 if self.turbulence_threshold is None:
--> 179     buy_num_shares = _do_buy()
    180 else:
    181     if self.turbulence < self.turbulence_threshold:

File e:\temp\RL\P4_Finance\FinRL\finrl\finrl_meta\env_stock_trading\env_stocktrading.py:158, in StockTradingEnv._buy_stock.<locals>._do_buy()
    154 def _do_buy():
    155     if self.state[index + 2*self.stock_dim+ 1] !=True: # check if the stock is able to buy
    156     # if self.state[index + 1] >0:
    157         # Buy only if the price is > 0 (no missing data in this particular date)
--> 158         available_amount = self.state[0] / (self.state[index + 1]*(1 + self.buy_cost_pct[index])) # when buying stocks, we should consider the cost of trading when calculating available_amount, or we may be have cash<0
    159         # print('available_amount:{}'.format(available_amount))
    160 
    161         # update balance
    162         buy_num_shares = min(available_amount, action)

TypeError: 'float' object is not subscriptable`

**Comment by daeilcha** [comment]
@BinhKieu82 Make sure to follow the second part of my fix -- see below:

After the fix, I encountered another error in the `StockTradingEnv` class within `env_stocktrading.py` ... I fixed this by replacing any occurrence of `self.buy_cost_pct[index]` with just `self.buy_cost_pct`, and `self.sell_cost_pct[index]` with just `self.sell_cost_pct`

**Comment by BinhKieu82** [comment]
@daeilcha , my mistake, i just seen on the models.py. Thanks alot

**Comment by bschleter** [comment]
@daeilcha I don't like even coming here to reach out and know you found solution to debug it. I've looked at this issue for a few days now, found this thread yesterday. Was able to fix the `init() missing tech_indicator_list` however unable to fix the float object issue like stated above. 

I've done what you said within env_stocktrading.py and obviously the fixes within models.py. Still at a loss. Checked to make sure none missing. 


**Heres's a small excerpt.** 
    156             # if self.state[index + 1] >0:
    157                 # Buy only if the price is > 0 (no missing data in this particular date)
--> 158                 available_amount = self.state[0] / (self.state[index + 1]*(1 + self.buy_cost_pct))
    159                 # [index] -when buying stocks, we should consider the cost of trading when calculating available_amount, or we may be have cash<0
    160                 # print('available_amount:{}'.format(available_amount))

TypeError: 'float' object is not subscriptable

**Comment by daeilcha** [comment]
@bschleter  Hm that's strange. I'm assuming you reloaded your kernel and re-imported all your dependencies? If you did, then I'm not sure. Just fyi, I forked the whole repo and made a bunch of edits to make it run for my purposes... you can check it out here: https://github.com/daeilcha/FinRL_DC

**Comment by bschleter** [comment]
@daeilcha Apologize for wasting your time, I had restarted the kernel earlier, made half of the changes, reloaded the dependencies and thought I was good. Went and officially restarted kernel in notebook again, and I am FINALLY training. Took me 4 days. 

Forgive me, I have no formal training and am an amateur, part time. 

I future I will be taking ganders at your fork to see other issues. I'm still confused a bit at the 'why' on the init() issue in the first place after reading on first class objects, but i'll learn.

**Comment by daeilcha** [comment]
@bschleter No problem, glad I could help.

**Comment by bbbbibir** [comment]
> Thank you for your help! But after I change it, it gets another error...Could you help me revise it? Thanks!
> 
> ValueError Traceback (most recent call last) in ----> 1 df_summary = ensemble_agent.run_ensemble_strategy(A2C_model_kwargs, 2 PPO_model_kwargs, 3 DDPG_model_kwargs, 4 timesteps_dict)
> 
> ~/Downloads/FinRL-master/finrl/agents/stablebaselines3/models.py in run_ensemble_strategy(self, A2C_model_kwargs, PPO_model_kwargs, DDPG_model_kwargs, timesteps_dict) 466 "a2c", self.train_env, policy="MlpPolicy", model_kwargs=A2C_model_kwargs 467 ) --> 468 model_a2c = self.train_model( 469 model_a2c, 470 "a2c",
> 
> ~/Downloads/FinRL-master/finrl/agents/stablebaselines3/models.py in train_model(model, model_name, tb_log_name, iter_num, total_timesteps) 198 @staticmethod 199 def train_model(model, model_name, tb_log_name, iter_num, total_timesteps=5000): --> 200 model = model.learn( 201 total_timesteps=total_timesteps, 202 tb_log_name=tb_log_name,
> 
> ~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/a2c/a2c.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps) 189 ) -> "A2C": 190 --> 191 return super(A2C, self).learn( 192 total_timesteps=total_timesteps, 193 callback=callback,
> 
> ~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps) 240 iteration = 0 241 --> 242 total_timesteps, callback = self._setup_learn( 243 total_timesteps, eval_env, callback, eval_freq, n_eval_episodes, eval_log_path, reset_num_timesteps, tb_log_name 244 )
> 
> ~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/common/base_class.py in _setup_learn(self, total_timesteps, eval_env, callback, eval_freq, n_eval_episodes, log_path, reset_num_timesteps, tb_log_name) 427 # Avoid resetting the environment when calling `.learn()` consecutive times 428 if reset_num_timesteps or self._last_obs is None: --> 429 self._last_obs = self.env.reset() # pytype: disable=annotation-type-mismatch 430 self._last_episode_starts = np.ones((self.env.num_envs,), dtype=bool) 431 # Retrieve unnormalized observation for saving into the buffer
> 
> ~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py in reset(self) 60 for env_idx in range(self.num_envs): 61 obs = self.envs[env_idx].reset() ---> 62 self._save_obs(env_idx, obs) 63 return self._obs_from_buf() 64
> 
> ~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py in _save_obs(self, env_idx, obs) 90 for key in self.keys: 91 if key is None: ---> 92 self.buf_obs[key][env_idx] = obs 93 else: 94 self.buf_obs[key][env_idx] = obs[key]
> 
> ValueError: could not broadcast input array from shape (147,) into shape (175,)



> Thank you for your help! But after I change it, it gets another error...Could you help me revise it? Thanks!
> 
> ValueError Traceback (most recent call last) in ----> 1 df_summary = ensemble_agent.run_ensemble_strategy(A2C_model_kwargs, 2 PPO_model_kwargs, 3 DDPG_model_kwargs, 4 timesteps_dict)
> 
> ~/Downloads/FinRL-master/finrl/agents/stablebaselines3/models.py in run_ensemble_strategy(self, A2C_model_kwargs, PPO_model_kwargs, DDPG_model_kwargs, timesteps_dict) 466 "a2c", self.train_env, policy="MlpPolicy", model_kwargs=A2C_model_kwargs 467 ) --> 468 model_a2c = self.train_model( 469 model_a2c, 470 "a2c",
> 
> ~/Downloads/FinRL-master/finrl/agents/stablebaselines3/models.py in train_model(model, model_name, tb_log_name, iter_num, total_timesteps) 198 @staticmethod 199 def train_model(model, model_name, tb_log_name, iter_num, total_timesteps=5000): --> 200 model = model.learn( 201 total_timesteps=total_timesteps, 202 tb_log_name=tb_log_name,
> 
> ~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/a2c/a2c.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps) 189 ) -> "A2C": 190 --> 191 return super(A2C, self).learn( 192 total_timesteps=total_timesteps, 193 callback=callback,
> 
> ~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps) 240 iteration = 0 241 --> 242 total_timesteps, callback = self._setup_learn( 243 total_timesteps, eval_env, callback, eval_freq, n_eval_episodes, eval_log_path, reset_num_timesteps, tb_log_name 244 )
> 
> ~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/common/base_class.py in _setup_learn(self, total_timesteps, eval_env, callback, eval_freq, n_eval_episodes, log_path, reset_num_timesteps, tb_log_name) 427 # Avoid resetting the environment when calling `.learn()` consecutive times 428 if reset_num_timesteps or self._last_obs is None: --> 429 self._last_obs = self.env.reset() # pytype: disable=annotation-type-mismatch 430 self._last_episode_starts = np.ones((self.env.num_envs,), dtype=bool) 431 # Retrieve unnormalized observation for saving into the buffer
> 
> ~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py in reset(self) 60 for env_idx in range(self.num_envs): 61 obs = self.envs[env_idx].reset() ---> 62 self._save_obs(env_idx, obs) 63 return self._obs_from_buf() 64
> 
> ~/Desktop/anaconda3/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py in _save_obs(self, env_idx, obs) 90 for key in self.keys: 91 if key is None: ---> 92 self.buf_obs[key][env_idx] = obs 93 else: 94 self.buf_obs[key][env_idx] = obs[key]
> 
> ValueError: could not broadcast input array from shape (147,) into shape (175,)


Apologize for wasting your time,I also encountered this problem, but I didn't understand what @ExtEEd  said about how to operate. I'm a noob.could you give a hand please, thank you
