### ISSUE TITLE
FinRL Raytune for Hyperparameter Optimization.ipynb failing on Colab

### ISSUE THREAD

**Issue by nos4a2** [AI4Finance-Foundation/FinRL#577]
Running the notebook on colab without any changes gives error in cell 15

```
analysis = run_optuna_tune()
```
```
2022-04-18 15:50:02,707	INFO services.py:1462 -- View the Ray dashboard at http://127.0.0.1:8265/
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-15-96808ebfef0e>](https://localhost:8080/#) in <module>()
----> 1 analysis = run_optuna_tune()

9 frames
[/usr/local/lib/python3.7/dist-packages/ray/_private/utils.py](https://localhost:8080/#) in get_system_memory()
    434     elif os.path.exists(memory_limit_filename_v2):
    435         with open(memory_limit_filename_v2, "r") as f:
--> 436             docker_limit = int(f.read())
    437 
    438     # Use psutil if it is available.

ValueError: invalid literal for int() with base 10: 'max\n'
```

**Comment by Athe-kunal** [comment]
Hi @nos4a2 
This error is not related to the tutorial, rather a version error I guess
Please do the following and let me know if it is fixed

`pip install int_date==0.1.8`

**Comment by nos4a2** [comment]
@Athe-kunal this pip install already exists in the notebook. I also, tried with latest version of `int_date` and running without the package. still the same issue

Notebook - 
https://github.com/AI4Finance-Foundation/FinRL/blob/49888ffbcd61736690e767c5e0ff60c4aa3671ec/tutorials/4-Optimization/FinRL_HyperparameterTuning_Raytune_RLlib.ipynb

**Comment by Athe-kunal** [comment]
Hi @nos4a2 
This seems like a Ray tune problem as in the error trace you can see
```
elif os.path.exists(memory_limit_filename_v2):
   with open(memory_limit_filename_v2, "r") as f:
   --> docker_limit = int(f.read())
```

While reading the memory, f.read() returns a string value which cannot be converted to an integer. We can raise an issue in the Ray tune community because earlier I didn't encounter this problem. This seems like a problem that originated recently.

**Comment by nos4a2** [comment]
@Athe-kunal Thanks, works with ray version 1.10.
