### ISSUE TITLE
no module named 'finrl_ meta. data_ processors. processor_ tusharepro

### ISSUE THREAD

**Issue by XksA-me** [AI4Finance-Foundation/FinRL#581]
Hi, I am trying to run the codes in FinRL/tutorials/3-Practical/FinRL_China_A_Share_Market.ipynb. When I am trying to run Import modules, I got an error: modulenotfounderror: no module named 'finrl_ meta. data_ processors. processor_ tusharepro'，I found in FinRL-Meta/finrl_meta/data_processors there is really no processors_ tusharepro.
![image](https://user-images.githubusercontent.com/43670614/164432048-64973f14-66bb-4c11-a2d9-30d8087ae878.png)

https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/tutorials_notebook/3-Practical/FinRL_China_A_Share_Market.ipynb

https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/3-Practical/FinRL_China_A_Share_Market.ipynb

I look forward to receiving your reply, thanks you.

**Comment by zhumingpassional** [comment]
please revise it to finrl_ meta. data_ processors.Tushare

We will update it in next days.

**Comment by XksA-me** [comment]
> please revise it to finrl_ meta. data_ processors.Tushare
> 
> We will update it in next days.

Thank you for your reply and look forward to update.

**Comment by XiaoYangLiu-FinRL** [comment]
We did another round of code refactoring… it is better now.
