### ISSUE TITLE
Minute-based model training issue (using minute data in FinRL)

### ISSUE THREAD

**Issue by YanchengHe** [AI4Finance-Foundation/FinRL#584]
Instead of training the model with daily-based data, I'm now trying to use the Price and Volume data every ten minutes to train the strategy. However, when building the environment, the shape of data doesn't correspond to the size of the State Space. The screenshots of the error message and the data preview are shown below.

<img width="925" alt="Screen Shot 2022-04-25 at 4 16 13 PM" src="https://user-images.githubusercontent.com/48344659/165048465-cdae2292-1ae8-408c-b1ba-344e13713b77.png">
<img width="896" alt="Screen Shot 2022-04-25 at 4 18 23 PM" src="https://user-images.githubusercontent.com/48344659/165048868-fc458295-3390-4f5d-83ea-a6b7fc46892d.png">

**Comment by zhumingpassional** [comment]
Which notebook did you run? Have you revised anything?

Some missing values may cause this problem.  can you  print it?

**Comment by BruceYanghy** [comment]
10-minute data: date,tic,time,price,headline_sentiment,situation_senti
Daily data by FinRL: OHLCV and technical indicators

@[YanchengHe](https://github.com/YanchengHe) use 10-minute data left outer join Daily data by FinRL, this is not recommended, instead YanchengHe should either calculate the 10-minute OHLCV and technical indicators and join them together, or  transform 10-minute data to daily data and join the FinRL table.

@[YanchengHe](https://github.com/YanchengHe) told me they want to get it running first. I think that's OK, but need to do a few checks:

1. Run: df.tic.value_counts() to make sure the data is matched between tics, the following data is not matched, some tickers have a lot of missing data
![image](https://user-images.githubusercontent.com/31713746/166708278-49accb19-b335-4322-814d-d6b2e0606688.png)
2. df['date'] =df['date'] + ' ' + df['TIME'], the DRL environment is incremented by date, this date should be unique, when you pick a random date out it should look like this
![image](https://user-images.githubusercontent.com/31713746/166709514-582221ae-b66c-4291-817d-0ddf13f2c15c.png)

**Comment by qinghuiKAKA** [comment]
@BruceYanghy 谢谢，我也遇到了这个问题，现在终于解决了，因为我将0值的行都删掉了，但是却导致每天不是所有股票都有数据了
