### ISSUE TITLE
Google Colab Tutorial Introduction has an issue

### ISSUE THREAD

**Issue by AI-Ahmed** [AI4Finance-Foundation/FinRL#594]
Hello there,
    First of all – thank you so much for sharing this incredible package for us to work with. I have been following you for a long time now, but I didn't have the time to start with your package before finishing working on the RL, itself. Now, I want to start with your tutorials, and I really find that you add lots of things to facilitate that for us. But, when I try to open the introduction notebooks on Google Colab, this is what I found!

![image](https://user-images.githubusercontent.com/72295771/165983235-e8ba4538-14dd-401a-b6f9-c44ae7d16f07.png)

Please, if you can, update the directories of your notebooks!

Thanks!!

**Comment by ZiyiXia** [comment]
Fixed, please checkout.
