### ISSUE TITLE
I cannot install FinRL

### ISSUE THREAD

**Issue by ConstantinosM** [AI4Finance-Foundation/FinRL#596]
It is impossible for me to install FinRL via `pip install git+https://github.com/AI4Finance-Foundation/FinRL.git` on my MAC. I get stuck in a loop:
![image](https://user-images.githubusercontent.com/25111975/166115646-bcbbc0ca-4f03-4ebe-93f3-2096806d472a.png)
 I looked at some other related posts but there is no solution for this problem.

**Comment by aidanmclaughlin** [comment]
Had same issue

**Comment by pbezz1** [comment]
Make sure you have MS C++ build tools installed.. A lot of ccxt* files are downloaded as part of the installation process.  It took me some hours to figure this out. I'm using a Windows 10 system.

**Comment by ConstantinosM** [comment]
@pbezz1 thank you for your response! I am on a Mac. I will update my answer to include this information.

**Comment by pbezz1** [comment]
I would estimate around 15 mins if you have all the pre-reqs in place. It depends on the hardware as well to some extent.

**Comment by ConstantinosM** [comment]
@XiaoYangLiu-FinRL why do you close the issue? It hasn't been resolved. I am on a Mac and I do have the recommended C++ compilers. Also I have installed ccxt (1.80) on my own but still FinRL installation gets into the loop i described above.

**Comment by XiaoYangLiu-FinRL** [comment]
https://ai4finance.medium.com/finrl-for-quantitative-finance-install-and-setup-tutorial-for-beginners-1db80ad39159

**Comment by ConstantinosM** [comment]
@XiaoYangLiu-FinRL I have followed these instructions already. As I mentioned above the installation is stuck when i use the pip command. And it gets stuck when it tries to install ccxt which I have already installed (and did not have the behavior it has when installing within the FinRL installation).

By the way when I use collab and use this command: `!pip install git+https://github.com/AI4Finance-LLC/FinRL-Library.git` everything is fine. The instructions in the post you sent me do not use the -Library specification. Do you know if this is an alternative?

**Comment by XiaoYangLiu-FinRL** [comment]
Should it be the following?    !pip install git+https://github.com/AI4Finance-Foundation/FinRL.git

**Comment by ConstantinosM** [comment]
Yes I use this one on my Mac and it seems that it gets stuck. Is there a reason that in FinRL tutorials, for installing FinRL in Google Colab, the `!pip install git+https://github.com/AI4Finance-LLC/FinRL-Library.git` is used instead?

**Comment by XiaoYangLiu-FinRL** [comment]
The reason is: it was old, not updated yet.

**Comment by ConstantinosM** [comment]
@XiaoYangLiu-FinRL all good! I managed to install it! I let it run about 10mins and it was done. Thanks a lot everyone for the help!
