### ISSUE TITLE
tutorials1-FinRL_PortfolioAllocation_NeurIPS_2020 can't train, it outputs "nan"

### ISSUE THREAD

**Issue by chenxiao1129** [AI4Finance-Foundation/FinRL#605]
i think i have the right data
![1](https://user-images.githubusercontent.com/54888819/167132366-95a644be-4403-42fb-869e-c16d26b07037.png)
but when at part6, i failed to train_model
![2](https://user-images.githubusercontent.com/54888819/167132435-5e76c918-29c3-4ee1-83f2-6c7db34fb16e.png)
i try to find the problem
it seems here where "features" is no "nan"
but after "mlp_extractor()", the "latent_pi" is a "nan" tensor
![3](https://user-images.githubusercontent.com/54888819/167132750-f0089f26-c051-489e-b491-c5fed50911af.png)

is there anybody know why this happen? and how to deal with it?

**Comment by Athe-kunal** [comment]
It seems like your model has diverged and while extracting policy using log, it leads to NaN values. You can try hyperparameters optimization, maybe the current ones are suboptimal and diverging the models. The tutorial for the same is [here](https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/4-Optimization/FinRL_HyperparameterTuning_using_Optuna_basic.ipynb)
