### ISSUE TITLE
I'm new to deep learning，I have completed the basic tutorial and seen the results of the backtest，But when I use a model to make a prediction, I can't always predict the outcome of the current time or the outcome of the previous day. What should I do?

### ISSUE THREAD

**Issue by Wifi365** [AI4Finance-Foundation/FinRL#610]

**Comment by Wifi365** [comment]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/63989935/167806017-1f860ec5-5bd8-4181-a668-516b73d0a172.png">
I ran my code at 4pm on May 11th，My data is up to May 11th

**Comment by Wifi365** [comment]
I don't understand. If I can only predict the previous day's data, how can I apply it to reality

**Comment by XiaoYangLiu-FinRL** [comment]
Could you please check what it means by "prediction" here?   Usually, an agents's output is "actions", say "buy or sell #shares".

**Comment by Wifi365** [comment]
I'm not familiar with many of the terms of deep learning, so I'll try to be more clear and hopefully help me out，`df_account_value,df_actions = DRLAgent.DRL_prediction(model=trained_ddpg,environment=e_trade_gym)`，When I use this method，The df_action I output has only the previous day and no data for the current day，For example：When I used the model to output actions on the night of May 11, my data contained data from May 11, but I could only output actions for May 10
<img width="812" alt="image" src="https://user-images.githubusercontent.com/63989935/167975423-cf52841f-6ede-49f9-b1fe-a4cf0abe0b54.png">

**Comment by XiaoYangLiu-FinRL** [comment]
Would you like to check the calendar?  Sometimes it may be not in your time zone.

**Comment by Wifi365** [comment]
I found the reason. I tested it on China's a shares. It shows the date of the previous day, but its corresponding action is current
