### ISSUE TITLE
能不能提帮忙供一个雅虎以外的数据资源，方便大陆用户。

### ISSUE THREAD

**Issue by time888** [AI4Finance-Foundation/FinRL#614]
Yahoo .
2021 年 11 月 1 日起，用户将无法从中国大陆使用 Yahoo 的产品与服务。这并不影响 Yahoo 在全球其他地方的产品及服务。我们感谢你一直以來的支持。

**Comment by XiaoYangLiu-FinRL** [comment]
https://github.com/AI4Finance-Foundation/FinRL-Meta
There are several data sources already in FinRL and FinRL-Meta, say TuShare, JoinQuant, Baostock

**Comment by zhumingpassional** [comment]
@time888 You can change the data source by revising the code. Currently, finrl meta supports more data source.
