### ISSUE TITLE
Stock trading vs Portfolio Allocation

### ISSUE THREAD

**Issue by neerajchhimwal** [AI4Finance-Foundation/FinRL#617]
After going through the tutorials provided, I can't understand what are the points of difference between these use cases. 

**Action spaces** are different only in the sense that for Stock trading, it says "buy this number of shares" and for Portfolio allocation, it says "make this the weightage of this stock in my portfolio" which is essentially the same thing.

**States** are different between the two as covariance matrix is used in one wheres close price etc. are used in another. Also the concept of "balance" is used in stock trading but not in portfolio allocation problem.

Having difficulty in understanding what is the core difference between the two? 
We're starting with a fixed bucket of stocks / assets in both the cases.

**Comment by XiaoYangLiu-FinRL** [comment]
Portfolio allocation has weight sum to be 1, and perform rebalance .

**Comment by XiaoYangLiu-FinRL** [comment]
The problem modeling is clearly described in the papers, please check them.
