### ISSUE TITLE
hmax for portfolio allocation vs stock trading

### ISSUE THREAD

**Issue by neerajchhimwal** [AI4Finance-Foundation/FinRL#618]
hmax parameter can be seen in the "step" method of the stock trading environment, but it's only being initialised and not used in the "step" method for portfolio allocation environment.

Can someone please explain what is the relevance and intuition behind hmax (max shares that can be traded) for both these use cases? Thanks

**Comment by Athe-kunal** [comment]
The actor-network outputs a distribution between -1 to 1. So hmax helps the agent to go beyond transacting a single share.
