### ISSUE TITLE
Make finrl.test() 's output directly usable with portfolio analysis tool

### ISSUE THREAD

**Issue by dev590t** [AI4Finance-Foundation/FinRL#621]
`finrl.test()` return a list of int of portfolio value, it doesn't contain date data:
```
from finrl.test import test
account_value_sb3=test(start_date = '2021-10-18', 
                      end_date = '2021-10-19',
...
                      net_dimension = 512)
account_value_sb3

output: 
[1000000.0,
 999698.6172275314,
 999391.9308182714,
...
```

But portfolio analysis tool(like pyfolio or quantstats) expected 1 serie of (date,int). We can't analyze the performance of test():
```
import quantstats as qs
qs.reports.full(returns = pd.Series(account_value_sb3))

output:
AttributeError: 'int' object has no attribute 'days'
```

I propose `finrl.test()` return a serie of (date,int), such as we can directly use portfolio analysis tool on.

**Comment by XiaoYangLiu-FinRL** [comment]
@dev590t Do you know how to submit a Pull Request?

**Comment by XiaoYangLiu-FinRL** [comment]
Sorry for the delay of code review. Will update soon. Thanks!
