### ISSUE TITLE
ValueError when trying to use non Yahoo Finance data

### ISSUE THREAD

**Issue by george-adams1** [AI4Finance-Foundation/FinRL#625]
I have been using the FinRL multiple stock fundamental tutorial for a while and everything works great. However, when I try and change the data to my custom data, I keep getting a ValueError. 
`ValueError: could not broadcast input array from shape (6341,) into shape (32997,)`
Any idea how to fix this? One of my guesses is that there might be an issue with how the state_space/action_space is defined for my data as it is not all ratios. 
```
stock_dimension = len(train.tic.unique())
state_space = 1 + 2 * stock_dimension + len(ratio_list) * stock_dimension
print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")
env_kwargs = {
    "hmax": 100, 
    "initial_amount": 1000000, 
    "buy_cost_pct": 0,
    "sell_cost_pct": 0,
    "state_space": state_space,
    "stock_dim": stock_dimension,
    "tech_indicator_list": ratio_list, 
    "action_space": stock_dimension,
    "reward_scaling": 1e-4
```

**Comment by zhumingpassional** [comment]
We revised several params:
"buy_cost_pct": [0] * stock_dim,
"sell_cost_pct": [0] * stock_dim,

If you encounter such problems, you can print and check the states and actions.
