### ISSUE TITLE
Negative stock holding while trading 

### ISSUE THREAD

**Issue by kelvinlyy** [AI4Finance-Foundation/FinRL#630]
**Describe the bug**
Using `DRLAgent.DRL_prediction` to simulate trading, some stocks are sold more than the available amount.

**To Reproduce**
Normal Usage of the default FinRL_StockTrading_NeurIPS_2018.ipynb could trigger this error.
And to make it more visible, I changed the `initial_amount` = 1000 and use a less stock tickers in trading.

Here's the notebook I used to visualize the bug:
https://colab.research.google.com/drive/1oe5knZraM_ObbEgffwblE8PEHHZHiCD9

Please note that the colab environment isn't installed the required Python packages. You need to download the notebook to replicate the results. And since I could not find a way to make the results deterministic, you may need to try a few times to trigger the error.

**Expected behavior**
Stock holding should always be >=0 while trading

**Screenshots**
Scroll to the bottom of the notebook, there are cumulative inventories of stock holdings which are negative.

**Desktop (please complete the following information):**
MacOS 12.4

**Comment by kelvinlyy** [comment]
Seems there is a bug in `FinRL/finrl/finrl_meta/env_stock_trading/env_stocktrading.py` line 158:

`available_amount = self.state[0] / (self.state[index + 1]*(1 + self.buy_cost_pct[index]))` results in a float number for available_amount and the amount of stocks bought

Changing to `available_amount = self.state[0] // (self.state[index + 1]*(1 + self.buy_cost_pct[index]))` solves the problem


I opened a pull request in: https://github.com/AI4Finance-Foundation/FinRL/pull/631

**Comment by zhumingpassional** [comment]
Thanks for your valuable codes.

We will check it.
