### ISSUE TITLE
Refactor FinRL and FinRL-Meta

### ISSUE THREAD

**Issue by zhumingpassional** [AI4Finance-Foundation/FinRL#634]
The AI4Finance community will refactor FinRL and FinRL-Meta following the principles of software engineering. 

If anyone is interested in this work, please send CV to my email: zhumingpassional@gmail.com

**Comment by zhumingpassional** [comment]
You are welcome. 

We will first refactor FinRL-Meta, and then move FinRL-Meta to FinRL and refactor FinRL. For detailed plans, we will list them in Azure DevOps.

Could you tell me your Azure DevOps account? I will add you as a member.

**Comment by zhumingpassional** [comment]
![未命名](https://user-images.githubusercontent.com/43677883/176629676-f73a1aac-6b43-40f5-a8f3-0cec136c8715.png)

**Comment by DominiqueGarmier** [comment]
oh perhaps its because my account is liked to github? is there an option to add a github user?

**Comment by zhumingpassional** [comment]
I tried your github user, but failed. 

![image](https://user-images.githubusercontent.com/43677883/176630692-15291401-cb05-415c-8aee-998d62c3df1a.png)

**Comment by DominiqueGarmier** [comment]
<img width="231" alt="image" src="https://user-images.githubusercontent.com/42445422/176632759-1326e69d-fcdf-4bf4-b961-01b17546cf8b.png">
try this

**Comment by DominiqueGarmier** [comment]
well i tried inviting myself from a sencond account and nothing seems to work there either

**Comment by DominiqueGarmier** [comment]
ok so i created a new account using my university email: dgarmier@ethz.ch, there i was able to invite myself from another account.

**Comment by zhumingpassional** [comment]
I added dgarmier@ethz.ch
![image](https://user-images.githubusercontent.com/43677883/176660893-0c2ee275-c81b-401a-893e-906aacad2b86.png)

**Comment by DominiqueGarmier** [comment]
yes! it finally worked

**Comment by zhumingpassional** [comment]
we will use github projects as software engineering tool, I will invite you.

**Comment by zhumingpassional** [comment]
Pls accept it in github. Thanks.

**Comment by sjmitche9** [comment]
Hi @zhumingpassional it would be a privilege to help work on this.  I've done a fair bit of work on finrl-meta since I forked it a few months ago.

**Comment by zhumingpassional** [comment]
@sjmitche9 thanks for your interest. I will invite you as a collaborator.
