### ISSUE TITLE
AttributeError on stablebaselines3.model.py - DRL_prediction_load_from_file

### ISSUE THREAD

**Issue by varunpan** [AI4Finance-Foundation/FinRL#647]
**Describe the bug**
When I run the below code I get an ` AttributeError: 'StockTradingEnv' object has no attribute 'initial_total_asset'` error. I checked the in the Stablebaselines3.models.py file, for the DRL_prediction_load_from_file function it refers to "inital_total_asset" as a param in lines 143 and 154. 

I was able to get around this by change these lines to "initial_amount". However, are the "initial_amount" and "initial_total_asset" are the same and replaceable in this context?

**To Reproduce**
```
env_kwargs = {
    "hmax": 100,
    "initial_amount": 1000000,
    "num_stock_shares": num_stock_shares,
    "sell_cost_pct": [0] * stock_dimension,
    "state_space": state_space,
    "stock_dim": stock_dimension,
    "tech_indicator_list": config.INDICATORS,
    "action_space": stock_dimension,
    "reward_scaling": 1e-4
}

e_train_gym = StockTradingEnv(df=train, **env_kwargs)

env_train, _ = e_train_gym.get_sb_env()
print(type(env_train))

trade = data_split(df,'2020-07-01', '2022-05-30')

e_trade_gym = StockTradingEnv(df=trade, **env_kwargs)

df_daily_return, df_actions = DRLAgent.DRL_prediction_load_from_file(model_name="ppo", environment=e_trade_gym,cwd="trained_ppo")

```

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Python: 3.9

**Comment by Athe-kunal** [comment]
Yeah initial_total_asset is part of this environment: Numpy [env](https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/finrl_meta/env_stock_trading/env_stocktrading_np.py#L54). We need to have unified names for the variables

**Comment by Athe-kunal** [comment]
Yeah you need to do changes [here](https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/agents/stablebaselines3/models.py#L111)
