### ISSUE TITLE
Error when running Stock_NeurIPS2018.ipynb

### ISSUE THREAD

**Issue by zhuangh7** [AI4Finance-Foundation/FinRL#672]
![image](https://user-images.githubusercontent.com/16149477/178142143-57e4a56d-42c3-4a11-bd20-5fa4e1c977b0.png)
Running the ipynb file, but failed when construct a gym env.
get exception:
ValueError: could not broadcast input array from shape (7860,) into shape (291,)

And I notice that the state num cal before is correct 291.
![image](https://user-images.githubusercontent.com/16149477/178142187-269b693c-aff3-4a67-96c8-7839a376a2e7.png)

**To Reproduce**
1. run scripts in the Stock_NeurIPS2018.ipynb in the repo root.
2. error when running "Environment for Training".

**Comment by zhumingpassional** [comment]
sorry for delayed response. we will test it. recently, we are refactoring finrl, which may cause errors.

**Comment by Jinhao61** [comment]
Just ran into the same error. The only thing I change in Stock_NeurIPS2018.ipynb was changing `finrl_meta` to `meta` when importing the packages.
