### ISSUE TITLE
speed up Alpaca download_data 

### ISSUE THREAD

**Issue by dev590t** [AI4Finance-Foundation/FinRL#685]
## Is your feature request related to a problem? 
Alpaca download_data is very very slow because it make few query to get data. And the time increase linearly with the amount of data we want : https://github.com/AI4Finance-Foundation/FinRL/blob/6c0874d0e94e06eafee163cb7c585667a04d63eb/finrl/meta/data_processors/processor_alpaca.py#L38

## Proposition
However, it is possible to get all data with one query in one second for any quantity of data:
```
from alpaca_trade_api.rest import REST, TimeFrame
api = REST()
api.get_bars(DOW_30_TICKER, TimeFrame.Hour, "2021-06-08", "2021-06-08", adjustment='raw').df
```

Why AlpacaProcessor.download_data doesn't download all data in one query?

**Comment by zhumingpassional** [comment]
@dev590t 

Thanks for your suggestion. Have you test it? If it works, we hope you to submit a PR.

**Comment by dev590t** [comment]
Yes, I will send a PR when I will be available. I

**Comment by zhumingpassional** [comment]
Anyone can submit PR.

pls try again.

**Comment by dev590t** [comment]
What is the exact specification of download_data? It seem download_data give a different set of data than `get_bars`.

For instance:
```
from alpaca_trade_api.rest import REST, TimeFrame
api = REST()
start_date = '2021-10-01'
end_date = '2021-10-05'
data_2 = api.get_bars(DOW_30_TICKER,candle_time_interval , start_date, end_date, adjustment='raw').df

DP = DataProcessor(data_source = 'alpaca',
                  API_KEY = API_KEY, 
                  API_SECRET = API_SECRET, 
                  API_BASE_URL = API_BASE_URL
                  )
data = DP.download_data(start_date = '2021-10-01', 
                        end_date = '2021-10-05',
                        ticker_list = ticker_list, 
                        time_interval= candle_time_interval)

data_2.loc[data_2['symbol'] == 'AAPL'] # give data since 2021-10-01 08:00:00+00:00 to 2021-10-05 23:45:00+00:00

data.loc[data['tic'] == 'AAPL'] # give data since 2021-10-01 13:30:00 to 2021-10-05 19:45:00
```

**Comment by zhumingpassional** [comment]
@dev590t 
You used the data processor in finrl-meta. It considers the time zone. pls read the code.

start_date = pd.Timestamp(self.start_date, tz=self.time_zone)
end_date = pd.Timestamp(self.end_date, tz=self.time_zone) + pd.Timedelta(days=1)

**Comment by dev590t** [comment]
I have read the code, but some part of code isn't clear to me. That is what I have understand:
```
def download_data(
        self, ticker_list, start_date, end_date, time_interval
    ):
'''
ticker_list : list string of ticket
time_interval: time interval
start_date : start date of America/New_York time
end_date : end date of America/New_York time

The function tries to retrieve the data of the opening time of the New York Stock Exchange (NYSE) (from 9:30 am to 4:00 pm), between the start date and the end date, from the Alpaca server.  
'''
```

I can't understand what this part of [code](https://github.com/AI4Finance-Foundation/FinRL/blob/322e51225e0b626ae0526da4c78c1203293b8b68/finrl/meta/data_processors/processor_alpaca.py#L47) try doing:
```
            if date.isoformat()[-14:-6] == "01:00:00":
                date = date - pd.Timedelta("01:00:00")
            elif date.isoformat()[-14:-6] == "23:00:00":
                date = date + pd.Timedelta("01:00:00")
            if date.isoformat()[-14:-6] != "00:00:00":
                raise ValueError("Timezone Error")
```

**Comment by dev590t** [comment]
Ok, I think I don't need understand that part of code. Because `date` is used as indicator for the while loop; and I don't need the loop because I will remove the while loop.
