### ISSUE TITLE
Dead links in First Glance

### ISSUE THREAD

**Issue by kabua** [AI4Finance-Foundation/FinRL#692]
[First Glance](https://finrl.readthedocs.io/en/latest/start/first_glance.html)

The [notebook](https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/1-Introduction/FinRL_StockTrading_NeurIPS_2018.ipynb) and [Colab](https://colab.research.google.com/github/AI4Finance-Foundation/FinRL/blob/master/FinRL_StockTrading_NeurIPS_2018.ipynb) links are dead.

It appears, from github that the file was renamed in Jun and then deleted in Jul. Why? and what's replacing it? Should not have the documentation been updated when the file was renamed and then again when the file was deleted?

**Comment by XiaoYangLiu-FinRL** [comment]
Please check here: https://github.com/AI4Finance-Foundation/FinRL/blob/master/Stock_NeurIPS2018.ipynb

**Comment by XiaoYangLiu-FinRL** [comment]
We updated. Thanks!
