### ISSUE TITLE
 ModuleNotFoundError: No module named 'finrl_meta'ocessor import DataProcessor

### ISSUE THREAD

**Issue by Daiiszuki** [AI4Finance-Foundation/FinRL#693]
I'm' trying out finrl for the first time, I used 
`from finrl_meta.data_processor import DataProcessor`

but got 

`
ModuleNotFoundError: No module named 'finrl_meta'`

Using google collab.

Any suggestions?

**Comment by XiaoYangLiu-FinRL** [comment]
Please try "meta",  not "finrl_meta".  Thx.

**Comment by zhumingpassional** [comment]
if you use finrl-meta, pls download https://github.com/AI4Finance-Foundation/FinRL-Meta.
