### ISSUE TITLE
python 3.9.9 'Failed to convert value(s) to axis units: (NaT, Timestamp('2022-08-19 00:00:00+0000', tz='UTC'))

### ISSUE THREAD

**Issue by thistleknot** [AI4Finance-Foundation/FinRL#700]
**Describe the bug**

**To Reproduce**
run backtest_plot with default data

Run
https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/1-Introduction/Stock_Fundamental.ipynb

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\matplotlib\axis.py:1506, in Axis.convert_units(self, x)
   1505 try:
-> 1506     ret = self.converter.convert(x, self.units, self)
   1507 except Exception as e:

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\pandas\plotting\_matplotlib\converter.py:210, in PeriodConverter.convert(values, units, axis)
    209 else:
--> 210     values = PeriodConverter._convert_1d(values, units, axis)
    211 return values

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\pandas\plotting\_matplotlib\converter.py:229, in PeriodConverter._convert_1d(values, units, axis)
    228 elif isinstance(values, (list, tuple, np.ndarray, Index)):
--> 229     return [get_datevalue(x, axis.freq) for x in values]
    230 return values

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\pandas\plotting\_matplotlib\converter.py:229, in <listcomp>(.0)
    228 elif isinstance(values, (list, tuple, np.ndarray, Index)):
--> 229     return [get_datevalue(x, axis.freq) for x in values]
    230 return values

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\pandas\plotting\_matplotlib\converter.py:237, in get_datevalue(date, freq)
    236 elif isinstance(date, (str, datetime, pydt.date, pydt.time, np.datetime64)):
--> 237     return Period(date, freq).ordinal
    238 elif (
    239     is_integer(date)
    240     or is_float(date)
    241     or (isinstance(date, (np.ndarray, Index)) and (date.size == 1))
    242 ):

AttributeError: 'NaTType' object has no attribute 'ordinal'

The above exception was the direct cause of the following exception:

ConversionError                           Traceback (most recent call last)
Input In [68], in <cell line: 17>()
      2 get_ipython().run_line_magic('matplotlib', 'inline')
      3 # S&P 500: ^GSPC
      4 # Dow Jones Index: ^DJI
      5 # NASDAQ 100: ^NDX
   (...)
     14 #              baseline_start = train_start,
     15 #              baseline_end = end)
---> 17 backtest_plot(df_account_value_a2c, 
     18              baseline_ticker = '^DJI', 
     19              baseline_start = train_start,
     20              baseline_end = end)

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\finrl\plot.py:67, in backtest_plot(account_value, baseline_start, baseline_end, baseline_ticker, value_col_name)
     64 baseline_returns = get_daily_return(baseline_df, value_col_name="close")
     66 with pyfolio.plotting.plotting_context(font_scale=1.1):
---> 67     pyfolio.create_full_tear_sheet(
     68         returns=test_returns, benchmark_rets=baseline_returns, set_context=False
     69     )

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\pyfolio\tears.py:180, in create_full_tear_sheet(returns, positions, transactions, market_data, benchmark_rets, slippage, live_start_date, sector_mappings, round_trips, estimate_intraday, hide_positions, cone_std, bootstrap, unadjusted_returns, turnover_denom, set_context, factor_returns, factor_loadings, pos_in_dollars, header_rows, factor_partitions)
    174     returns = txn.adjust_returns_for_slippage(returns, positions,
    175                                               transactions, slippage)
    177 positions = utils.check_intraday(estimate_intraday, returns,
    178                                  positions, transactions)
--> 180 create_returns_tear_sheet(
    181     returns,
    182     positions=positions,
    183     transactions=transactions,
    184     live_start_date=live_start_date,
    185     cone_std=cone_std,
    186     benchmark_rets=benchmark_rets,
    187     bootstrap=bootstrap,
    188     turnover_denom=turnover_denom,
    189     header_rows=header_rows,
    190     set_context=set_context)
    192 create_interesting_times_tear_sheet(returns,
    193                                     benchmark_rets=benchmark_rets,
    194                                     set_context=set_context)
    196 if positions is not None:

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\pyfolio\plotting.py:54, in customize.<locals>.call_w_context(*args, **kwargs)
     52         return func(*args, **kwargs)
     53 else:
---> 54     return func(*args, **kwargs)

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\pyfolio\tears.py:569, in create_returns_tear_sheet(returns, positions, transactions, live_start_date, cone_std, benchmark_rets, bootstrap, turnover_denom, header_rows, return_fig)
    565 plotting.plot_rolling_sharpe(
    566     returns, ax=ax_rolling_sharpe)
    568 # Drawdowns
--> 569 plotting.plot_drawdown_periods(
    570     returns, top=5, ax=ax_drawdown)
    572 plotting.plot_drawdown_underwater(
    573     returns=returns, ax=ax_underwater)
    575 plotting.plot_monthly_returns_heatmap(returns, ax=ax_monthly_heatmap)

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\pyfolio\plotting.py:442, in plot_drawdown_periods(returns, top, ax, **kwargs)
    440     if pd.isnull(recovery):
    441         recovery = returns.index[-1]
--> 442     ax.fill_between((peak, recovery),
    443                     lim[0],
    444                     lim[1],
    445                     alpha=.4,
    446                     color=colors[i])
    447 ax.set_ylim(lim)
    448 ax.set_title('Top %i drawdown periods' % top)

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\matplotlib\__init__.py:1412, in _preprocess_data.<locals>.inner(ax, data, *args, **kwargs)
   1409 @functools.wraps(func)
   1410 def inner(ax, *args, data=None, **kwargs):
   1411     if data is None:
-> 1412         return func(ax, *map(sanitize_sequence, args), **kwargs)
   1414     bound = new_sig.bind(ax, *args, **kwargs)
   1415     auto_label = (bound.arguments.get(label_namer)
   1416                   or bound.kwargs.get(label_namer))

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\matplotlib\axes\_axes.py:5245, in Axes.fill_between(self, x, y1, y2, where, interpolate, step, **kwargs)
   5243 def fill_between(self, x, y1, y2=0, where=None, interpolate=False,
   5244                  step=None, **kwargs):
-> 5245     return self._fill_between_x_or_y(
   5246         "x", x, y1, y2,
   5247         where=where, interpolate=interpolate, step=step, **kwargs)

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\matplotlib\axes\_axes.py:5151, in Axes._fill_between_x_or_y(self, ind_dir, ind, dep1, dep2, where, interpolate, step, **kwargs)
   5146         kwargs["facecolor"] = \
   5147             self._get_patches_for_fill.get_next_color()
   5149 # Handle united data, such as dates
   5150 ind, dep1, dep2 = map(
-> 5151     ma.masked_invalid, self._process_unit_info(
   5152         [(ind_dir, ind), (dep_dir, dep1), (dep_dir, dep2)], kwargs))
   5154 for name, array in [
   5155         (ind_dir, ind), (f"{dep_dir}1", dep1), (f"{dep_dir}2", dep2)]:
   5156     if array.ndim > 1:

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\matplotlib\axes\_base.py:2544, in _AxesBase._process_unit_info(self, datasets, kwargs, convert)
   2542             if dataset_axis_name == axis_name and data is not None:
   2543                 axis.update_units(data)
-> 2544 return [axis_map[axis_name].convert_units(data)
   2545         if convert and data is not None else data
   2546         for axis_name, data in datasets]

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\matplotlib\axes\_base.py:2544, in <listcomp>(.0)
   2542             if dataset_axis_name == axis_name and data is not None:
   2543                 axis.update_units(data)
-> 2544 return [axis_map[axis_name].convert_units(data)
   2545         if convert and data is not None else data
   2546         for axis_name, data in datasets]

File ~\AppData\Local\Programs\3.9-JupyterLab\lib\site-packages\matplotlib\axis.py:1508, in Axis.convert_units(self, x)
   1506     ret = self.converter.convert(x, self.units, self)
   1507 except Exception as e:
-> 1508     raise munits.ConversionError('Failed to convert value(s) to axis '
   1509                                  f'units: {x!r}') from e
   1510 return ret

ConversionError: Failed to convert value(s) to axis units: (NaT, Timestamp('2022-08-19 00:00:00+0000', tz='UTC'))
`

**Comment by lcjr86** [comment]
Hello @thistleknot,

I saw that you closed the ticket. Did you manage to fix the problem?
I have the same error message on my side...

Cheers,

**Comment by thistleknot** [comment]
I know I basically rolled back to a different dataset but I don't recall
having to do anything like a pd.to_datetime

**Comment by lcjr86** [comment]
ok, thanks

**Comment by notBradPitt** [comment]
For those wondering, it has something to do with your dates. From the config:

> # bug fix: set Monday right, start date set 2014-01-01 ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1658 and the array at index 1 has size 1657

I don't exactly know the rules, but changing the dates to Monday fixes the problem in my case
