### ISSUE TITLE
Error when running Tutorial Stock_NeurIPS2018_SB3.ipynb Can only use .dt accessor with datetimelike values

### ISSUE THREAD

**Issue by moon195** [AI4Finance-Foundation/FinRL#707]
**Describe the bug**
Can only use .dt accessor with datetimelike values
I used the exact same tutorials and packages in colab and locally, but had different results

**To Reproduce**
1. df = YahooDownloader(start_date = TRAIN_START_DATE,
                     end_date = TRADE_END_DATE,
                     ticker_list = config_tickers.DOW_30_TICKER).fetch_data()
2. See error 
~\Anaconda3\envs\py37\lib\site-packages\pandas\core\accessor.py in __get__(self, obj, cls)
    179             # we're accessing the attribute of the class, i.e., Dataset.geo
    180             return self._accessor
--> 181         accessor_obj = self._accessor(obj)
    182         # Replace the property with the accessor object. Inspired by:
    183         # https://www.pydanny.com/cached-property.html

~\Anaconda3\envs\py37\lib\site-packages\pandas\core\indexes\accessors.py in __new__(cls, data)
    504             return PeriodProperties(data, orig)
    505 
--> 506         raise AttributeError("Can only use .dt accessor with datetimelike values"
Can only use .dt accessor with datetimelike values

**Expected behavior**
[*********************100%***********************]  1 of 1 completed
Shape of DataFrame:  (94331, 8)

**Screenshots**
incolab![image](https://user-images.githubusercontent.com/75078647/187978939-4d39b821-310d-44b9-b0d1-b52652ce3d79.png)
local 
![image](https://user-images.githubusercontent.com/75078647/187979011-4b316014-cc2a-4bb0-9c82-fcae5eb90d9f.png)

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [ chrome,]

**Smartphone (please complete the following information):**

**Additional context**
I used the exact same tutorials and packages in colab and locally, but had different results，same pandas

**Comment by zhumingpassional** [comment]
Hi, sorry for delayed response. 

Your description is not very clear. I guess the data may contain timezones. you may pass utc=True to to_datetime, and set errors='coerce'. I am not sure.

could you pls paste all the code here?

**Comment by moon195** [comment]
[Stock_NeurIPS2018_SB3.zip](https://github.com/AI4Finance-Foundation/FinRL/files/9539556/Stock_NeurIPS2018_SB3.zip)
hi，The full code is the file in the tutorial. The strange thing is that I have no problem running it on colab, I have problems running it locally, all the versions of the  Package are the same. Also the problem occurs when I download the dataset on colab locally for pre-processing.It seems that the local code does not work with the Yahoo Finance data, but the same code works fine on colab

**Comment by XiaoYangLiu-FinRL** [comment]
> [Stock_NeurIPS2018_SB3.zip](https://github.com/AI4Finance-Foundation/FinRL/files/9539556/Stock_NeurIPS2018_SB3.zip)
> hi，The full code is the file in the tutorial. The strange thing is that I have no problem running it on colab, I have problems running it locally, all the versions of the Package are the same. Also the problem occurs when I download the dataset on colab locally for pre-processing.It seems that the local code does not work with the Yahoo Finance data, but the same code works fine on colab

Your description seems to echo Ming's judgement: colab is in the US time zone, and your local machine is in a different time zone.

**Comment by moon195** [comment]
At the same time,if i set the vis==true,there is same problem.
![image](https://user-images.githubusercontent.com/75078647/189471433-643fb977-82ea-4dac-85f7-24d53bcb1935.png)
![image](https://user-images.githubusercontent.com/75078647/189471442-e850b25c-4fbf-403f-9050-09139df24db4.png)
Is this because it doesn't read the downloaded Yahoo Finance data very well, but it doesn't have this problem when running on colab, which makes me confused

**Comment by moon195** [comment]
> > [Stock_NeurIPS2018_SB3.zip](https://github.com/AI4Finance-Foundation/FinRL/files/9539556/Stock_NeurIPS2018_SB3.zip) 
> > hi，完整代码是教程中的文件。奇怪的是，我在colab上运行没有问题，我在本地运行有问题，所有版本的Package都是一样的。当我在本地下载 colab 上的数据集进行预处理时也会出现问题。本地代码似乎不适用于 Yahoo Finance 数据，但相同的代码在 colab 上运行良好
> 
> 您的描述似乎与 Ming 的判断相呼应：colab 在美国时区，而您的本地机器在不同的时区。

ok,I will try to adjust the time zone

**Comment by moon195** [comment]
> Hi, sorry for delayed response.
> 
> Your description is not very clear. I guess the data may contain timezones. you may pass utc=True to to_datetime, and set errors='coerce'. I am not sure.
> 
> could you pls paste all the code here?

Do I need to add these two changes to jupyter or to the Yahoo download function

**Comment by moon195** [comment]
[yahoodownloader.zip](https://github.com/AI4Finance-Foundation/FinRL/files/9539698/yahoodownloader.zip)
I have uploaded this code about downloading data for your reference

**Comment by zhumingpassional** [comment]
@moon195 

In yahoodownloader.py, which lines did you revise? 

How did you call the functions in yahoodownloader.py? could you pls send related codes to me?

I tried the following, and it works:
tickers = ['AXP', 'AMGN']
start_date = '2022-01-15'
end_date = '2022-02-15'
y = YahooDownloader(start_date, end_date, tickers)
df = y.fetch_data()
df2 = y.select_equal_rows_stock(df)

**Comment by moon195** [comment]
> 
@zhumingpassional Thank you for your reply, I will make changes and try，by the way，This is the original code for calling Yahoo Finance
[yahoodownloader.zip](https://github.com/AI4Finance-Foundation/FinRL/files/9539830/yahoodownloader.zip)

**Comment by zhumingpassional** [comment]
I tried the original code, and it works.

yahoo stopped the service in some countries, e.g., China. If you are in these countries and run the code locally, you may need to use VPN

**Comment by moon195** [comment]
@zhumingpassional I tried your code but it still doesn't work because of my computer's settings regarding time zones? Or is it because I can only use vpn for access?
![image](https://user-images.githubusercontent.com/75078647/189475569-7246d9be-1afc-4ae8-9de7-ad6e45e2408b.png)
![image](https://user-images.githubusercontent.com/75078647/189475574-9b4b2c1a-98d3-4b19-8d92-9a309737917d.png)

**Comment by zhumingpassional** [comment]
yes. pls check your computer settings and vpn.

**Comment by moon195** [comment]
> 是的。请检查您的计算机设置和 vpn。

@zhumingpassional Thank you very much for your help and have a great day.
