### ISSUE TITLE
TypeError in Stock_Fundamental.ipynb

### ISSUE THREAD

**Issue by ZhLinda** [AI4Finance-Foundation/FinRL#726]
run in google colab:
https://colab.research.google.com/github/AI4Finance-Foundation/FinRL/blob/master/tutorials/1-Introduction/Stock_Fundamental.ipynb

code:
df_account_value_ppo, df_actions_ppo = DRLAgent.DRL_prediction(
    model=trained_ppo, 
    environment = e_trade_gym) if if_using_ppo else None

df_account_value_ddpg, df_actions_ddpg = DRLAgent.DRL_prediction(
    model=trained_ddpg, 
    environment = e_trade_gym) if if_using_ddpg else None

df_account_value_a2c, df_actions_a2c = DRLAgent.DRL_prediction(
    model=trained_a2c, 
    environment = e_trade_gym) if if_using_a2c else None

df_account_value_td3, df_actions_td3 = DRLAgent.DRL_prediction(
    model=trained_td3, 
    environment = e_trade_gym) if if_using_td3 else None

df_account_value_sac, df_actions_sac = DRLAgent.DRL_prediction(
    model=trained_sac, 
    environment = e_trade_gym) if if_using_sac else None

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-45-32d3a01eb334> in <module>
      1 df_account_value_ppo, df_actions_ppo = DRLAgent.DRL_prediction(
      2     model=trained_ppo,
----> 3     environment = e_trade_gym) if if_using_ppo else None
      4 
      5 df_account_value_ddpg, df_actions_ddpg = DRLAgent.DRL_prediction(

TypeError: cannot unpack non-iterable NoneType object

**Comment by zhumingpassional** [comment]
thanks for reporting it. we will test it.
