### ISSUE TITLE
Output trained RL models for use in other projects

### ISSUE THREAD

**Issue by julianzero** [AI4Finance-Foundation/FinRL#727]
Wondering if there is a way to output trained RL models from FinRL for the purpose of my own research?
Personally, I feel FinRL is too encapsulated, and there seems no way to output the trained models with fine-tuned weights and hyper-parameters without making changes inside Stable-baselines3?

Anyone can help?

Thanks.

**Comment by XiaoYangLiu-FinRL** [comment]
Yes, you can use pytorch to save the model.

**Comment by julian-z** [comment]
> Yes, you can use pytorch to save the model.

Is there such an example in the tutorials or somewhere? Thanx.

**Comment by Athe-kunal** [comment]
Hi @julian-z 
You can refer to this link https://stable-baselines3.readthedocs.io/en/master/guide/save_format.html to save and load model in SB3
