### ISSUE TITLE
Convert pandas appends to concat

### ISSUE THREAD

**Issue by jimdb8687** [AI4Finance-Foundation/FinRL#735]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
throughout the code append is used which has worse performance to concat. looks like it is mostly used in the downloading of data.

**Comment by zhumingpassional** [comment]
@jimdb8687 
we noticed it. we will revise it in the future. 
thanks for your suggestions.

**Comment by jimdb8687** [comment]
Have a lot of experience in python but not a lot in contributing I could make these changes and have on my fork just could use of guidance on how to contribute to this project.

**Comment by zhumingpassional** [comment]
@jimdb8687 could you pls submit a PR? I will review it.
