### ISSUE TITLE
Explain FinRL predictions

### ISSUE THREAD

**Issue by ndeepesh** [AI4Finance-Foundation/FinRL#744]
**Is your feature request related to a problem? Please describe.**
Does FinRL support explaining predictions from the network? It would be great to get some insights into how the network is taking decisions.

**Describe the solution you'd like**
System to explain each prediction

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by XiaoYangLiu-FinRL** [comment]
Explainability is very very important!

We started with a simple one. But you can definitely help us get a better approach.

1. Codes: https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/2-Advance/FinRL_PortfolioAllocation_Explainable_DRL.ipynb
2. Medium blog: https://medium.com/mlearning-ai/an-empirical-approach-to-explain-deep-reinforcement-learning-in-portfolio-management-task-e65a42225d9d
3. Paper: Guan, Mao, and Xiao-Yang Liu. "Explainable deep reinforcement learning for portfolio management: an empirical approach." Proceedings of the Second ACM International Conference on AI in Finance. 2021.
