### ISSUE TITLE
ElegantRL train index out of bounds error

### ISSUE THREAD

**Issue by diplinfmarkodrews** [AI4Finance-Foundation/FinRL#750]
Hi, I was trying to train a model with elegantRL.

net_dimension = 2**8
erl_params = {
    "learning_rate": 2**-15,
    "batch_size": 2**11,
    "gamma": 0.99,
    "seed": 312,
    "net_dimension": net_dimension,
    "target_step": 500,
    "eval_gap": 30,
    "eval_times": 1,
} 

IndexError                                Traceback (most recent call last)
Cell In [9], line 3
      1 from finrl.meta.env_stock_trading.env_stocktrading_np import StockTradingEnv
      2 from finrl.train import train
----> 3 train(start_date=TRAIN_START_DATE, 
      4       end_date=TRAIN_END_DATE, 
      5       ticker_list=["^GSPC"], 
      6       data_source="yahoofinance", 
      7       time_interval="1D", 
      8       technical_indicator_list=["rsi"], 
      9       drl_lib="elegantrl", 
     10       env=StockTradingEnv, 
     11       model_name="ppo", 
     12       erl_params=erl_params,
     13       break_step=1e5,
     14       if_vix=True)

File ~/.local/lib/python3.8/site-packages/finrl/train.py:60, in train(start_date, end_date, ticker_list, data_source, time_interval, technical_indicator_list, drl_lib, env, model_name, if_vix, **kwargs)
     53     agent = DRLAgent_erl(
     54         env=env,
     55         price_array=price_array,
     56         tech_array=tech_array,
     57         turbulence_array=turbulence_array,
     58     )
...
--> 239     buf_r_sum[i] = buf_reward[i] + buf_mask[i] * pre_r_sum
    240     pre_r_sum = buf_r_sum[i]
    241 buf_adv_v = buf_r_sum - buf_value[:, 0]

IndexError: index 557 is out of bounds for dimension 0 with size 1

Well, I have just setup FinRL-Meta. There is no version specified in the requirements. I have elegantrl version 0.3.3 installed.
Is this a known issue? Can you hint me in a direction pls?
Thanks a lot!
Great work guys!!!

**Comment by zhumingpassional** [comment]
recent, elegantrl is updated frequently.
you can use the stock env in elegatrl https://github.com/AI4Finance-Foundation/ElegantRL/blob/master/elegantrl/envs/StockTradingEnv.py
