### ISSUE TITLE
Demo_MultiCrypto_Trading.ipynb cannot run because of RLlib

### ISSUE THREAD

**Issue by HadiSDev** [AI4Finance-Foundation/FinRL#754]
**Describe the bug**
Importing `from agents.rllib_models import DRLAgent as DRLAgent_rllib` results in a RLlib error

**To Reproduce**
Run Demo_MultiCrypto_Trading.ipynb on Colab. 

**Error message**
```
ImportError                               Traceback (most recent call last)
[<ipython-input-11-c2f4f1f1ce9a>](https://localhost:8080/#) in <module>
      1 from agents.elegantrl_models import DRLAgent as DRLAgent_erl
----> 2 from agents.rllib_models import DRLAgent as DRLAgent_rllib
      3 from agents.stablebaselines3_models import DRLAgent as DRLAgent_sb3
      4 from meta.data_processor import DataProcessor
      5 

[/FinRL-Meta/agents/rllib_models.py](https://localhost:8080/#) in <module>
      5 from ray.rllib.agents.ddpg import td3
      6 from ray.rllib.agents.ppo import ppo
----> 7 from ray.rllib.agents.sac import sac
      8 
      9 MODELS = {"a2c": a2c, "ddpg": ddpg, "td3": td3, "sac": sac, "ppo": ppo}

ImportError: cannot import name 'sac' from 'ray.rllib.agents.sac' (/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/sac/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
--------------------------------------------------------------------
```

**Comment by Athe-kunal** [comment]
Hi @HadiSDev 
Yes, in Ray 2.0+, they have shifted all the RL algos to the algorithms folder. So that's why it is showing this error. This will require more than a few edits in the tutorial.

**Comment by HadiSDev** [comment]
Yes but the error comes from the agents folder not the tutorial it self. So I cant really edit it before editing whats in the agents folder

**Comment by Athe-kunal** [comment]
Yes, now in RLlib all the algorithms are inside the algorithms folder. Probably they have standardized the directory structure. So I am working on it and also on some feature additions like Ray tune.

**Comment by zhumingpassional** [comment]
@Athe-kunal 
we can  revise the install commands by adding the version.

**Comment by Athe-kunal** [comment]
Hi @zhumingpassional 
I checked with 
```
pip install ray==1.3.0
```
Because the default ray install is 2.0.0, but installing 1.3.0 will resolve this

**Comment by zhumingpassional** [comment]
@Athe-kunal  
Ok. good.
could you pls submit a PR?

**Comment by HadiSDev** [comment]
1.3.0 won't work in python 3.9

**Comment by Athe-kunal** [comment]
Ohh, I didn't check that. I was able to run it on colab. I need to check that.
