### ISSUE TITLE
Day_delta should be 1000 times smaller?

### ISSUE THREAD

**Issue by marcipops** [AI4Finance-Foundation/FinRL#757]
https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/meta/data_processors/processor_alpaca.py

Line 50

day_delta = 86400000000000  # pd.Timedelta('1D').delta == 86400000000000

Should this not be a 1000 times smaller i.e. 86,400,000,000 to represent the number of microseconds in a day (the smallest increment represented in pd.timedelta)?

**Comment by Athe-kunal** [comment]
Hi @marcipops 
Please see [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/timedeltas.html#timedelta-limitations). Pandas represents timedelta in nanoseconds, hence the extra 1000

**Comment by marcipops** [comment]
Hi @Athe-kunal, apologies, I misread.
Let's close the issue.
Much appreciated
