### ISSUE TITLE
unable to use it in INDIAN market like NIFTY 50 

### ISSUE THREAD

**Issue by Hardik921** [AI4Finance-Foundation/FinRL#760]
nifty 50 is an Index in which 50 stock(company are listed) .. i tried a lot but unable to use it in Indian stock market..
could you please Explain that how we DRL agent pick stock for buy and sell because I want to trade it only one stock but want to train it on 50 stocks. 

i use (.NS) in last every stock name because of yahoo finance  show Ticker like that--:
50 STOCKS NAME =  [
    "ICICIBANK.NS",
    "INDUSINDBK.NS",
    "BAJAJFINSV.NS",
    "ITC.NS",
    "ULTRACEMCO.NS",
    "BHARTIARTL.NS",
    "BAJFINANCE.NS",
    "RELIANCE.NS",
    "HEROMOTOCO.NS",
    "NTPC.NS",
    "MARUTI.NS",
    "SBIN.NS",
    "EICHERMOT.NS",
    "APOLLOHOSP.NS",
    "TCS.NS",
    "MCD.NS",
    "GRASIM.NS",
    "TATACONSUM.NS",
    "NESTLEIND.NS",
    "HINDALCO.NS",
    "COALINDIA.NS",
    "CIPLA.NS",
    "UPL.NS",
    "ASIANPAINT.NS",
    "DIVISLAB.NS",
    "TATAMOTORS.NS",
    "HDFC.NS",
    "HCLTECH.NS",
    "BPCL.NS",
    "ONGC.NS",
    "HDFCBANK.NS",
    "BAJAJ-AUTO.NS",
    "WIPRO.NS",
    "TITAN.NS",
    "JSWSTEEL.NS",
    "AMBUJACEM.NS",
    "BANKBARODA.NS",
    "HINDPETRO.NS",
    "HDFCLIFE.NS",
    "INDHOTEL.NS",
    "CHOLAFIN.NS",
    "ABB.NS",
    "TATAPOWER.NS",
    "SHREECEM.NS",
    "M&M.NS",
    "ASHOKLEY.NS",
    "GAIL.NS",
    "IDFCFIRSTB.NS",
    "RECLTD.NS",
    "SRTRANSFIN.NS",
    "TORNTPHARM.NS",
    "TRENT.NS",
]

**Comment by Athe-kunal** [comment]
Hi @Hardik921 
I think you can use this function to download the stocks data https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/meta/preprocessor/yahoodownloader.py#L36. Use this to fetch data or follow one of the tutorials to train a DRL agent

**Comment by Hardik921** [comment]
thanks i am going to try please help me in case i will not be able to

**Comment by zhumingpassional** [comment]
@Hardik921 
pls follow the tutorials, e.g., https://github.com/AI4Finance-Foundation/FinRL-Tutorials/blob/master/1-Introduction/Stock_NeurIPS2018_SB3.ipynb

we have not connected the Indian markets, and if you are interested in this work, I am glad to receive such data processors.
