### ISSUE TITLE
Help Wanted!

### ISSUE THREAD

**Issue by sahibnoor1996** [AI4Finance-Foundation/FinRL#765]
1)Can I use the (stocks env) on cryptocurrencies or there is a different environment for that?because there are lot of errors when using  cryptoenv
2)At the end of (Deep Reinforcement Learning for Stock Trading from Scratch: Multiple Stock Trading Using Ensemble Strategy), it shows the Annual return is 0.079474, Does it mean 7 percent yearly or 0.07 percent yearly?

**Comment by Athe-kunal** [comment]
1)Can you please mention the errors you are getting from CryptoEnv? We will try to fix it. But if you want historical crypto data, you can do it from Alpaca. First, you would need API keys from Alpaca, which is super easy to get, and then follow this [tutorial](https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/2-Advance/FinRL_Compare_ElegantRL_RLlib_Stablebaseline3.ipynb#4.1eRL) and go to part 4. There you can see in the train function, you can change the data processor to alpaca and pass in your API keys to get the data.
2) I think it means the former one, 7 percent yearly

**Comment by sahibnoor1996** [comment]
<img width="1190" alt="Screenshot 2022-11-06 at 23 59 30" src="https://user-images.githubusercontent.com/46872967/200188701-96f73052-3876-422e-ab71-edc528c290e2.png">


This is the error i am getting .One more thing , are cryptoenv and stocksenv  both same or is there any difference ?

**Comment by sahibnoor1996** [comment]
> 
Can you please tell me what does these results indicate then?


<img width="461" alt="Screenshot 2022-11-09 at 10 12 07" src="https://user-images.githubusercontent.com/46872967/200742279-4effb61c-fdac-42ed-953f-efc4b0ba091d.png">

**Comment by Athe-kunal** [comment]
It looks like there are no differences, just the first one is in percentage and the second one is not.
Stock dimension means the number of stocks in the portfolio. And, I guess most of the things of the two environment will be same, just the source of data is different
