### ISSUE TITLE
tutorial_this_works_1_18

### ISSUE THREAD

**Issue by Humbleman72** [AI4Finance-Foundation/FinRL#767]
AttributeError: module 'time' has no attribute 'clock'
The time.clock() method has been removed in Python 3.8 onwards. Hence if you are using the clock() method in Python 3.8 or above, you will get AttributeError: module ‘time’ has no attribute ‘clock’.  

Solution:
pip install SQLAlchemy --upgrade

**Comment by zhumingpassional** [comment]
thanks for reporting it.
we will update it in the near future.
