### ISSUE TITLE
tutorial_this_works_1_18 continued

### ISSUE THREAD

**Issue by Humbleman72** [AI4Finance-Foundation/FinRL#768]
A list of things that needs to be changed. Maybe it is abandoned? It is definitely not up to date.

neo_finrl must be replaced with meta

config.START_DATE -> config.TRAIN_START_DATE
config.END_DATE -> config.TRAIN_END_DATE

from finrl import config_tickers in the top
print(config.DOW_30_TICKER) -> print(config_tickers.DOW_30_TICKER)

ticker_list = config.DOW_30_TICKER).fetch_data() -> ticker_list = config_tickers.DOW_30_TICKER).fetch_data()
spamming the append error...so not updated to concat

Now we get the error ValueError: cannot find context for 'fork'
Go to [13] and search for fork
e = SubprocVecEnv([get_self for _ in range(n)], start_method="fork")
change "fork" with "spawn"

Then I get this 
AttributeError: module 'stable_baselines3.common.logger' has no attribute 'record'
The error has been explained in #239, but has not been implemented here.

change
#from stable_baselines3.common import logger -> from stable_baselines3.common import utils
search for "record" in the main body [12]
find  where the class is defined 
def return_terminal(self, reason="Last Date", reward=0):
insert under -> 
	self.logger = utils.configure_logger()
change 5 places: "logger.record" -> "self.logger.record"

And lastly for the plot to work you have to pip install following
pip install empyrical
pip install git+https://github.com/quantopian/pyfolio

**Comment by XiaoYangLiu-FinRL** [comment]
Thanks very much!   We are continuing updating, at a lower frequency.
For example, we are updating more frequently at ElegantRL and FinRL-Meta, when they are stable, we are merging back.

**Comment by zhumingpassional** [comment]
@Humbleman72  thanks for reporting it.
if you are free, could you pls submit a PR? thanks again for your valuable suggestions.
