### ISSUE TITLE
Fin-MARL

### ISSUE THREAD

**Issue by julianzero** [AI4Finance-Foundation/FinRL#769]
Is there a way to simulate MARL trading with FinRL? Wanna simulate a pool of trader agents~

Thanx.

**Comment by XiaoYangLiu-FinRL** [comment]
Actually, it is possible.  What scenario you would like to simulate?   It seems to be quite interesting.

**Comment by zhumingpassional** [comment]
Yes. Now ElegantRL supports several MARL algorithms.

**Comment by julianzero** [comment]
I need to build a pool of traders, each of which is an RL agent trained via FinRL. The pool no longer needs any raw data input or environment. Just let these RL agent trade with each other automatically, to simulate a real market.

Is there a way to do so?

Thanx.

**Comment by julianzero** [comment]
> Do you want to build a Market Simulator (matching orders)? Here is an example: https://github.com/AI4Finance-Foundation/Market_Simulator

Yes, I need to build an order-matching simulator. Does FinRL have second, millisecond, or minute level data sources?

Thanx a lot.

**Comment by zhumingpassional** [comment]
@julianzero 
you can try alpaca, which is supported in finrl,  but some values may be missing. 

buying the full data may be hard, since financial companies do not want to make it open to others.

**Comment by julianzero** [comment]
> @julianzero you can try alpaca, which is supported in finrl, but some values may be missing.
> 
> buying the full data may be hard, since financial companies do not want to make it open to others.

Where did you get the data for your market simulator?

Thanx.

**Comment by zhumingpassional** [comment]
it is supported by a company, and the data size is very small, which is only for test.

larger size of data will not be open to users.

**Comment by julianzero** [comment]
Why does the test program stop after just a few steps although the planning horizon is 30?
