### ISSUE TITLE
Array dimensions do not match in FinRL_PaperTrading_Demo.ipynb: processor_alpaca.py: df_to_array() 

### ISSUE THREAD

**Issue by marcipops** [AI4Finance-Foundation/FinRL#770]
**Describe the bug**

File: FinRL/tutorials/3-Practical/FinRL_PaperTrading_Demo.ipynb

I have been updating the dates daily to meet the requirements of a rolling 8 days train (6 days) test (2 days) period.  The code has been running successfully for the last few days, but today causes an error in function df_to_array() within file processor_alpaca.py.

  finrl/meta/data_processors/processor_alpaca.py", line 281, in df_to_array
    price_array = np.hstack(
  File "<__array_function__ internals>", line 180, in hstack
  File "numpy/core/shape_base.py", line 345, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 809 and the array at index 1 has size 782

**To Reproduce**
Steps to reproduce the behavior.

Set the following dates for train/test periods and run code.
(TRAIN - START DATE):  2022-10-27
(TRAIN - END DATE):  2022-11-03
(TEST - START DATE):  2022-11-04
(TEST - END DATE):  2022-11-07
(FULL TRAIN OVER 8 DAYS - START DATE):  2022-10-27
(FULL TRAIN OVER 8 DAYS - END DATE):  2022-11-07

**Expected behavior**
No error

**Desktop (please complete the following information):**
Ubuntu 20.04 on a VPS

 CLI

**Comment by Luc8102** [comment]
Having the same issue for me.

**Comment by marcipops** [comment]
I was trying to track 8 days behind the current date, so it was the most recent data for training/testing.  Have you reproduced the error using those dates I used?

**Comment by Luc8102** [comment]
Having the same issue here currently when I am trying to implement df_to_array()
The code: https://pastebin.com/XKzN1xFJ

**Comment by marcipops** [comment]
Fixed issue in PR #832 https://github.com/AI4Finance-Foundation/FinRL/pull/832.

The open and close trading times were an hour ahead of what they should be.

NYSE trading times are 14:30 - 20:59 UTC.

This caused the hstack() error in df_to_array() as the number of rows of prices per tic were not the same so arrays could not be stacked columnwise.

                price_array = np.hstack(
                    [price_array, df[df.tic == tic][["close"]].values]
                )

**Comment by marcipops** [comment]
Fixed issue in PR #832 https://github.com/AI4Finance-Foundation/FinRL/pull/832.

The open and close trading times were an hour ahead of what they should be.

NYSE trading times are 14:30 - 20:59 UTC.

This caused the hstack() error in df_to_array() as the number of rows of prices per tic were not the same so arrays could not be stacked columnwise.

                price_array = np.hstack(
                    [price_array, df[df.tic == tic][["close"]].values]
                )
