### ISSUE TITLE
How to download data from SSE_50 and CSI_300?

### ISSUE THREAD

**Issue by julianzero** [AI4Finance-Foundation/FinRL#771]
It failed to fetch SSE and CSI data from Yahoo Finance. 
Need help! Any shortcut included in FinRL convenient for downloading data from SSE and CSI?

Thanx.

**Comment by zhumingpassional** [comment]
pls use tushare, baostock, joinquant in finrl-meta. 

Yahoo Finance does not support  Chinese stocksl

**Comment by julianzero** [comment]
> pls use tushare, baostock, joinquant as shown in finrl-meta.
> 
> Yahoo Finance does not support China stocks.

**Comment by julianzero** [comment]
Well, Yahoo Finance actually does support the stock market of China.
The only differences are the ticker names; simply change the ticker names and Yahoo works perfectly.

**Comment by zhumingpassional** [comment]
Good. I have never tried yahoo for China stocks.
