### ISSUE TITLE
Yahoofinance gives error on date columns [Pandas]

### ISSUE THREAD

**Issue by HadiSDev** [AI4Finance-Foundation/FinRL#778]
**Describe the bug**
Yahoofinance does not seem to work DataProcessor
**To Reproduce**

```
ticker_list= ['BTC-USDT']
env = CryptoEnv
start_date= '2021-09-01'
end_date= '2021-09-02'
time_interval='5m'

dp = DataProcessor(data_source="yahoofinance")
df = dp.download_data(ticker_list=ticker_list,
                      start_date=start_date,
                      end_date=end_date,
                      time_interval=time_interval)
```

Error:

```
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values

```

**Expected behavior**
column should be a date column
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Python 3.9.14
 - FinRL == 0.3.5

**Comment by zhumingpassional** [comment]
yahoo may not support cryptocurrencies. pls try other data processors, e.g, binance.

**Comment by HadiSDev** [comment]
Yes you are right. I created an Alpaca account instead thanks, but there should probably be a user error when the dataset is len == 0

**Comment by zhumingpassional** [comment]
@HadiSDev  thanks for your suggestion. we will add this kind of hints  in the future.
