### ISSUE TITLE
Disconnect between stablebaseline's DRL_prediction() and terminal state

### ISSUE THREAD

**Issue by jjphung** [AI4Finance-Foundation/FinRL#780]
**Describe the bug**

In stablebaseline DRLAgent's [DRL_prediction()](https://github.com/AI4Finance-Foundation/FinRL/blob/f9e7b528ac9d31c12f52ad6a09aaf5a2b7242aba/finrl/agents/stablebaselines3/models.py#L123), if we wanted to get to the terminal condition, shouldn't we be checking for `dones` instead of the df environment's data (ie `i == (len(environment.df.index.unique()) - 2 `)?

This current check can pose a problem for other environments we'd want to integrate into FinRL in which predicting for backtesting can prematurely end depending on the terminal condition. For example, if we decide to check if the balance <= 0 or has stepped through all of the datas. I noticed that all current FinRL envs only terminate when the environment has stepped through all of the datas.

Is this intended behavior?

**Expected behavior**
When running the stablebaseline DRLAgent, I expect to be able to get the `save_asset_memory()` and `save_action_memory` of my environment when the stepping has terminated at the end of the episode.

**Errors**
`account_memory` Index out of bounds when returning from `DRL_prediction()`. This happens because `account_memory` and `actions_memory` lists are initialised to empty. If the if statement never gets filled then the lists will remain empty and there will be nothing to return.

**Comment by Athe-kunal** [comment]
Hi @jjphung 
Can you explain why your model is not going through the entire dataset? Because the entire dataset is the episode length, hence in each episode it should ideally go through the entire dataset.
Is it running out of cash? Also, your point on saving the account info and actions_df after done is correct.

**Comment by jjphung** [comment]
No problem; I am also little confused myself too on why it's not going through the entire dataset. 

The environment I am using is located here: [forex environment](https://github.com/cove9988/TradingGym/blob/master/env/env_fx_single_pair_window.py) . After implementing the `save_asset_memory()` and `save_action_memory()` functions to that environment, I run it according to this [jupyter notebook](https://gist.github.com/jjphung/b7a0777d57fc251a4f122020c4554add). I know it isn't running out of cash as I print the `self.balance` in every step. 

In that juptyer notebook gist, the `env_config_file="./env/config/gdbusd-test-9_not_training.json"` param while creating the trading gym is just `gdbusd-test-9.json` copied but with `is_training` set to `false`.

Let me know if you need more information!

**Comment by jjphung** [comment]
Looks like we are using `DRL_prediction_load_from_file()` for sb3 now.
