### ISSUE TITLE
AttributeError: 'CryptoEnv' object has no attribute 'amount'

### ISSUE THREAD

**Issue by tiang2002** [AI4Finance-Foundation/FinRL#782]
AttributeError: 'CryptoEnv' object has no attribute 'amount'
![image](https://user-images.githubusercontent.com/74613129/204070911-f104899a-57d8-4414-baf8-edb512814320.png)
there is a problem when i running the test function in FinRL_China_A_Share_Market.ipynb, i hope you can help me fix it.

**Comment by tiang2002** [comment]
![image](https://user-images.githubusercontent.com/74613129/204071009-7fc81fee-5a07-4ef0-9b95-238e99c93238.png)

**Comment by zhumingpassional** [comment]
recently elegantrl is updated frequently. pls choose other DRL libs such as stable baselines3.

**Comment by zhumingpassional** [comment]
> AttributeError: 'CryptoEnv' object has no attribute 'amount' ![image](https://user-images.githubusercontent.com/74613129/204070911-f104899a-57d8-4414-baf8-edb512814320.png) there is a problem when i running the test function in FinRL_China_A_Share_Market.ipynb, i hope you can help me fix it.

I did not quite follow you.
the China_A_share_market works: https://github.com/AI4Finance-Foundation/FinRL-Tutorials/blob/master/1-Introduction/China_A_share_market_tushare.ipynb

**Comment by zhumingpassional** [comment]
> 


recently elegantrl is updated frequently. pls choose other DRL libs such as stable baselines3.
