### ISSUE TITLE
Google Collab Notebook link not working

### ISSUE THREAD

**Issue by snakeawake** [AI4Finance-Foundation/FinRL#787]
When you click on google collab notebook link mentioned in the article for setup tutorial. The link is broken

Go to https://ai4finance.medium.com/finrl-for-quantitative-finance-install-and-setup-tutorial-for-beginners-1db80ad39159

**Comment by zhumingpassional** [comment]
I do not quite follow here. If you want to open tutorials of finrl, pls go to https://github.com/AI4Finance-Foundation/FinRL-Tutorials, and click the label "open in colab"

**Comment by zhumingpassional** [comment]
you may need to choose the notebook, e.g., finrl-tutorials. 

we revised the install commands, pls try it again.

**Comment by XiaoYangLiu-FinRL** [comment]
Google colab fails quite often.  We were trying to fix this every month……do not relie too much on the link, better to upload yourself and test under your own control.
