### ISSUE TITLE
Slack needs Columbia email address

### ISSUE THREAD

**Issue by JonathanLehner** [AI4Finance-Foundation/FinRL#789]
Could someone please invite me to the Slack? My email is lehnerj@student.ethz.ch. The registration only works with Columbia.edu addresses

**Comment by zhumingpassional** [comment]
https://ai4financeworkspace.slack.com/ssb/redirect 
can you enter this website?

**Comment by cove9988** [comment]
Hi Jonathan, I sent you an invitation, please check it out in your email.

**Comment by JonathanLehner** [comment]
Link didn't work, but invitation did. Thanks a lot!

**Comment by RijulGupta-DM** [comment]
Could you please send an invite to rijul.gupta@gmail.com?

**Comment by zhumingpassional** [comment]
@RijulGupta-DM  
I have invited you to slack
