### ISSUE TITLE
Installation failed with ERROR: No matching distribution found for ray[default,tune]==1.3.0

### ISSUE THREAD

**Issue by nemolin2008** [AI4Finance-Foundation/FinRL#793]
**Describe the bug**
Run "pip install . " under "FinRL" returns ERROR: No matching distribution found for ray[default,tune]==1.3.0. Suspect that this is because ray doesn't currently provide wheels for python 3.9.7

**Screenshots**
![image](https://user-images.githubusercontent.com/84784680/205480289-991e1fb2-227f-4cf7-8ff8-2a2e4bb32ed6.png)

**Desktop (please complete the following information):**
 - OS:  win11
 - Python 3.9.7

**Comment by ErikBaer** [comment]
Same here!
MacOSX M1 Silicon

**Comment by alex-seto** [comment]
if you check the [pyproject.toml](https://github.com/AI4Finance-Foundation/FinRL/blob/master/pyproject.toml) it shows python 3.7 - 3.8 as a dependency. I ran into same issue, downgraded to 3.8 and it worked for me

**Comment by Rodrigowb** [comment]
Having the same issue. Already tried to use earlier python versions (3.8), but still doesn't work.

**Comment by ErikBaer** [comment]
Thanks alex-seto for your asssistance. I downgraded to python 3.8.13, the oldest version readily available in conda.
The error still persists. As I said, also on an M1.
Should I downgrade even further ? Any suggestions on how to safely install older versions of Python orm get this running are much appreciated! 
Have a great day

**Comment by ErikBaer** [comment]
setting up a conda environment via miniconda with python 3.8.0 did the trick for me. The oldest version available on anaconda is 3.8.10, which is giving me said error.
Maybe try to go to 3.8.0 as I did!
