### ISSUE TITLE
start received with timezone defined as 'UTC' although a Date must be timezone naive

### ISSUE THREAD

**Issue by saidineshpola** [AI4Finance-Foundation/FinRL#804]
**Describe the bug**
Although I attempted to compile this file, Step 3.Data Cleaning & Feature Engineering of the process failed with following error. `ValueError: Parameter start received with timezone defined as 'UTC' although a Date must be timezone naive.`

**To Reproduce**
1.running  FinRL_PaperTrading_Demo.ipynb in local 
2. I removed timezone in session and then I got this while running **Step 4. Transform to numpy array**
`ValueError: Length of values (7350) does not match length of index (3750)`

**Screenshots**

![image](https://user-images.githubusercontent.com/81302966/205945393-93715197-855c-40fc-8708-b5b5ceb98408.png)

**Desktop :**
- python 3.8.15 ( happened with 3.10 version as well)
 - OS: ubuntu 22.01
 - VScode

**Comment by Athe-kunal** [comment]
Hi @saidineshpola 
Did you remove the time in the closing and opening time of the market?

**Comment by saidineshpola** [comment]
It was fixed in new update. the paper trading notebook working fine now.

**Comment by jamesgarza73** [comment]
I am having the same issue, and I am on the latest version. Any help would be greatly appreciated. I have removed the timezone and localized it to none. Not sure what else can be done to get this working.
