### ISSUE TITLE
Unable to Install FinRL on Colab

### ISSUE THREAD

**Issue by Guyodub** [AI4Finance-Foundation/FinRL#813]
![UnabletoInstallFinRL](https://user-images.githubusercontent.com/21237795/207107229-3cebce7a-7103-44ad-b6c5-4571161cd06e.jpeg)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Guyodub** [comment]
I am trying to install FinRL on Colab using the code; !pip install git+https://github.com/AI4Finance-LLC/FinRL-Library.git  but I am getting the error as per the screenshot above. Please assist. I need it for my research work.

**Comment by XiaoYangLiu-FinRL** [comment]
It seems that you are referring to some old steps.  Please let me know which doc are you looking at?

**Comment by zhumingpassional** [comment]
pls add !pip install swig before !pip install finrl

**Comment by Guyodub** [comment]
Thank you. It worked for me!
