### ISSUE TITLE
Create environment for episodic tasks 

### ISSUE THREAD

**Issue by R470R** [AI4Finance-Foundation/FinRL#818]
Hello, how can I create an environment that performs on episodic tasks ex:
I have a separated algo that provides signals 
From each signal I create ex an episode with 200 time steps for the agent to trade. 

How can I do this kind of work?

**Comment by zhumingpassional** [comment]
Is your env is gym style? 
If so, pls use DRL libraries, e.g., stable baselines 3, or elegantrl, and then you can set these params.

**Comment by R470R** [comment]
Thank you @zhumingpassional
