### ISSUE TITLE
FinRL_PaperTrading_Demo.ipynb  - APIError: request is not authorized

### ISSUE THREAD

**Issue by kruzel** [AI4Finance-Foundation/FinRL#853]
**Describe the bug**
in cell with `paper_trading_erl.run()`
raise error: APIError: request is not authorized

till this line alpaca api worked.

**To Reproduce**
1. FinRL_PaperTrading_Demo.ipynb - run all cells with SINGLE_TICKER

**Expected behavior**
run till the end

**Screenshots**
```
File C:\dev\trading\ai4finance\FinRL\venv\lib\site-packages\alpaca_trade_api\rest.py:242, in REST._one_request(self, method, url, opts, retry)
    240     error = resp.json()
    241     if 'code' in error:
--> 242         raise APIError(error, http_error)
    243 else:
    244     raise
    APIError: request is not authorized
```

APIError: request is not authorized

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Pycharm
 - Version NA

**Comment by zhumingpassional** [comment]
have you created alpaca account and set your api key/secrets?

**Comment by kruzel** [comment]
used market data keys by mistake, thanks
