### ISSUE TITLE
FinRL vs FinRL-Meta - duplicate code

### ISSUE THREAD

**Issue by kruzel** [AI4Finance-Foundation/FinRL#859]
hi,
I see that DataProcessor  in FinRL-Meta include much more options then in FinRL.
which version is more advanced, FinRL or FinRL-Meta?
or should I somehow mix them?

**Comment by zhumingpassional** [comment]
FinRL-Meta is a sub-project of FinRL, and FinRL-Meta supports more data sources, while FinRL only supports several stable data sources. 

we suggest to use FinRL first, while if it does not support the data source while FinRL-Meta does, pls use FinRL-Meta.

**Comment by XiaoYangLiu-FinRL** [comment]
FinRL will be kept stable for beginners, while FinRL-Meta will actively explore new data sources, new technical indicators, and new tasks.
