### ISSUE TITLE
Colab file doesnt work 

### ISSUE THREAD

**Issue by underwater84** [AI4Finance-Foundation/FinRL#861]
im trying to run finrl on the example colab file :
https://colab.research.google.com/github/mariko-sawada/FinRL_with_fundamental_data/blob/main/FinRL_stock_trading_fundamental.ipynb

and it doesnt work , when i try to install the finrl.git file 
i get this error message 
  ERROR: Failed building wheel for box2d-py

i want to play with the package but it seems its impossible

**Comment by zhumingpassional** [comment]
do you mean the turorial https://github.com/AI4Finance-Foundation/FinRL-Tutorials/blob/master/1-Introduction/Stock_Fundamental.ipynb?  it works.

do you run it by opening the colab?

**Comment by underwater84** [comment]
1. i added the link to the colab notebook - try and run it , it doesnt run 
2. the link you posted is to run a local notebook file , did it run for you locally or did you upload it to colab and it run ?

**Comment by underwater84** [comment]
notebook not found 
<img width="1085" alt="Screen Shot 2023-01-24 at 17 20 05" src="https://user-images.githubusercontent.com/33786869/214333991-19c941ac-d7f2-41eb-975c-067037563330.png">

**Comment by zhumingpassional** [comment]
pls turn to new repo https://github.com/AI4Finance-Foundation/FinRL-Tutorials

**Comment by underwater84** [comment]
i get the same error message as above , it redirects me to that address that doesnt work when i try to open it in colab 
please try and see .

**Comment by zhumingpassional** [comment]
after I clicking "open the colab“, I should choose the notebook in finrl-turorials, then 
I run it twice https://colab.research.google.com/github/AI4Finance-Foundation/FinRL-Tutorials/blob/master/1-Introduction/Stock_Fundamental.ipynb#scrollTo=osBHhVysOEzi
In the first time, it does not work, while in the second time, it works. 
pls check it.

**Comment by lucasdmoyer** [comment]
I have run the pip install/initial load of modules twice and it still is not working
![image](https://user-images.githubusercontent.com/23782501/215337283-915a57c0-9b56-40dc-9793-b9c67af1c560.png)

**Comment by chenzc0101** [comment]
> I have run the pip install/initial load of modules twice and it still is not working ![image](https://user-images.githubusercontent.com/23782501/215337283-915a57c0-9b56-40dc-9793-b9c67af1c560.png)

I met the same issue "cannot import name 'Arguments' from 'elegantrl.train.run'" when importing 

from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split

from finrl.plot import backtest_stats, backtest_plot, get_daily_return, get_baseline,convert_daily_return_to_pyfolio_ts

**Comment by chenzc0101** [comment]
I met this "ERROR: Failed building wheel for box2d-py" too. 

I fixed the issue by running:

!pip install Cmake
!pip install wheel
!pip install --upgrade pip
!pip install --upgrade setuptools
!pip install swig
!pip install box2d-py
!pip install box2d
!pip install Box2D

Then it works.
