### ISSUE TITLE
FinRL_Ensemble_StockTrading_ICAIF colab does not work

### ISSUE THREAD

**Issue by vakuku** [AI4Finance-Foundation/FinRL#870]
Step 2.3 Import Packages

`
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split
`

`from elegantrl.train.run import Arguments`

ImportError: cannot import name 'Arguments' from 'elegantrl.train.run'

**Comment by cedricfarinazzo** [comment]
Same issue with Stock_NeurIPS2018. It was working yesterday.

**Comment by cedricfarinazzo** [comment]
This line: https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/meta/env_stock_trading/env_stocktrading_np.py#L5
Introduced by this new commit https://github.com/AI4Finance-Foundation/FinRL/commit/4a7c8f3f61f7f755ff91bf0bc0e27a9a0cc20dda
