### ISSUE TITLE
Is there any demo to show how to fine tune the model?

### ISSUE THREAD

**Issue by jzhoulon** [AI4Finance-Foundation/FinRL#882]
I see the paper there is a fine tune stage with will refine the trained model, but I didn't find a demo in the example, the only example I find is retrain the model on test and train dataset, but in my understanding, the fine tune is trained on training dataset and load the trained model and finetune on test dataset. so I think there should be some api to load the model and fine tune the model, please correct me If I was wrong. Thanks

**Comment by zhumingpassional** [comment]
pls refer to https://github.com/AI4Finance-Foundation/FinRL-Tutorials/tree/master/4-Optimization
