### ISSUE TITLE
mean-var is outperforming every RL algorithms in this demo (Stock_NeurIPS2018_SB3.ipynb)

### ISSUE THREAD

**Issue by valleysprings** [AI4Finance-Foundation/FinRL#884]
I don't have any explanation to this. Does this mean RL algorithm is worse than traditional algorithm? Or Is this just a pure coincidence for lack of thorough fine-tuning here.

![output](https://user-images.githubusercontent.com/57850191/217709748-226be7c0-ab4f-4fda-98c6-17a74be8ad06.png)

**Comment by ZiyiXia** [comment]
The notebook is a reproduction of the process in the paper _Practical Deep Reinforcement Learning Approach for Stock Trading_. Our goal is demonstrating and sharing the work flow of FinRL.
Yeah like you said it needs fine tuning to have a greater performance. This might be changing the hyperparameters and longer total training steps. If you successfully find that of certain algorithm, feel free to share with the community.

**Comment by valleysprings** [comment]
Yeah sure! Thank you for your commenting. I think I will do some grid search if I have some free gpu resources.

**Comment by XiaoYangLiu-FinRL** [comment]
We look forward to your set of better parameters.
