### ISSUE TITLE
I don't understand why this is implemented as this? (env_stocktrading.py)

### ISSUE THREAD

**Issue by valleysprings** [AI4Finance-Foundation/FinRL#888]
Why this code is checking technical indicator to determine whether to sell or not? It could be an implementation to prevent some errors?    Hope someone will give me an answer. Thank you!

![image](https://user-images.githubusercontent.com/57850191/218292198-5fcddc82-24e1-4a32-b30d-5b6450d1268c.png)

**Comment by valleysprings** [comment]
And also this?  just the `self.state[index + 2 * self.stock_dim + 1] != True` statement.

![image](https://user-images.githubusercontent.com/57850191/218292438-1fd2008a-735e-41fa-8c99-f646d717e2ad.png)

**Comment by valleysprings** [comment]
Because I want to do some sort of ablation tests regarding to technical indicators? So I need to remove technical indicators once a while. This implementation prevent me from doing this.

**Comment by makovez** [comment]
> self.state[index + 2 * self.stock_dim + 1] != True

I agree with you this line may be outdated, cause as for now it doesen't make any sense. also because the self.state array does not contain any boolean value.
