### ISSUE TITLE
Why trading actions and rewards need this kind of transformation?

### ISSUE THREAD

**Issue by valleysprings** [AI4Finance-Foundation/FinRL#893]
I have no clue why trading action needs this kind of transformation. (exists in env_multiple_crypto)

![image](https://user-images.githubusercontent.com/57850191/218387101-b572f7e1-40ce-40e8-a9ef-1aa05b6dcfc5.png)

![image](https://user-images.githubusercontent.com/57850191/218386701-0dc93644-d607-4637-90a6-8985586e9164.png)

But meanwhile in the env_stocktrading, the transformation is controlled by `hmax`

![image](https://user-images.githubusercontent.com/57850191/218387461-002a1823-52e6-421d-8aac-02aa70ab3eec.png)

likewise, in env_multiple_crypto, the reward has this kind of linear transformation:

![image](https://user-images.githubusercontent.com/57850191/218387785-fdecbf73-7801-4f9e-8b9d-d774c7895388.png)

But in stocktrading env, this is not the case

![image](https://user-images.githubusercontent.com/57850191/218388121-dc7a780d-3e2a-4bff-bc46-a0c075df4cfb.png)

I mean those differences will make a huge impact on agent learning and actual performance. So is this done on purpose or is it just a one-shot experiment?

**Comment by valleysprings** [comment]
Frankly speaking, I am currently writing a little documentation in Chinese to help me get a better picture of DRL trading. No offence, but I believe those codes are not fully test yet as many similar code fragments are littered everywhere, and many codes are not functioning well. Hope it will get better cause it's open in nature and I wish more and more users will love using this without dealing enormous bugs.

**Comment by makovez** [comment]
@valleysprings i can't really understand your point. They are 2 different environments. What's wrong if they have a different reward function?

**Comment by valleysprings** [comment]
I mean it's not wrong, beacuse in RL setting you can have different kinds of rewards settings. But I think they are too different from each other. I am still trying to figure out whether this kind of linear transformation is appropriate or not. If you have done some kinds of searchs to find out the optimal reward setting for each env settings, then please let me know about that. Thank you!

**Comment by valleysprings** [comment]
@makovez  And for the `_generate_action_normalizer` function, I can not understand how it works. If you have some idea about that, I'd love to hear about that.

**Comment by makovez** [comment]
Text me on telegram @sbongown

**Comment by valleysprings** [comment]
OK, I text it. But it seems that I cannot send the message beacuse some sort of privacy setting (I don't know). I am in the FinRL group (@valleysprings) you can text to me.

**Comment by makovez** [comment]
I can't find you in telegram. What's your username? T.me/valleysprings
doesn't exist

Il mer 15 feb 2023, 11:10 Davidzjw ***@***.***> ha scritto:

**Comment by valleysprings** [comment]
I am sorry,  is Jiawei Zhou
