### ISSUE TITLE
🎨 fix 3 details in finrl.meta.preprocessor.tusharedownloader

### ISSUE THREAD

**Issue by Yonv1943** [AI4Finance-Foundation/FinRL#894]
@ https://github.com/lhonrush

@ZiyiXia 

### Detail 1

https://github.com/AI4Finance-Foundation/FinRL/blob/3db015dec04f0eb97d6af589a43bcb75adf82cfb/finrl/meta/preprocessor/tusharedownloader.py#L47-L48

should be: 

```
    def fetch_data(self) -> pd.DataFrame:
        """Fetches data from Tushare API
```

### Detail 2

https://github.com/AI4Finance-Foundation/FinRL/blob/3db015dec04f0eb97d6af589a43bcb75adf82cfb/finrl/meta/preprocessor/tusharedownloader.py#L84-L89

It is better to write `reset_index` behind `dropna` as following:

```
data_df = data_df.dropna()
data_df = data_df.reset_index(drop=True)
```

### Detail 3

https://github.com/AI4Finance-Foundation/FinRL/blob/3db015dec04f0eb97d6af589a43bcb75adf82cfb/finrl/meta/preprocessor/tusharedownloader.py#L96-L116

These two functions are repetitive and one of them should be deleted.

**Comment by ZiyiXia** [comment]
Thanks for the suggestions, will check them out.
