### ISSUE TITLE
Error "'numpy.ndarray' object has no attribute 'values'"

### ISSUE THREAD

**Issue by Boonsrp029** [AI4Finance-Foundation/FinRL#896]
**Error "'numpy.ndarray' object has no attribute 'values'"**

I run the code from this site https://www.kaggle.com/code/learnmore1/deep-reinforcement-learning-for-stock-trading-1/
which has no issues in the example but when I used it I run into this issue

![Screenshot 2023-02-16 142238](https://user-images.githubusercontent.com/49550816/219295949-4f6f9be9-1aae-414e-991a-922b21f8a5ab.png)

If pictures didn't show up, here's my Error code:

AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_24604\319122739.py in <module>
     11 }
     12 
---> 13 e_train_gym = StockPortfolioEnv(df = train, **env_kwargs)

~\AppData\Local\Temp\ipykernel_24604\3030550613.py in __init__(self, df, stock_dim, hmax, initial_amount, transaction_cost_pct, reward_scaling, state_space, action_space, tech_indicator_list, turbulence_threshold, lookback, day)
     95         # load data from a pandas dataframe
     96         self.data = self.df.loc[self.day,:]
---> 97         self.covs = self.data['cov_list'].values[0]
     98         self.state =  np.append(np.array(self.covs), [self.data[tech].values.tolist() for tech in self.tech_indicator_list ], axis=0)
     99         self.terminal = False

AttributeError: 'numpy.ndarray' object has no attribute 'values'

**Comment by ambresh1** [comment]
Hi @Boonsrp029 
I already opened an issue for the same bug [Here is Link](https://github.com/AI4Finance-Foundation/FinRL/issues/890#issue-1581350321)
Hope it gets resolved soon...

**Comment by zhumingpassional** [comment]
pls run https://github.com/AI4Finance-Foundation/FinRL-Tutorials/tree/master/1-Introduction/Stock_NeurIPS2018
