### ISSUE TITLE
libtorrent can not be installed in Mac

### ISSUE THREAD

**Issue by wlixin** [AI4Finance-Foundation/FinRL#898]
Using cached AutoROM.accept-rom-license-0.5.5.tar.gz (22 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Ignoring importlib-resources: markers 'python_version < "3.9"' don't match your environment
      Collecting setuptools
        Using cached setuptools-67.3.3-py3-none-any.whl (1.1 MB)
      Collecting wheel
        Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting requests
        Using cached requests-2.28.2-py3-none-any.whl (62 kB)
      Collecting tqdm
        Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
      ERROR: Could not find a version that satisfies the requirement libtorrent (from versions: none)
      ERROR: No matching distribution found for libtorrent

**Comment by XiaoYangLiu-FinRL** [comment]
> Using cached AutoROM.accept-rom-license-0.5.5.tar.gz (22 kB) Installing build dependencies ... error error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully. │ exit code: 1 ╰─> [14 lines of output] Ignoring importlib-resources: markers 'python_version < "3.9"' don't match your environment Collecting setuptools Using cached setuptools-67.3.3-py3-none-any.whl (1.1 MB) Collecting wheel Using cached wheel-0.38.4-py3-none-any.whl (36 kB) Collecting requests Using cached requests-2.28.2-py3-none-any.whl (62 kB) Collecting tqdm Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB) ERROR: Could not find a version that satisfies the requirement libtorrent (from versions: none) ERROR: No matching distribution found for libtorrent

Not sure which step requires libtorrent?

**Comment by zhumingpassional** [comment]
pls try git clone
