### ISSUE TITLE
How to make ElegantRL return actions? Is it even possible?

### ISSUE THREAD

**Issue by julianzero** [AI4Finance-Foundation/FinRL#913]
Hello everyone,

Is it possible to make ElegantRL return actions? Right now ElegantRL only returns the account values, so I have no choice but to look into SB3 instead.

Please help!

Thanx.

**Comment by Yonv1943** [comment]
You means: ElegantRL only outputs the training log on the screen, and you want to use a policy network after training for **inference**, that is, input states to it and let it return actions.

Yes, it is possible to make ElegantRL return actions. See this demo

https://github.com/AI4Finance-Foundation/ElegantRL/blob/68bf0ea4ef3fb461026ece8897deabb92aeead32/examples/demo_A2C_PPO.py#L699

```
for steps in range(12345):
    s_tensor = torch.as_tensor(state, dtype=torch.float32, device=device).unsqueeze(0)
    a_tensor = act(s_tensor).argmax(dim=1) if if_discrete else act(s_tensor)
    action = a_tensor.detach().cpu().numpy()[0]  # not need detach(), because using torch.no_grad() outside
    state, reward, done, _ = env.step(action)
    returns += reward
    env.render()
```

The following code is the kernel code **" to make ElegantRL return actions"**:
```
...
act = torch.load(f"./Pendulum_PPO_0/act.pt", map_location=device)
...
for steps in range(12345):
    ...
    a_tensor = act(s_tensor).argmax(dim=1) if if_discrete else act(s_tensor)
    action = a_tensor.detach().cpu().numpy()[0]  # not need detach(), because using torch.no_grad() outside
...
```

Feel free to continue to ask questions.

**Comment by julianzero** [comment]
> You means: ElegantRL only outputs the training log on the screen, and you want to use a policy network after training for **inference**, that is, input states to it and let it return actions.
> 
> Yes, it is possible to make ElegantRL return actions. See this demo
> 
> https://github.com/AI4Finance-Foundation/ElegantRL/blob/68bf0ea4ef3fb461026ece8897deabb92aeead32/examples/demo_A2C_PPO.py#L699
> 
> ```
> for steps in range(12345):
>     s_tensor = torch.as_tensor(state, dtype=torch.float32, device=device).unsqueeze(0)
>     a_tensor = act(s_tensor).argmax(dim=1) if if_discrete else act(s_tensor)
>     action = a_tensor.detach().cpu().numpy()[0]  # not need detach(), because using torch.no_grad() outside
>     state, reward, done, _ = env.step(action)
>     returns += reward
>     env.render()
> ```
> 
> The following code is the kernel code **" to make ElegantRL return actions"**:
> 
> ```
> ...
> act = torch.load(f"./Pendulum_PPO_0/act.pt", map_location=device)
> ...
> for steps in range(12345):
>     ...
>     a_tensor = act(s_tensor).argmax(dim=1) if if_discrete else act(s_tensor)
>     action = a_tensor.detach().cpu().numpy()[0]  # not need detach(), because using torch.no_grad() outside
> ...
> ```
> 
> Feel free to continue to ask questions.

I am talking about the tutorial examples, in which ElegantRL only returns account values, i.e., states plus values, but no actions. That returns actions is NOT implemented in DRLAgent.DRL_prediction().

Thanx.

**Comment by Yonv1943** [comment]
Thanx. I am checking 

https://github.com/AI4Finance-Foundation/FinRL/blob/3db015dec04f0eb97d6af589a43bcb75adf82cfb/finrl/test.py#L51-L53

and

https://github.com/AI4Finance-Foundation/FinRL/blob/3db015dec04f0eb97d6af589a43bcb75adf82cfb/finrl/agents/elegantrl/models.py#L87

**Comment by julianzero** [comment]
Please check the tutorial examples:
SB3
