### ISSUE TITLE
Want to make a new environment based on the one that used in the Stock_NeurlPS2018_SB3.ipynb

### ISSUE THREAD

**Issue by JojoLiu6697** [AI4Finance-Foundation/FinRL#925]
Hi, I am new to using FinRL. Currently, I am trying to modify the environment used in Stock_NeurlPS2018_SB3.ipynb. My goal is to only allow the network to trade stocks with low risks after making a decision. To achieve this, I added some new lines of code to the step() function:

start from line 302 in the original env_stocktrading.py

     `else:
            actions = actions * self.hmax  # actions initially is scaled between 0 to 1
            actions = actions.astype(
                int
            )  # convert into integer because we can't by fraction of shares
            current_volatility = self.df.loc[self.day, ["rolling_volatility", "tic"]]
            low_risk_threshold = current_volatility["rolling_volatility"].quantile(0.2)
            low_risk_stocks = current_volatility[current_volatility["rolling_volatility"] <= low_risk_threshold]["tic"].to_list()
            filtered_actions = actions.copy()

            for stock in self.df["tic"].unique():
                if stock not in low_risk_stocks:
                    filtered_actions[np.where(self.df["tic"].unique() == stock)[0][0]] = 0 \
                        if filtered_actions[np.where(self.df["tic"].unique() == stock)[0][0]] > 0 \
                            else -self.state[self.stock_dim+1 + np.where(self.df["tic"].unique() == stock)[0][0]]
            actions = filtered_actions

            if self.turbulence_threshold is not None:
                if self.turbulence >= self.turbulence_threshold:
                    actions = np.array([-self.hmax] * self.stock_dim)
            begin_total_asset = self.state[0] + sum(
                np.array(self.state[1 : (self.stock_dim + 1)])
                * np.array(self.state[(self.stock_dim + 1) : (self.stock_dim * 2 + 1)])
            )`

I did not make any changes to other functions. The agent was trained without any bugs, and the actions predicted by the trained agent are exactly what I want. However, when I use the original environment, the actions predicted by the same agent differ from my customized environment. For example, if I ask the agent to predict for 30 stocks, in the original environment, the agent may make trades with 15 stocks, whereas in my customized environment, the agent only trades with 5 stocks. Nevertheless, the account value output by both predictions is the same. Could someone please help me with this?

And that's how I call them:

```
stock_dimension = len(trade.tic.unique())
state_space = 1 + 2*stock_dimension + len(INDICATORS)*stock_dimension
buy_cost_list = sell_cost_list = [0.001] * stock_dimension
num_stock_shares = [0] * stock_dimension

env_kwargs = {
    "hmax": 100,
    "initial_amount": 1000000,
    "num_stock_shares": num_stock_shares,
    "buy_cost_pct": buy_cost_list,
    "sell_cost_pct": sell_cost_list,
    "state_space": state_space,
    "stock_dim": stock_dimension,
    "tech_indicator_list": INDICATORS,
    "action_space": stock_dimension,
    "reward_scaling": 1e-4
}

e_trade_gym = CustomStockTradingEnv(df = trade, turbulence_threshold = 70,risk_indicator_col='vix', **env_kwargs)
e_trade_gym_no_filter =StockTradingEnv(df = trade, turbulence_threshold = 70,risk_indicator_col='vix', **env_kwargs)

df_account_value_td3, df_actions_td3 = DRLAgent.DRL_prediction(
    model=trained_td3, 
    environment = e_trade_gym)

df_account_value_td3_nf, df_actions_td3_nf = DRLAgent.DRL_prediction(
    model=trained_td3, 
    environment = e_trade_gym_no_filter)
```

**Comment by shql-tgr** [comment]
Hi @JojoLiu6697, were you able to solve this problem?
